### ISSUE TITLE
Question regarding YT+ in combination with YT subsciptions grid

### ISSUE THREAD

**Issue by Niddi** [ParticleCore/Particle#101]
Hello.

I hope you don't mind me posting this question here, as it's not directly an issue with YT+.

I've been using YTC for a long time now. Since the option to hide watched videos in YTC does not work anymore, I added YT subscriptions grid (YTSG) to my list of addons and it works like a charm. I learned about YT+ reading the YTC Issues forum and gave it a try. What can I say, I really like it. It's slim and not as bloated as YTC and has almost everything I'm looking for. I really love to option for the video to follow you when reading the comments.
Unfortunately YT+ doesn't seem to work with YTSG. I know that you are not planning to add an option to hide watched videos anytime soon, but I would like your input on this. Maybe there is a way to get these two addons to work together.

a) When running YT+ (latest userscript with Greasemonkey) with YTSG the "Load more" button just doesn't want to work. If I click on "My subscriptions" on the left side or simply reload the page, it will load without integrating YTSG at all. It's as if I don't have it installed. To fix this, I have to click on "All activity" once. When I go back to "Uploads only", everything is working (YT+ and YTSG), even the "Load more" button. That is, until I refresh the page. After that it stops working again.

b) When deactivating Greasemonkey (or just the YT+ script), it's the same problem. So this seems to be an issue with YTSG and YouTube.

c) Now for the strange part: when running YTSG with the latest Developer version of YTC, everything is working from the start. I can refresh the page or do other stuff on YouTube and everything just keeps on working.So for some reason YTC seems to do something that enables YTSG to always work.

So my actual question is if you have any idea what might be causing this and if there is a way to copy this behaviour with YT+?

Browser Name: Firefox

Browser Version: 41.0.1

Operating System: Win 10 Pro 64Bit

Software Type: Userscript

Software Version: 0.7.4

Userscript Manager: Greasemonkey

Userscript Version: 3.4.1

**Comment by ParticleCore** [comment]
In YT+ settings go to General > General and activate "Disable SPF". Refresh YouTube and see if your issue is solved.

**Comment by Niddi** [comment]
Hey, that worked :) Thanks a lot for the quick help!
