### ISSUE TITLE
Palemoon problem

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#102]
I can't open the settings on palemoon, greasemonkey. 
But it worked on some of the previous versions, and only recently when I tried to go and check the settings, I found that the button doesn't do anything

**Comment by ParticleCore** [comment]
I am sorry but I am not providing support for Palemoon: https://github.com/ParticleCore/Particle/wiki

A possible workaround is to downgrade to the version that was working.

If someone wishes to fork a version for Palemoon then feel free to do so, as long as the license is respected.

**Comment by q1k** [comment]
The button stops displaying the settings on version 0.6.9
So the last fully working one is 0.6.8,
What exactly was changed in this one?

**Comment by ParticleCore** [comment]
You can click on the commits to find out exactly what changed: https://github.com/ParticleCore/Particle/commit/99da5fe1c3babf5fabe737c2b3b603fd754f1377

**Comment by q1k** [comment]
interestingly enough, the script seems to be working fine on seamonkey.

**Comment by ParticleCore** [comment]
It is very likely that one or more methods introduced in 0.6.9 are not compatible with Palemoon but are compatible with Seamonkey.

**Comment by Domochevsky** [comment]
According to the Pale Moon team, this particular issue can be fixed by replacing all instances of getElementById(" 
with 
querySelector("#
since "MDN says NOTHING about having `getElementById` on `DocumentFragment` object."

**Comment by ParticleCore** [comment]
@Domochevsky YT+ no longer makes use of the dom node `documentFragment` for quite a few versions already and when it did use it, it was strictly used with `querySelector` in `documentFragment` because, like you said, `getElementById` does not work with `documentFragment`, it never did.

**Comment by Domochevsky** [comment]
@ParticleCore according to the PM team "`typeof()` insisting that those elements are DocumentFragments".
They also say that "temp creates a new context inside the existing document, it's not a document in itself (document.createElement creates an element, not a document). As such, the resulting structure that is manipulated and passed around is not a document but only a fragment of it."

**Comment by ParticleCore** [comment]
Support is only being provided for Firefox and Chrome, if either of them starts having issues with the current method then I will try to change it.

If Pale Moon wants to be diferent then that is not my concern seeing that it is not a browser I am supporting.

Please do not insist more on this issue, if it isn't Firefox or Chrome then I will not provide support for it.

**Comment by ParticleCore** [comment]
Just out of curiosity, in the YT+ code if you change 

````javascript
pWrapper.getElementById("P-container").appendChild(template("GEN"));
````
to
````javascript
pWrapper.querySelector("#P-container").appendChild(template("GEN"));
````
Does the settings menu start working?

**Comment by Domochevsky** [comment]
No, that alone does not work. It then moves on to "TypeError: menu.getElementById is not a function", which seems to be part of list = menu.getElementById("blacklist");

If that is changed to querySelector as well THEN the menu will open.

**Comment by ParticleCore** [comment]
Forgot that one, so if it is changed to `menu.querySelector("#blacklist")` it works correctly for you too? There's no other errors after that one?

**Comment by Domochevsky** [comment]
It will open successfully without error, yes.

However, settings are not saved across page reloads. (But that seems vaguely unrelated to the the issue at hand.)

**Comment by ParticleCore** [comment]
The performance impact seems negligible so the next version will ship with the querySelector method instead.

Settings not saving is a different issue and I don't intend on finding out the root of the problem. Currently YT+ makes use of MutationObserver with documentElement data attributes to communicate the setting changes between the page and the content script, whatever the problem might be I suspect it is related to that.

**Comment by ParticleCore** [comment]
Version 0.7.8 is available and ships with the changes discussed here.
