### ISSUE TITLE
Individual repeat, randomize and autoplay settings for each playlist

### ISSUE THREAD

**Issue by reboot** [ParticleCore/Particle#103]
I would be nice if YouTube+ could remember playlist settings like repeat, randomize and autoplay individually for each playlist. I have some playlists I want to autoplay, but I don't want to play all playlists automatically. So every time i enabled it for one of the autoplay playlist, all others will be autoplayed too after that, until I disable it again. i would be nice if this setting could be remembers for each playlist to I don't have to enable and disable it again and again when watching different playlists.

**Comment by ParticleCore** [comment]
Sorry but I don't find these features useful so I will not be adding them for now.

**Comment by SW1FT** [comment]
Repeating a certain video would be such a great feature for someone who wants to listen to a certain music for a while without having to constantly click on repeat. Please reconsider.

**Comment by ParticleCore** [comment]
@SW1FT There is already the "Repeat video" button in the advanced controls (below the player) which does exactly just that: https://github.com/ParticleCore/Particle/wiki/Features#adv_repeat
