### ISSUE TITLE
Feature request: Channel trailer autoplay

### ISSUE THREAD

**Issue by m-thorsen** [ParticleCore/Particle#104]
Would it be within the scope of this addon to toggle autoplay of channel trailers separately from requested videos/playlists?

**Comment by ParticleCore** [comment]
This is a feature that I considered implementing at the beginning, but didn't find it to be that much useful during my experience so I won't be implementing it for now. However I intend to add it once Firefox starts allowing webextensions.

**Comment by q1k** [comment]
I support this.
