### ISSUE TITLE
A new endscreen - Feature request

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#106]
Can we have another type of endscreen?
Please note that this is the layout that appears if "UpNext Auto-Play" is turned on. I just deleted a few things.

So if we have the upnext (autoplay next video) feature turned off, we could have another type of endscreen. The background is the thumbnail picture.
![New endscreen](http://i.imgur.com/c9Rjdd3.jpg)

**Comment by ParticleCore** [comment]
This is not a feature I find to be useful.

**Comment by q1k** [comment]
Why not?
it basically resembles the older youtube endscreen (before they made the thumbnails). As so:
![Older Youtube Endscreen](https://www.stretchclock.com/more/images/support/adjust-volume.png)

**Comment by ParticleCore** [comment]
Hope you don't mind, but I will repeat what I explained to another user regarding adding new features:

>It's not due to lack of interest but because I don't want to add more features unless I find them to be useful. The software has already reached a point where it has too many features for me to be comfortable with maintaining, especially with YouTube changing so often. If I were to add every feature that is requested I would very likely be having trouble now trying to maintain the software and keeping it light, eventually getting tired of it and abandoning the project.

>I would love to make a full feature packed software with all possible features requested by the users, but the frequent changes on YouTube do not permit it, at least not with just one person possessing limited time and programing knowledge.

>I hope you understand.

**Comment by q1k** [comment]
You also said, you keep in mind all features suggested, so you may add them in the future, am I right?

**Comment by ParticleCore** [comment]
That is correct, each feature label is always a possibility in future versions. I often click on them and check each one individually now and then to see if there is one I could add.

**Comment by q1k** [comment]
I'm sure there would be others too who don't like the thumbnail endscreen, and would like this feature included.
Thanks for considering it.

**Comment by thegrandpow** [comment]
At least is it possible to have the endscreen that appears on embedded videos, when the videos thumbnails is off.?

Basically the endscreen looks just like the second image posted here.
If endscreen is simply disabled, it is not possible to click anywhere on the video to start it again (only on the play/pause/replay button).
