### ISSUE TITLE
Feature request - Click anywhere on collapsed video description to open

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#107]
As the title says, click anywhere on the collapsed video description to open it.
This was a default feature on youtube a few months ago. But then they made it so that we actually have to click the button, which can be really annoying. 
And possibly return the gradient background that was over the collapsed description. As so: 
```
.yt-uix-expander-collapsed #watch-description {
background: linear-gradient(to bottom, transparent, #ccc);
}
```

**Comment by ParticleCore** [comment]
Sorry but I don't find this feature to be useful.
