### ISSUE TITLE
Enhancement feature - Hide small player when video is paused

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#109]
So basically hide small player (player always visible when reading comments) when video is not playing (video ends or is paused)

**Comment by ParticleCore** [comment]
This wouldn't be practical, every time a user wanted to resume the video he would have to leave the comment area to press play and then return to the comment area again.

**Comment by q1k** [comment]
not really, by pressing space anywhere on the page we play/pause the video.

**Comment by ParticleCore** [comment]
That is only possible for users that have global shortcuts enabled.

**Comment by q1k** [comment]
So maybe force enable shortcuts?

**Comment by ParticleCore** [comment]
Then users that don't want them enabled would request for them to be disabled. This is not an enhancement that will be implemented.

**Comment by q1k** [comment]
So just show a message, warning them of what happens, if they do want to hide paused/stopped floater player and shortcuts are disabled.
