### ISSUE TITLE
Youtube Plus : How do I disable the "Player always visible when reading comments" feature?

### ISSUE THREAD

**Issue by tjak19** [ParticleCore/Particle#110]
Hi,
How do I disable the "Player always visible when reading comments" feature?
Thank you! Great Add-On ...
Tom

**Comment by tjak19** [comment]
Hi,
How do I disable the "Player always visible when reading comments" feature?
Thank you! Great Add-On ...
Tom

**Comment by tjak19** [comment]
Hi,
How do I disable the "Player always visible when reading comments" feature?
Thank you! Great Add-On ...
Tom

**Comment by tjak19** [comment]
Hi,
How do I disable the "Player always visible when reading comments" feature?
Thank you! Great Add-On ...
Tom

**Comment by ParticleCore** [comment]
It is in the settings menu available in any YouTube page. The icon to open the settings menu is located on the top right of the page (dark grey triangle with a + sign over it).

Click it and when the settings menu opens go to `Video` > `Player Settings` and then turn off `Player always visible when reading comments`. Save the settings and reload the page, now the player should not follow when you scroll down to read the comments.

**Comment by tjak19** [comment]
Thanks! Worked like a charm.

On October 23, 2015 1:54:25 PM MST, Particle <notifications@github.com> wrote:
>It is in the settings menu available in any YouTube page. The icon to
>open the settings menu is located on the top right of the page (dark
>grey triangle with a + sign over it).
>
>Click it and when the settings menu opens go to `Video` > `Player
>Settings` and then turn off `Player always visible when reading
>comments`. Save the settings and reload the page, now the player should
>not follow when you scroll down to read the comments.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ParticleCore/Particle/issues/110#issuecomment-150690423

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
