### ISSUE TITLE
Pressing space bar to play videos only scrolls page.

### ISSUE THREAD

**Issue by HighMans** [ParticleCore/Particle#111]
Browser Name: Chrome

Browser Version: 46.0.2490.71 m

Operating System: Windows 10 Ultimate

Software Type: Tampermonkey

Software Version: 3.11

Problem Description: Pressing space bar to play videos only scrolls page.

Steps to reproduce:  Press space bar on a video page.

Additional details:

**Comment by ParticleCore** [comment]
This is the normal YouTube behavior. Unless you have the player active (meaning you have to click on it for it to become active) the spacebar will scroll the page.

YT+ has a feature that makes the [player shortcuts always active](https://github.com/ParticleCore/Particle/wiki/Features#shortcuts_on) exactly for this purpose. This will allow the spacebar to play the video (and any other player shortcut to do its function) without having to click on the player, but you have to enable it in the YT+ settings first for it to work.

**Comment by Eisys** [comment]
Actually I am seeing this behaviour with said feature enabled.

For me, steps to reprocude are:

Go to a video(from sub box or a user's channel; feature works as intended), then click on the user's channel name, leading me to their videos, then click on another video of theirs, and now, pressing space scrolls down and arrow keys don't work for audio level or skipping 5 seconds. If I refresh the page at this point, it starts working again.

SPF seems to be at fault here. If I disable SPF and follow said steps again, everything works correctly.

**Comment by ParticleCore** [comment]
This is why I ask in the report template to be as precise as possible when describing the problem.

Despite that, I have just replicated your steps and the issue does not occur. The shortcuts remain active after the last step.

Have you disabled all other extensions except YT+, restart Chrome and see if the issue persists?

If it still persists could you post your YT+ settings so that I can try to replicate the problem using exactly the same settings as the ones you are using? You don't need to include your blacklist for this.

**Comment by Eisys** [comment]
Disabled everything else. Restarted chrome. Still happened.
Cleared browsing data and ran CCleaner. Still happens.
My settings: http://pastebin.com/xn3qJzS8

Another way to reproduce is to go to a video, then click the YT button on top left, brings me to subs page, and then go to any video again.

**Comment by ParticleCore** [comment]
I was finally able to replicate the problem, I suspect It wasn't possible before because I had autoplay disabled, will try to find out what is happening.

**Comment by ParticleCore** [comment]
YT+ 0.7.6 contains a fix for this problem, let me know if it works for you as well.

Also thanks for your help with this, Eisys.

**Comment by Eisys** [comment]
Absolutely no problem. ;)

I'm guessing the Chrome addon version will take a little while to update so I installed Tamper and script version to test, and it works perfectly now.

Thank you!

**Comment by ParticleCore** [comment]
That's correct, the Webstore update is not immediately available, but I have observed processing times as low as 30mins, however unless you force the extension update on your end the browser will only check according to its own period which I believe to be every 24h.

**Comment by ParticleCore** [comment]
Correct that, less than 15 minutes. I just forced the extension update on Chrome and it already updated to 0.7.6, guess they might have an extension record that rewards those with good standings, being the shorter update publications one of the perks.
