### ISSUE TITLE
Feature request: automatically set location

### ISSUE THREAD

**Issue by notDavid** [ParticleCore/Particle#112]
Hi, great addon!

i don't use a Google account, and i use [Self Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) to remove all (tracking) cookies. Therefore every time i use Youtube it forgets my location.

Would it be possible in the Youtube Plus addon to configure a static location = Worldwide ?
<img width="1440" alt="screen_shot_2015-10-27_at_17_24_15" src="https://cloud.githubusercontent.com/assets/1530401/10764935/c9aa0142-7cd0-11e5-9ade-b97d402a1944.png">

Also, the "Choose your language" bar is very annoying:
<img width="1440" alt="screen_shot_2015-10-27_at_17_23_17" src="https://cloud.githubusercontent.com/assets/1530401/10764948/da512e8a-7cd0-11e5-981f-85a405e72cc1.png">

Thanks.

**Comment by ParticleCore** [comment]
Sorry but I don't intend to add this feature for now.

A better way would be to use the whitelist feature in the other add-on and add the YouTube cookie that you wish to maintain.
