### ISSUE TITLE
Settings icon is hidden/transparent in 0.7.6

### ISSUE THREAD

**Issue by whispy** [ParticleCore/Particle#113]
Using FF 41.0.2.

The icon is still clickable if you know where it is located, but otherwise, it would be impossible to find.

**Comment by ParticleCore** [comment]
The icon is working correctly on all 3 types of YT+ and both in Firefox and Chrome. Disable all add-ons except YT+, restart Firefox and see if the problem still persists.

**Comment by luxoflux** [comment]
If you happen to be using the userscript, note that it makes a connection to https://particlecore.github.io/Particle/stylesheets/YouTubePlus.css, so make sure that's allowed if you're using a blocker. I myself just integrated the stylesheet into the userscript to avoid that remote connection.

**Comment by ParticleCore** [comment]
I will close this issue for now, if @whispy is still having problems let me know.
