### ISSUE TITLE
can you take this as reference or HELP to develop it? 

### ISSUE THREAD

**Issue by kliop00023** [ParticleCore/Particle#115]
just because YePpHa got a full time job and it is not easy for him to develop the js on it own :<

YePpHa/YouTubeCenter
https://github.com/YePpHa/YouTubeCenter

**Comment by ParticleCore** [comment]
It is not a project I would be capable of taking over for the time being, it would require too much work which I can't spare and I don't intend to copy it, my intentions have always been to create a lighter and smaller option for those that wanted it.
