### ISSUE TITLE
Ads on main Home screen

### ISSUE THREAD

**Issue by pyromanci** [ParticleCore/Particle#116]
On the main page of you tube that shows your recommendations and the like. There is normally a Ad Div. It's ID is ad_creative_1. would be nice if there was option to remove this div.

**Comment by ParticleCore** [comment]
YT+ is removing the advertisement and the respective div container in all current versions both in Firefox and Chrome, as long as the option [`Disable advertisements outside the video page`](https://github.com/ParticleCore/Particle/wiki/Features#outside_ads) is activated.

Make sure you don't have that option deactivated and it's an adblocker that is actually removing the advertisment but not the div.

Providing more details would be useful, which YT+ version you are using, what browser, which browser version, etc.

https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having problems let me know.
