### ISSUE TITLE
Volume bar popup when changed via mouse wheel

### ISSUE THREAD

**Issue by markreg** [ParticleCore/Particle#119]
It would be convenient to see the volume level when the mouse wheel is used to increase/decrease the volume.

**Comment by ParticleCore** [comment]
I've thought about it when I was developing the feature, but then users would request for the ability to customize the colors, the type, the text, not show it at all, etc. So I decided to not add it.

**Comment by markreg** [comment]
That's cool. Although, even a momentary expansion of the volume panel to show the red bar's width changing would be sufficient I think.

**Comment by ParticleCore** [comment]
I have added this functionality in version 1.2.3, once it is being used the player's own volume slider should become visible for the duration of the volume change. Let me know if it works for you as well.
