### ISSUE TITLE
Settings will not save on Safari 9.0.1

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [ParticleCore/Particle#120]
I am using Safari 9.0.1 on OS X 10.11 with Tampermonkey 3.12
The script itself seems to function without issue but as soon as I refresh the page or open a new tab all my settings are lost. I noticed in the export/import textbox that the settings reset to 

```
{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": true,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": true,
  "GEN_SDBR_ON": true,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "auto",
  "VID_PLST_SEP": true,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_FIT_WDTH": "1280px",
  "VID_HIDE_COMS": "1",
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": true,
  "VID_SDBR_ALGN": "1",
  "BLK_ON": true,
  "volLev": 50,
  "plApl": false,
  "plRev": false,
  "advOpts": true,
  "blacklist": {},
  "extLang": {}
}
```

I've tried reinstalling the script, tampermonkey and even clearing my safari user data out completely to see if it would fix the problem, but it does not.

**Comment by ParticleCore** [comment]
I am sorry but I am only providing support for Firefox and Chrome: https://github.com/ParticleCore/Particle/wiki
