### ISSUE TITLE
Userscript doesn't work on Safari.

### ISSUE THREAD

**Issue by LiamBM** [ParticleCore/Particle#121]
I know that Particle doesn't have a Safari extension, but even the userscript keeps forgetting the settings i've changed. For example, every time I check the "YouTube logo redirects to subscriptions" box and save, then reload the page, it appears unchecked again. Basically there's no way of saving the general settings without it reseting each time. Any solutions? Thanks

**Comment by ParticleCore** [comment]
This has already been asked before, see https://github.com/ParticleCore/Particle/issues/120

**Comment by q1k** [comment]
You could edit the script and change the defaults of the options.
