### ISSUE TITLE
Inline "advanced options" bar alongside video description buttons

### ISSUE THREAD

**Issue by markreg** [ParticleCore/Particle#122]
It would be great if there was an option or change to inline the advanced options bar on the right hand side of the video description buttons, this works well especially if the "short video description buttons" option is selected.

**Comment by ParticleCore** [comment]
Initially this was suppose to be the default position for the advanced controls, but after further investigation I noticed that it wouldn't work well for small window sizes if `short video description buttons` is not enabled and plenty other extensions/userscripts also used the same place for some of their features which would conflict with them or with the advanced controls, so I decided to place these on the top corner which so far seems like a non-conflicting place.
