### ISSUE TITLE
Have to click the play button twice when starting a video with autoplay set to off

### ISSUE THREAD

**Issue by hoboX10** [ParticleCore/Particle#126]
When it displays the video thumbnail with a play button, I'll click play. It'll then show the video player as if it is starting to load, but after a second it will go back to the thumbnail button again. Clicking play a second time causes it to then play. Minor issue, but gets annoying when watching many videos in a row.

**Comment by Piter432** [comment]
Confirmed on newest Chrome, YouTube+ and Tampermonkey on Windows XP SP3.

**Comment by ParticleCore** [comment]
Have been tracking this since https://github.com/ParticleCore/Particle/issues/90#issuecomment-143920166, I think I was able to find a better fix without the consequence that you have been observing but I need to test it a bit further before releasing it, it should be released today if everything goes correctly.

Just a quick question, are you using YT+ with video ads enabled?

**Comment by hoboX10** [comment]
Well I don't have any of the block ads boxes checked, but it's because I just have Adblock Plus blocking them all.

**Comment by ParticleCore** [comment]
That's not a problem, it just confirms my tests which is good, otherwise it would be a different problem making this harder to fix.

**Comment by ParticleCore** [comment]
Version 0.7.7 should have this issue fixed, let me know if it worked for you as well.

**Comment by hoboX10** [comment]
Working!

**Comment by Couacus** [comment]
Just wanted to let you know I have this exact same problem on version 1.9.5. Have had this problem for some time now. Windows 10 and Firefox 56. It would be nice to know if this is a problem on my end or if if the problem has come back.

**Comment by ParticleCore** [comment]
@Couacus Follow the troubleshooting instructions as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting
