### ISSUE TITLE
Activating Fullbrowser mode does not work correctly when the player is floating

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#127]

**Comment by q1k** [comment]
what?
i see no problem

**Comment by ParticleCore** [comment]
If you enable fullbrowser mode while the player is floating it fails to enter fullbrowser mode, this was brought to my attention by another user.

**Comment by q1k** [comment]
it's working fine here.
I can go fullscreen (F11) even if float player is on, over the comments.

Tested on Seamonkey, Firefox, and Chrome.
All fine

**Comment by ParticleCore** [comment]
Fullbrowser mode is not the same as going into fullscreen, it is related to the YT+ feature of filling the page with the player: https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

**Comment by q1k** [comment]
seems like a rather useless feature to me.
I'd rather go fullscreen, than that.

**Comment by ParticleCore** [comment]
It is more useful for people with more than 1 monitor that want the videos to stay in fullscreen when they play and go back to the normal page when it ends without having to manually enter or exit fullscreen.

**Comment by q1k** [comment]
A possible fix would be to temporarily disable/remove floater player and then go in full mode.

But again I'd rather use full-screen or fit-to-page-width theater mode.

**Comment by ParticleCore** [comment]
The fix for this one is already created, I am just working on another one that has been harder to get around.
