### ISSUE TITLE
Youtube Ads still being displayed when set "Disable advertisements in the video page"

### ISSUE THREAD

**Issue by RZeroX** [ParticleCore/Particle#134]
Browser Name: Nightly

Browser Version: 45.0a1

Operating System: Windows 10

Software Type: Add-on

Software Version: 0.7.7

Problem Description: When viewing any video which feature ads the ads will play on the video and to the right side of the video

Steps to reproduce: Play any video which feature any ads using the Nightly Browser, I've tested with Chrome and it worked fine and it blocked all the ads for the channels which I weren't subscribed to.

Additional details:

**Comment by ParticleCore** [comment]
This is being caused by that specific Firefox version, for some reason it is causing the add-on to run the crucial content after the page is finished loading. Currently trying to figure out if it their change is intentionaly or not.

On the other hand, the userscript is working correctly.

**Comment by ParticleCore** [comment]
Problem lies with the Port api, it is only working after the pages finish loading but the script needs to load before the pages are interacting. This causes the script to run after every crucial stage has passed resulting in it being unable to modify the player and the page before they are ready.

Couldn't find any other method to go around this, will be waiting for an answer from Mozilla but so far I am completely unable to fix this.

**Comment by ParticleCore** [comment]
I think I have managed to work around the problem, the new method seems to work in the latest Nightlies. Update YT+ to 0.7.8 and let me know if it works for your too.

**Comment by RZeroX** [comment]
It's working for me as-well.
