### ISSUE TITLE
Add new shortcuts

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#136]
1. Would be nice to be able to cycle quality options with a shortcut, for example, like pressing Q.
and a popup message to appear showing the current quality (360p, 480p, etc)

2. Toggle small and theater mode player, with a shortcut, by pressing T.

**Comment by ParticleCore** [comment]
I am no longer able to accept any more feature requests: https://github.com/ParticleCore/Particle/blob/master/README.md
