### ISSUE TITLE
Sidebar Mode Improvement

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#140]
First of all I know that currently you are not accepting any new features. But right of the bat let's make one thing clear, this is not a feature request, but rather an improvement.
<br>
I'm suggesting that the main video would pause when we go in sidebar and the sidebar should start from where the main video was paused.

**Comment by ParticleCore** [comment]
Will have to take a look at it and if it doesn't need too much I will probably add it, but it will have to wait.

**Comment by ParticleCore** [comment]
That's not a method that can be used with javascript, it will have to check the current video time at the time of the sidebar mode click and if the video is actually playing and not over, open the sidebar video with the current time in the URL with #t=XX at the end and pause the current video in the original page. Should be short, just have to test it when I have the time.

**Comment by q1k** [comment]
<span class="ytp-time-current">2:35</span>
shows the current time

<span class="ytp-time-duration">3:22</span>
shows the total time

**Comment by ParticleCore** [comment]
That's not a time that can be used in the url, it has to be in total of seconds. It can easily be grabbed from the player, there's no problems there or anywhere else as far as I could see. Everything I need for this enhancement seems easily feasible and straight forward.

**Comment by q1k** [comment]
ok, great.

**Comment by ParticleCore** [comment]
I've implemented the enhancement in 0.8.0, let me know if it works well for you too.

**Comment by q1k** [comment]
just updated 

the video pauses, but when the sidebar appears the video starts at 0:00 for a split second, and then it goes to the correct time.

is it possible to make it start at the specific time? , That is to add &t=117s at the end of the link?

**Comment by ParticleCore** [comment]
It is a limitation of the YouTube HTML5 player, it first needs to load the video information and only then it checks for the time tag in the url to seek to the respective time. Using `#` is intentional because it forces the video to play even if it has autoplay disabled while `&` does not. With `&` and autoplay disabled the video will not play automatically, but it will start playing at that point in time once you click play. Both `#` and `&` do the same thing, difference is one forces play while the other does not.

**Comment by q1k** [comment]
but adding both does the trick
youtube.com/watch?v=XXXXXXXX &t=117s#t=117s

**Comment by ParticleCore** [comment]
No, it won't make a difference, the video will behave exactly the same way as when using just the `#`.
