### ISSUE TITLE
Comments bug on YouTube or YouTube+ side?

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#141]
I see a bug with comments section on YouTube, but not sure what cause it. I think it's YouTube problem, but I will report it here to make sure, that with YouTube+ everything is fine.

**Comment by q1k** [comment]
What's the problem?

**Comment by ParticleCore** [comment]
So far I haven't found any problem with the comments. If you find it again let me know what it is.

**Comment by ParticleCore** [comment]
Seems like the issue you are seeeing is on the YouTube side: https://www.reddit.com/r/youtube/comments/3t8hj7/is_anyone_else_not_loading_comments/

**Comment by q1k** [comment]
This happened to my yesterday,
I open a video, wait until the whole page is finished loading, and then I click show comments. I took quite a long time to load the comments. 
But I don't think it's a youtube+ problem.

looks to me a youtube and google+ problem.
