### ISSUE TITLE
Grid subscriptions bugged due to recent release of the native YouTube grid layout

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#142]
YouTube recently released their own subscription grid layout with the adition of an option to switch to the previous list layout.

Until a new version is released users are advised to turn off the grid subscription option in YT+, switch the YouTube layout to list view and then enable the grid layout in YT+.

**Comment by Eisys** [comment]
Would it be possible to keep the old style of grid subs?
The spacing between Today and Yesterday and all that makes me feel like videos are missing..

If not, totally fine. I'll get used to it I guess.

**Comment by ParticleCore** [comment]
I will chek it out. YT+ grid layout does work like before if you change YouTube's to list so that's one less thing to worry.

**Comment by ParticleCore** [comment]
@Eisys I've updated YT+, the grid layout should switch automatically to list and then apply its own layout like before. Let me know if it works well for you too.

**Comment by Eisys** [comment]
Ok so if I'm in Youtube's native grid view and I turn YT+'s grid ON, then I get this:
http://prntscr.com/94c114

To fix it, I turn YT+'s grid off, change to Youtube's list view and then turn YT+'s grid on again.
This is all on Chrome, using YT+ addon version

On Firefox, using greasemonkey, this said feature works as intended it seems. But at the same time, it works too well. If I turn YT+'s subs grid OFF, and change to Youtube's native Grid view, it still changes it right back to List view every time.

**Comment by ParticleCore** [comment]
Make sure the Chrome extension you were running is already the version 0.8.0 that contains the fix and not the previous version. I will push a new version soon that addresses the grid layout being applied all the time.

**Comment by Eisys** [comment]
I did.
I just deleted the addon and reinstalled from Chrome store. It says it's 0.8.0.
Before this I also deleted browser data and ran CCleaner.

**Comment by ParticleCore** [comment]
Just tested the first step you mentioned, it changed correctly to the YT+ grid layout from YouTube's native. Both versions use the exact same code so if it switches correctly in the userscript then the same has to be true for the extension version.

**Comment by Eisys** [comment]
I don't know what to say. It even happens on my laptop(has never had YT+ isntalled) 
Another weird thing with the addon version, Youtube's Grid doesn't change over to List when YT+'s grid is OFF.

**Comment by ParticleCore** [comment]
Can you share the settings of the YT+ version that is causing these issues? I cannot replicate them on my end by following your steps in userscript, add-on and extension.

**Comment by ParticleCore** [comment]
I just released version 0.8.1, see if the problems stil occur. If they do paste your settings and try to be as precise as you can so that I can try to replicate the problem on my end tomorrow.

**Comment by Eisys** [comment]
Welp, 0.8.1 fixed both bugs. Thank you.

**Comment by ParticleCore** [comment]
Glad to hear that, now I can rest with no worries. Thanks for the help!
