### ISSUE TITLE
Default video settings do not apply after a fresh install

### ISSUE THREAD

**Issue by reconman** [ParticleCore/Particle#146]
I installed the extension yesterday and today I noticed that there are multiple parts of the features window. I looked into the video-part of the settings, activated some features and saved them.

Only then the defaultly checked features like "show video when reading comments" or autoplay were activated.

Browser: Chrome 46.0.2490.86
Youtube Plus was installed with the Chrome store.

**Comment by ParticleCore** [comment]
I just tested it following your steps and all default settings were loading without issues. Autoplay was off, as it was expected and "Player always visible" was on as well.

**Comment by reconman** [comment]
Sorry, I thought autoplay was enabled by default and I just didn't notice the scrolling video.

**Comment by ParticleCore** [comment]
Thanks for letting me know, glad to hear that it is working correctly after all.
