### ISSUE TITLE
black stripes

### ISSUE THREAD

**Issue by apan65** [ParticleCore/Particle#148]
May you delete this stripes(http://c2n.me/3qDpzMs.png) like in YePpHa plugin.

**Comment by q1k** [comment]
You mean the old YouTube gradient background?

**Comment by apan65** [comment]
Yes. Grey youtube's background around player

**Comment by q1k** [comment]
.watch-stage-mode #theater-background {
    background-image: -moz-linear-gradient(center top , #555555, #333333) !important;
    /*padding-bottom: 35px !important;*/
}

**Comment by apan65** [comment]
thanks. but how made background equal? http://c2n.me/3qEqmx7.png

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.


https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by q1k** [comment]
@apan65
Try adding 1 pixel padding bottom.

**Comment by apan65** [comment]
@q1k
I had made this.

.watch-stage-mode #theater-background {

background-image:  /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#ffffff+0,ffffff+1&amp;1+0,0+0 */
background: -moz-linear-gradient(top,  rgba(255,255,255,0) 0%, rgba(255,255,255,0) 1%); /* FF3.6-15 */
background: -webkit-linear-gradient(top,  rgba(255,255,255,0) 0%,rgba(255,255,255,0) 1%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom,  rgba(255,255,255,0) 0%,rgba(255,255,255,0) 1%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00ffffff', endColorstr='#00ffffff',GradientType=0 ); /* IE6-9 */ !important;

/*padding-bottom: 35px !important; */

}

**Comment by ParticleCore** [comment]
@q1k he wants the black background gone, not changed to the old grey color.

**Comment by q1k** [comment]
background: transparent !important;

LOL
