### ISSUE TITLE
When dash playback disabled, some videos won't load

### ISSUE THREAD

**Issue by ccrowles** [ParticleCore/Particle#149]
Whenever I disable dash playback, some videos refuse to load and give me an error.
Example: https://www.youtube.com/watch?v=AblCIvAvPkQ
![screenshot02589](https://cloud.githubusercontent.com/assets/12866474/11335760/7954a67e-91df-11e5-9f6c-3aa0cfadf0fb.jpg)

**Comment by ParticleCore** [comment]
I have just tested that video with DASH disabled and it plays correctly.

Please follow this troubleshooting guide to see if the problem is being caused by YT+ or not: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you still need help let me know.
