### ISSUE TITLE
Fullscreen Top Player

### ISSUE THREAD

**Issue by mpenguin** [ParticleCore/Particle#154]
I'm migrating from Youtube Center, which I thought was probably the best script for Youtube, but which is now a dead project.

One feature that I love about YTC is the Fullscreen Top Player (https://github.com/YePpHa/YouTubeCenter/wiki/Features#fullscreen-top-player). Any plans to incorporate this feature into Youtube+?

Thanks. I'm enjoying the script so far!

**Comment by q1k** [comment]
There is a similar feature in YouTube+
Fullbrowser mode.

**Comment by mpenguin** [comment]
True, it's similar, but not quite the same.

First, it's controlled by a button click, not scroll. The Fullscreen Top Player also had the option of exiting the mode when the video ended.

Second, it seems a little buggy in that the controlbar and timer don't extend across the video when I enter fullbrowser mode; rather, they are still the same size as the "default mode."

Still, it works better than Youtube Center's Fullscreen Top Player. I look forward to this script getting better and better!

Thanks!

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.


https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by ParticleCore** [comment]
Can you post an example showing the "buggy" part of the fullbrowser mode? Also the fullbrowser mode enters and exits when videos start playing and end, respectively: https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

**Comment by ParticleCore** [comment]
I've managed to replicate the issue you mentioned with the controls bar while switching to fullbrowser mode, I'll see what I can do to fix this.

**Comment by ParticleCore** [comment]
The mentioned problem should be fixed now, hit `Ctrl` + `F5` to force your browser to download the new stylesheet with the fix. After that the control bar should no longer have problems adjusting to the different player sizes.
