### ISSUE TITLE
Bulgarian language

### ISSUE THREAD

**Issue by AdmiralAnimE** [ParticleCore/Particle#157]
I have translated the extension in bulgarian, please add it :) I'm uploading a txt file with the strings.

[bulgarian.txt](https://github.com/ParticleCore/Particle/files/57831/bulgarian.txt)

**Comment by ParticleCore** [comment]
Thank you for the contribution! I've added the [Bulgarian](https://github.com/ParticleCore/Particle/blob/master/Locale/bg_BG.json) locale to the list, it should become available to users with Bulgarian language selected in the YouTube website in 24h or less.
