### ISSUE TITLE
Making the image when you hover during a time on the video bigger?

### ISSUE THREAD

**Issue by meve90** [ParticleCore/Particle#160]
![utub](https://cloud.githubusercontent.com/assets/14894316/11745712/7e47f052-a01a-11e5-980a-d4d689ba1170.png)

Couln't find the correct words to explaing it.. is it possiible to make that shown by the red arrow bigger?

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.


https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by q1k** [comment]
Here's a simple css solution

<code>
.ytp-tooltip-bg {
transform: scale(1.6) !important;
margin-bottom: 10px !important;
}

.ytp-tooltip-text-wrapper {
bottom: 0px !important;
}
</code>

play around with the scale value to make it bigger or smaller.
you might want to re-adjust the margins too.

**Comment by Eisys** [comment]
@q1k Thank you so much for that, works great with Stylish.

**Comment by meve90** [comment]
@q1k ty!

**Comment by KamranMackey** [comment]
@ParticleCore What framework? Only framework you use is JavaScript. And why can't you find time?

**Comment by ParticleCore** [comment]
There's the YouTube API/framework which is very limited. My current schedule is full, I don't have the free time I had before.
