### ISSUE TITLE
Cannot install as userscript with Scriptish in Firefox

### ISSUE THREAD

**Issue by uszasty** [ParticleCore/Particle#161]
No error message is shown unfortunately, it just ignores the .js file completly.

**Comment by ParticleCore** [comment]
Scriptish has been [abandoned for more than a year](https://github.com/scriptish/scriptish/issues/276#issuecomment-145379995) and it is not a userscript manager supported by YT+

>Current support is being provided for:  
[![Firefox 38+](https://img.shields.io/badge/Firefox-38%2B-orange.svg)](https://www.mozilla.org/firefox)  [![Greasemonkey 3.2+](https://img.shields.io/badge/Greasemonkey-3.2%2B-yellow.svg)](http://www.greasespot.net/)  
[![Chrome  42+](https://img.shields.io/badge/Chrome-42%2B-blue.svg)](http://www.google.com/chrome/)  [![Tampermonkey 3.10+](https://img.shields.io/badge/Tampermonkey-3.10%2B-green.svg)](https://tampermonkey.net/) 

https://github.com/ParticleCore/Particle/blob/master/README.md
