### ISSUE TITLE
Player controls not properly aligned in full screen

### ISSUE THREAD

**Issue by Matthewus** [ParticleCore/Particle#168]
Browser Name: Firefox 43 & Chrome 47

Operating System: Windows 7 32 bit

Software Type: Userscript

Userscript Manager: Greasemonkey & Tampermonkey

Userscript Version: 0.9.0

Problem Description: There is no padding next to the full screen switch button in full screen, there should be padding, just like on the left side.

Steps to reproduce: -

Additional details: It looks as it should, if i disable the userscript.

**Comment by ParticleCore** [comment]
Thanks for the heads up, it's a left over from a previous quick patch and I've also found another bug during the process which has been fixed in version 0.9.1

After updating to 0.9.1, in YouTube press Ctrl + F5 and let me know if the problem is fixed for you as well.

**Comment by Matthewus** [comment]
Fixed for me too, thanks for the quick update.
