### ISSUE TITLE
Progress bar misalignment and pause issue

### ISSUE THREAD

**Issue by HerrKaha** [ParticleCore/Particle#169]
Browser Name: Firefox
Browser Version: 43.0.1
Operating System: Win10 64 bit
Software Type: Userscript with Greasemonkey
Software Version: 0.9.1

I use the Fullbrowser mode with my videos and I middle click on a video to open it in a new window (the fullbrowser is preselected) Sometimes the progress bar is not aligned correctly to the video size.
Like shown in this picture.
![screenshot 2015-12-19 14 04 06](https://cloud.githubusercontent.com/assets/16361388/11912864/55c2443a-a659-11e5-8d43-09e39f664d2f.png)

Sometimes when I pause the video and switch to another tab and come back and play the video, the buffering image stays on the screen and I can't pause the video. If i click on the progress bar and change the time of the video I can pause again. This is rare and hard to duplicate.

**Comment by ParticleCore** [comment]
I've updated the extension with a fix for this issue in 0.9.2, let me know if it works for you as well.

**Comment by HerrKaha** [comment]
It seems to work! Thanks for the quick response!

**Comment by ParticleCore** [comment]
Glad to hear that and I am happy to see that other users are making use of this feature.
