### ISSUE TITLE
Settings stay at default

### ISSUE THREAD

**Issue by swansnake** [ParticleCore/Particle#170]
Hi, so in the last day or two my YT+ updated a couple of times and reset itself to default and now won't save my settings. The blue notice comes up with each new load of a YouTube page, saying: "Thank you for installing YT+ You can customize your settings by clicking the button above", and clicking the X doesn't make it go away. I tried removing the script and exporting and importing the settings, and nothing.

Browser Name: Pale Moon
Browser Version: 25.8.1
Operating System: Windows 7 32 bit
Software Type: Userscript with Greasemonkey
Software Version: 0.9.2

**Comment by ParticleCore** [comment]
I am sorry but I am not providing support for Palemoon: https://github.com/ParticleCore/Particle/wiki

**Comment by guilhermearaujo** [comment]
The same happens on Safari. Are there plans to support Safari?

**Comment by ParticleCore** [comment]
@guilhermearaujo See https://github.com/ParticleCore/Particle/issues/86#issuecomment-142438112

**Comment by swansnake** [comment]
PM is based on Firefox and TY+ has worked fine with Pale Moon up until yesterday. Any idea why?

**Comment by ParticleCore** [comment]
A browser based on Firefox is not the same as Firefox, otherwise the extension would still be working. I do not know why it stopped working.

You can see for yourself the exact changes that have been made to each version here if it helps: https://github.com/ParticleCore/Particle/commits/master

**Comment by ParticleCore** [comment]
I have been informed that Greasemonkey itself is no longer supporting Pale Moon: https://github.com/greasemonkey/greasemonkey/pull/2183#issuecomment-132635977

From my commits I could not find anything that could have been changed in the mentioned period which could have caused the settings to not save, so the only conclusion is that the problem lies with Greasemonkey no longer being compatible with Pale Moon.

**Comment by swansnake** [comment]
Would you be able to tweak the XPI file so that Pale Moon can install it? As I understand it, no modification is needed, just a GUID string:

http://forum.palemoon.org/viewtopic.php?f=24&t=8740
" the extension author has to do is add Pale Moon's GUID {8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4} to the overlays in the chrome manifest to make overlays apply to Pale Moon as well"

**Comment by ParticleCore** [comment]
Sorry but no, that would mean supporting Pale Moon and after that other users would start requesting more support for Pale Moon for future problems that might arise, and it is a commitment I do not wish to take.

The source code for the add-on is available here: https://github.com/ParticleCore/Particle/tree/master/src/Add-on

If you want you can do the modifications on your own, but I will not be providing support for it.

**Comment by swansnake** [comment]
Okay, I think I was able to pretty much get everything back to my preferred settings by manually editing the .js file.

**Comment by janekptacijarabaci** [comment]
@swansnake 

Pale Moon:

The error in the Browser Console:
![channel_responseurl](https://cloud.githubusercontent.com/assets/2373486/11919241/45b792ee-a74d-11e5-9bd6-c714566b724b.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=998076

**Comment by swansnake** [comment]
That's way beyond my understanding. I can do simply copy/paste and change "true" to "false" and such. So I was able to edit the user.js file to turn on most of the non-default features. There must be a dataset I'm missing because it does not remember the theater layout. Otherwise everything seems to work okay...

**Comment by ParticleCore** [comment]
Changing the userscript disables the auto-update feature in Greasemonkey, you will no longer receive future updates automatically.

**Comment by swansnake** [comment]
That's fine, as long as nothing catastrophically changes with YouTube. It's too bad the script doesn't work as is on Pale Moon, it's my preferred browser by far.
