### ISSUE TITLE
Option to have both non-HFR video and HFR video in quality options on YouTube's player.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#177]
Currently if we want to watch a HFR video, we need to uncheck the “Disable HFR (60fps)” option, but if we want to watch the HFR video as non-HFR, we need to select that option. Unfortunately, both changes requires refresh to apply the change :/ I think there should be in quality options on YouTube's player an option something like this as it's shown in this screenshot I made:
![30-12-2015 r 00 19 21 - ytp non-hfr i hfr qalty](https://cloud.githubusercontent.com/assets/5713816/12044266/e0b09b40-ae8e-11e5-9538-96a3c343499a.png)

**Comment by ParticleCore** [comment]
Sorry but as far as I could see there is no way of doing this without rewriting the entire player from scratch. It automatically lists the best stream for each quality according to the browser's capabilities. I wish there was a way to do this, but have not found one yet. I will still keep looking for a way from time to time.
