### ISSUE TITLE
When “Player shortcuts always active” is on, unable to use system/browser keyboard shortcuts.

### ISSUE THREAD

**Issue by dotdapple** [ParticleCore/Particle#180]
For example, I’m unable to close the browser tab using ⌘W, or access my bookmarks sidebar with ⌘B. Would love if this can be fixed.

**Comment by ParticleCore** [comment]
A fix for this issue will be released today.

**Comment by ParticleCore** [comment]
The new version fixes this issue, let me know if it works for you too.

**Comment by dotdapple** [comment]
Works now! Thanks.
