### ISSUE TITLE
1080p60 flicker

### ISSUE THREAD

**Issue by mediocrenoob** [ParticleCore/Particle#181]
Browser: Firefox 43.0.3 x64

Operating System: Windows 8.1 

Software Type: Extention but also present in the script.

Software Version: 0.9.9

Userscript Manager: Greasemoneky 

Userscript Version: 0.9.9 

Problem Description: Setting the Default Video Quality to 1080p60 (don't know about anything higher than that) the YouTube video will flicker. Setting it to 720p60 and the video is fine.

Steps to reproduce: Change Default Video Quality to 1080p and watch a video. The time when it flickers is random and number of times it flickers is random.

Additional details: I've tried all the usual methods of disabling all my ententions and re-enabling them one by one and using a separate portable version of Firefox as a test environment, thinking it was an about:config setting. Even tried using the extention version over the script.

**Comment by ParticleCore** [comment]
I cannot reproduce this problem, the videos play in 1080p and 1080p60 without issues with FF 43.0.3 x64 on W7 x64.

Have you tried to see if the problem still persisted with YT+ disabled as it was suggested in the troubleshooting guide? Disable YT+, restart the browser, play a video in 1080p and see if the flickering returns.

This sounds more like a problem with your codecs or a hardware limitation.

**Comment by mediocrenoob** [comment]
I did try without any addons installed when I did a fresh install of the portable Firefox and it still flickered.

Could you elaborate on the codecs part? As far as a hardware limitation, I don't think it could be that either because this problem wasn't a problem with Firefox 42.

**Comment by ParticleCore** [comment]
If the problem persisted with YT+ disabled then this is not related to the extension. The reasons behind this can be plenty, using a portable Firefox version could be one of the reasons, W8 in certain cases is known for having some [codecs missing](https://www.reddit.com/r/youtube/comments/35mo04/only_360p_on_my_laptop_normal_on_my_pc_mozilla/cr677wp?context=3) causing YouTube issues (although it doesn't sound like your case), and so on.

**Comment by mediocrenoob** [comment]
My browser, normal installed Firefox and the portable one, both default to HTML5 since that's what YouTube defaults to. I downloaded those update files from that reddit post and both said that they are not applicable to my computer, so either they are already installed, superseded by something else or not needed.
