### ISSUE TITLE
Automatically exiting fullbrowser mode

### ISSUE THREAD

**Issue by AccountOneOff** [ParticleCore/Particle#184]
This doesn't always happen but when the script exits me out of fullbrowser mode when a video ends it breaks a few things.

- [Scroll bar is hidden and scrolling can only be achieved by using the arrow keys](http://i.imgur.com/ZVe8baZ.png)
- Player controls and related video end card don't fit the video player
- [Notification menu pops out behind layout](http://i.imgur.com/LGscBJt.png)

**Comment by ParticleCore** [comment]
I am able to replicate this issue, will try to find a fix for it.

**Comment by ParticleCore** [comment]
This issue should be fixed in 1.0.2, let me know if it works for you too.

**Comment by AccountOneOff** [comment]
Still happening after update.

https://streamable.com/elf7

**Comment by ParticleCore** [comment]
Disable everything you have installed (userscripts, add-ons) except YT+ and see if the problem persists.

**Comment by ParticleCore** [comment]
@AccountOneOff Do you happen to have any update on this? I have been trying to replicate the problem after the latest update and have not been successful so far

**Comment by AccountOneOff** [comment]
Sorry, yes turning off all add-ons/scripts fixed the problem but I don't know what is conflicting with it.

**Comment by ParticleCore** [comment]
Then now the next step is to turn on one by one and see when the issue reappears again, start with the ones that are targeting YouTube directly since those are most likely to be causing the problem and then move to the less likely ones.
