### ISSUE TITLE
Frame by Frame not working if youtube player is selected for e.g. in fullscreen mode

### ISSUE THREAD

**Issue by masterlup** [ParticleCore/Particle#188]
For some time the frame by frame option isnt working like it did.
When i select the youtube player (for eg to make it fullscreen or when i skip or when pressing play/pause) the option shift <> doesnt result in a frame by frame play. It only does the normal 5 second skip that you get by normally pressing the l+r arrows.
When i deselect the player (for eg by pressing on the title or on "show comments") the option shift <> is working and i have frame by frame playback.
So now i cant use frame by frame in fullscreen mode. How can i fix this?

I use the newest Chrome 47.0.2526.106 m
On Youtube i have the HTML5 player.
I also disabled and reinstalled the plugin.

**Comment by Eisys** [comment]
Can confirm. Same thing happening to me. Latest beta Chrome and 1.0.2 YT+

**Comment by masterlup** [comment]
It seem as if when the player is selected the extension cant be accessed and vise versa

**Comment by masterlup** [comment]
I just found out a little trick. You can go on fullscreen and click on share and then close (x). After this you can use frame by frame in fullscreen mode. But thats no real solution.

**Comment by ParticleCore** [comment]
I have to revert a part of the code for this feature, I forgot to keep it when making the changes. Will try to post the update with the fix today.

**Comment by masterlup** [comment]
thank you. i love this extension so far!!!

**Comment by ParticleCore** [comment]
This should be fixed in version 1.0.3, let me know if it works for you as well.

And sorry for the trouble.

**Comment by masterlup** [comment]
Its working fine so far. I let you know if i find anything else. Thank you!!!

**Comment by masterlup** [comment]
Frame by Frame does not work for me. Not even with any tricks or restrictions.

**Comment by ParticleCore** [comment]
@masterlup A fix has been implemented but due to Firefox server problems I am unable to upload the new version at the moment, will publish it when it becomes possible. Thanks for letting me know.

**Comment by ParticleCore** [comment]
@masterlup YT+ v1.2.2 has been published with the fix for this problem, let me know if it works for you as well.

**Comment by Wynadorn** [comment]
I'm sorry to say that this feature isn't working under 1.3 with Firefox 47
