### ISSUE TITLE
Enable info bar with watch later button, not working

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#190]
It does nothing, please fix

**Comment by ParticleCore** [comment]
It is working on my end

![ss](https://cloud.githubusercontent.com/assets/9222661/12142219/d9f721b6-b465-11e5-8a63-a4358a7d33b0.png)

More information could be helpful, also try the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by mauriciocolli** [comment]
For me, it is working
https://i.gyazo.com/a0d86908603becd313e58be36deb4c91.gif

**Comment by ParticleCore** [comment]
I will close this for now seeing that so far it is not possible for me to replicate the problem.

**Comment by MaximilianKohler** [comment]
Browser Name: Firefox

Browser Version: 49.0.2

Operating System: 8.1 x64

Software Type: firefox addon

Software Version: 1.6.7


So this happened during my first setup of this addon.

Pretty sure it did show up temporarily, then I changed some more settings (including various "fit to page in theater mode" settings) and it went away.

I tried restoring other settings but it never would come back. I clicked the YT+ "reset" button and restarted my browser, then pasted in my settings and clicked "save and load", but that didn't work. 

I reset the settings again, but this time also disabled then removed the whole addon. I restarted the browser and only checked this option. It showed while the ad of the first video I loaded played, then it went away permanently.

I made a completely new firefox profile and only installed YT+, only enabled the one option, and the exact same thing happened.

{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": true,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": false,
  "GEN_PPOT_ON": true,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd720",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": true,
  "VID_PPOT_SZ": false,
  "VID_PLR_HTML5": true,
  "BLK_ON": true,
  "floaterX": 2000,
  "floaterY": 2000,
  "firstTime": false,
  "volLev": 50,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "migration_instructions": true,
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": false,
  "GEN_YT_LOGO_LINK": false,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": false,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": false,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": "90%",
  "VID_PLR_FIT": true,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": true,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": true,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": false,
  "VID_PLR_CC": false,
  "VID_PLR_ALVIS_WDTH": false,
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": true,
  "lightsOut": false
}

**Comment by ParticleCore** [comment]
@MaximilianKohler Please open in a new issue, don't reuse this one.
