### ISSUE TITLE
[Suggestion] Night mode

### ISSUE THREAD

**Issue by Martan404** [ParticleCore/Particle#193]
I don't know where to post this but if there's another section besides issues then I apologize. 
I really like this script a lot. So much that I decided to stop using Magic Actions for Youtube which I've been using for some years now. However there's a feature that I really would like to see in YouTube+ and it's a night mode that makes YouTube all dark. It really makes YouTube easier on the eyes.

For reference, this is how the night mode looks that I used previously.
https://i.imgur.com/ObE4py1.png
The little switch in the top left toggles the night mode.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.


https://github.com/ParticleCore/Particle/blob/master/README.md

If you wish, there is already a dark themed YouTube userstyle that is compatible with YT+ https://userstyles.org/styles/101409/youtube-dark-grey

**Comment by q1k** [comment]
You could try this one too
https://userstyles.org/styles/62289/black-youtube-by-panos

**Comment by Martan404** [comment]
Missed that part where you said you couldn't accept any more features. Sorry about that!
I managed to find a userscript that both looks and works exactly how I wanted.
https://greasyfork.org/sv/scripts/4707-dark-tube
