### ISSUE TITLE
How to remove buttons under the video player

### ISSUE THREAD

**Issue by iamPanka** [ParticleCore/Particle#198]
Hi, very nice script!
Anyway I have a question: is there a way to remove all or a part of the buttons under the video player (I mean autoplay, repeat, thumbnail, screenshot and other buttons near the title)? Thanks a lot.

**Comment by Eisys** [comment]
I think you should be able to click the 3 lines that are above the buttons to hide them!

**Comment by iamPanka** [comment]
Ooops I'm sorry, I didn't notice it because I had a lyrics addon button in that corner that covered the option! Thanks a lot!
