### ISSUE TITLE
Replay button not working

### ISSUE THREAD

**Issue by grenzor** [ParticleCore/Particle#199]
Clicking the replay button in description with YT+ options doesn't do anything. Latest FF version.

**Comment by ParticleCore** [comment]
I cannot replicate this problem, the videos replay correctly once they reach the end.

Disable all add-ons and userscripts you might have installed, except YT+, restart the browser and try again.

Additionally more information could be helpful, such as the Firefox version, Operating system, YT+ type (add-on or userscript).

**Comment by ParticleCore** [comment]
I will close this for now, if you still need further help please follow the instructions provided above.

**Comment by grenzor** [comment]
This might be similar to #207 where the button itself is not working (for me replay button works on Win but not on Mint). Also found the other buttons like Take screenshot not doing anything too.

**Comment by ParticleCore** [comment]
That is because Firefox on Mint is using the flash player instead of the HTML5, plenty of features like the ones you mentioned are not compatible with flash.

**Comment by q1k** [comment]
Go here https://www.youtube.com/html5
and click use html5 player.

**Comment by grenzor** [comment]
@ParticleCore Ah yes, that's probably it.
