### ISSUE TITLE
Turkish language support (i've already translated)

### ISSUE THREAD

**Issue by ofmenlik** [ParticleCore/Particle#200]
I translated YT+ from English to Turkish, but I really don't understand how to upload it to system. So here is a txt file that you can download and add to the script: 
https://yadi.sk/i/dPImW40ZnXEFh

If you are going to give me credit please write my full name: Ömer Faruk Menlik

Thanks.

**Comment by ParticleCore** [comment]
Thanks for your contribution, but if you want to try the system there's no problems. All you have to do is go to the location of the translations here:

 https://github.com/ParticleCore/Particle/tree/master/Locale

Press the "New file" button

Follow the template instructions: https://github.com/ParticleCore/Particle/wiki/Translation-template

And then submit.

If you don't want to try it that's also fine, I will add it by hand.

**Comment by ParticleCore** [comment]
I have added your [Turkish translation](https://github.com/ParticleCore/Particle/blob/master/Locale/tr_TR.json) and it will be automatically loaded as soon as possible to YouTube+ users with the YouTube language set to Turkish. Thank you for your contribution!
