### ISSUE TITLE
Hovercard popping up without reason.

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#206]
Browser Name: Chrome
Browser Version: 49.0.2623.28 beta-m (64-bit)
Operating System: Win 10
Software Type: Userscript
Software Version: 1.0.3
Userscript Manager: Tampermonkey
Userscript Version: 3.12.58
Problem Description: The hovercard pops up after changing tabs in certain cases.
Steps to reproduce: Go on a video, middle click to open the channel's page in a new tab, go to that tab, then come back.
Although this happens in subscriptions as well; open a channel in new tab, go to it and then come back, the hovercard pops up in near the name of the channel I went to.
Additional details: I made a gif of it happening: https://gfycat.com/ForthrightCrazyCanine | My settings: http://pastebin.com/QH0XSpPY

**Comment by ParticleCore** [comment]
This is a YouTube bug, I was able to replicate it without YT+ enabled.

On Chrome 47.0.2526.106 m while replicating your exact steps (even the same video and channel):

My YT+ settings > Hovercard did not show up (I had the setting to [disable hovercards](https://github.com/ParticleCore/Particle/wiki/Features#hovercards_off) activated)

Your YT+ settings > Hovercard did show up (you do not have the above setting activated)

Without YT+ running > Hovercard still shows up

This should be reported to YouTube instead, let them know via the "Send feedback" link found at the bottom of YouTube pages. Include your gifs as well, they are extremely helpful.

Other than that, if you don't want the hovercard showing up just activate the YT+ setting, at least until the issue gets fixed.

**Comment by Eisys** [comment]
Oh sorry about that then. When I tested it, it didn't happen with YT+ disabled.
I will send feedback.

I do use the hovercard from time to time but will disable to see if I can live without it, because this bug can be really annoying.
