### ISSUE TITLE
Playlist autoplay feature not functional

### ISSUE THREAD

**Issue by tobeannouncd** [ParticleCore/Particle#207]
Browser Name: Google Chrome
Browser Version: 48.0.2564.97 m (64-bit)
Operating System: Windows 10 x64 Build 10586.71
Software Type: Userscript
Software Version: 1.0.6
Userscript Manager: Tampermonkey
Userscript Version: 3.12.58

Problem Description: Whenever I am in a playlist, the button for toggling playlist autoplay is visible. Whether the button is indicating that playlist autoplay is enabled or not, the playlist automatically will advance to the next video when the current video is finished. Clicking the button does not have any effect (autoplay does not toggle and the button doesn't change from 'lit' to 'unlit').

Steps to reproduce: Visit any playlist (Watch Later, Favorites, etc). Here's the most recent playlist I tried this with: https://www.youtube.com/playlist?list=PL-292yfpAFGYdTEWvXECZX8UwPgO7X3Zz

Additional details: Occasionally, playlist autoplay will be turned off. However, I have not been able to reliably reproduce this behavior.

**Comment by ParticleCore** [comment]
The feature is working correctly, the buttons are not. They are not offering the correct visual feedback (staying lit when active, dim when not). Will try to correct this as soon as possible.

**Comment by ParticleCore** [comment]
A fix for this issue has been included in the version 1.0.7, let me know if it works for you too.

**Comment by tobeannouncd** [comment]
It's working perfectly so far. Thanks!
