### ISSUE TITLE
float player

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#209]
after updating to 1.1.1 the option to disable float player is missing.

**Comment by ParticleCore** [comment]
Make sure you are looking for the right option, it is not missing:

![ss](https://cloud.githubusercontent.com/assets/9222661/12979333/e62d6af4-d0c5-11e5-8695-7fb9c0c42e61.png)

**Comment by q1k** [comment]
Oh the problem was on my end, 
something was wrong with the extensions on chrome on my laptop.
I started the browser only recently, and it was some older version. Now it's updated and there is no problem.

But I must say your script (particularly the floating player) conflicts with another script that I use, [Youtube new ui fix](https://greasyfork.org/en/scripts/11485-)

**Comment by ParticleCore** [comment]
It is unfortunate but YT+ is not built with other extensions in mind. If they don't work well together then they shouldn't be running together, unless the user is willing to use it as it is or the author decides to extend compatibility.
