### ISSUE TITLE
YouTube updated something?

### ISSUE THREAD

**Issue by ThisIsTooHardStepToTake** [ParticleCore/Particle#211]
Not sure if YouTube updated something but now when you click Fullscreen button it will maximize the window to the edges, it won't go fullscreen. You need to click F11 to go to fullscreen.

Is there any way to force it to fullscreen with YT+?

Chrome Canary 50.0.2646.0 / YT+ 1.1.1

Also tested with YT+ disabled, same issue.

**Comment by ThisIsTooHardStepToTake** [comment]
Chrome issue, updating to the latest version fixed the problem.

**Comment by ParticleCore** [comment]
Glad to hear that you got it solved!

**Comment by ThisIsTooHardStepToTake** [comment]
Looks like this is not completely solved yet, playlists won't go to fullscreen.

**Comment by ThisIsTooHardStepToTake** [comment]
Looks like a YT+ bug, after I disabled YT+ playlist video went to fullscreen mode correctly.

**Comment by ParticleCore** [comment]
Please follow the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by ParticleCore** [comment]
I will close this for now, I am not able to replicate your issue. If you still need help please follow the previous instructions.
