### ISSUE TITLE
Subscribed channels not showing in subscription feed.

### ISSUE THREAD

**Issue by windowlicker79** [ParticleCore/Particle#212]
Browser Name: Firefox

Browser Version: 44.0.2

Operating System: Windows 10

Software Type: add-on

Software Version: 1.1.2
 
Problem Description: I've recently noticed that some channels are not showing in my subscription feed.
I know one channel for definite (https://www.youtube.com/user/LEGOJANG) is doing it as he uploads daily videos and they never show up.
If I turn Youtube Plus off then the channels videos a displayed, but they disappear again when I turn it back on.
The thumbnails also flash up briefly if I switch between grid and list view, but they then disappear in a fraction of a second.

Steps to reproduce: Subscribe to the channel mentioned with Youtube Plus switched on.

**Comment by mauriciocolli** [comment]
Do you have tried see if you black listed it channel?
![black](https://cloud.githubusercontent.com/assets/13389907/13031505/189bde4c-d2b7-11e5-8734-e29255e67f18.PNG)

For me it is working well:
![not_able](https://cloud.githubusercontent.com/assets/13389907/13031509/3a678f4e-d2b7-11e5-9b29-76c16ba9ca6e.PNG)

**Comment by ParticleCore** [comment]
@windowlicker79 You have probably added that channel to the blacklist, like mauriciocolli suggested.

Go to YT+ settings > Blacklist and see if the channel is in the blacklist.

**Comment by windowlicker79** [comment]
That seems to have fixed it. No idea how that happened. There were a few other channels in there that I didn't even recognise. Deleted them all now. Thanks for the help.

**Comment by mauriciocolli** [comment]
Just to know:
![here](https://cloud.githubusercontent.com/assets/13389907/13034093/f856f142-d312-11e5-8cba-6d6d141e5f83.PNG)

**Comment by ParticleCore** [comment]
Glad to hear that it got fixed.
