### ISSUE TITLE
Feature request: Set default playback speed

### ISSUE THREAD

**Issue by tarbucktransom** [ParticleCore/Particle#213]
I exclusively watch youtube in 1.5x speed, and it would be great if there were a setting for default playback speed. As it stands, it resets every time there's a new video, including on playlists, and it's eternally annoying.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.


https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by Eisys** [comment]
If you are on chrome then use the [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?utm_source=chrome-app-launcher-info-dialog) addon.
