### ISSUE TITLE
fullbrowser

### ISSUE THREAD

**Issue by mighelch** [ParticleCore/Particle#215]
could you implement it like in this script
https://greasyfork.org/en/scripts/16323-youtube-player-controls
fullbrowser of YT+ is sorta full screen mode. Personally I don't find it that much useful.

**Comment by mauriciocolli** [comment]
Use the theater mode:
![theater mode](https://cloud.githubusercontent.com/assets/13389907/13051361/fac5180a-d3df-11e5-9fa8-54fd3b7609a4.PNG)

Just configure the max-width and check the "Fit to page in Theater Mode":
![width](https://cloud.githubusercontent.com/assets/13389907/13051420/4b87a9d8-d3e0-11e5-98bd-d76f84a97f61.PNG)

**Comment by ParticleCore** [comment]
Like mauriciocolli suggested, enable the feature and set the Fit to page max width to the width of your browser.
