### ISSUE TITLE
Float player don't remember position after exiting fullscreen

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#216]
This happens **on Firefox**, on Chrome is working correctly.
Tested on both Firefox & Chrome.

Steps to reproduce: on float player enter in full screen, and exits again. I noticed that **ONLY** happen when you use double-click to exit, if you use the button "Exit FullScreen" or use the shortcut F , it remembers the position.

Using the double-click to exit:
https://i.gyazo.com/3769657d668329ade572e5ad8e4697c2.mp4

Using the "Exit FullScreen" button:
https://i.gyazo.com/51712f958e769099e99784450b4045ad.mp4

_And thanks for the update_ :+1:

**Comment by ParticleCore** [comment]
Thanks for the notice, will work on a fix for this!

**Comment by ParticleCore** [comment]
This should be fixed with the version 1.1.4, let me know if it works for you too.

Also is the window/player dragging a good addition, does it feel more natural this way?

**Comment by mauriciocolli** [comment]
Yeah, it is working now, and I think that dragging the window is a good addition! Good work!

**Comment by q1k** [comment]
A couple more problems with this.
- When trying to drag the player it stops moving, so i'm forced to click to drag again.
- Exiting fullscreen moves the page to the top, and it is no longer possible to enter fullscreen with double click on player

**Comment by ParticleCore** [comment]
@q1k Please open a new issue and include more information.

**Comment by ParticleCore** [comment]
@q1k I think I was able to replicate both problems you mentioned and a fix for them has been released in 1.1.5, hope it works well for you too.
