### ISSUE TITLE
Disabling "Memorize audio volume" has no effect

### ISSUE THREAD

**Issue by mleyen** [ParticleCore/Particle#223]
Regardless of whether this is enabled or not, the volume and mute status will be set to the last value I used.

So if I mute a video and go to another page, the next video will be on mute by default.

Can this be fixed so disabling the option will force the volume to YouTube defaults, or even to max volume?

**Comment by ParticleCore** [comment]
YouTube also memorizes the mute and volume as well only if the user has cookies enabled, and until they are expired. This feature only ensures that it remembers the volume level even with cookies disabled or when they are expired.
