### ISSUE TITLE
Playback volume is louder than default with YouTube Plus

### ISSUE THREAD

**Issue by Fough1995** [ParticleCore/Particle#227]
Chrome 48.0.2564.116 (64-bit) & Firefox 44.0.2 (64-bit)
Windows 7 x64 / Extension (Chrome) & Add-on (Firefox) Version 1.1.6

YouTube seems to reduces the volume of loud videos by default (audio normalization), and enable YouTube Plus will remove this post-processing.
example: https://www.youtube.com/watch?v=tbYHzoBL8ec
Playback volume is louder when YouTube Plus is enabled.
I like to play videos in their original volume without normalization, but maybe others don't.
Could you add an option to enable/disable this post-processing?

**Comment by mauriciocolli** [comment]
I didn't notice till I record with and without the Youtube+:
![graph](https://cloud.githubusercontent.com/assets/13389907/13172752/e11c6878-d6e0-11e5-8cbf-a320bdd773d1.PNG)
Left Youtube+ **ON**  | Right **OFF**

**Comment by ParticleCore** [comment]
YouTube introduces audio "normalization" artificially that doesn't work well, which was causing videos with low volume to be even lower and other users complaining thinking that YT+ was the cause of this.
YT+ resets that setting to whatever default audio level the videos have to prevent artificial modifications that are not made by the user or creator. It doesn't make the videos louder, it just makes them at the default/original level the video was recorded at, which is what you want just like many other users:

>I like to play videos in their original volume without normalization

**Comment by ParticleCore** [comment]
For more information regarding this subject you can read it here when it was launched:
http://productionadvice.co.uk/youtube-loudness/

The problem with it was that, as I mentioned, it doesn't work well:

https://www.reddit.com/r/youtube/comments/3nu65z/my_youtube_changes_volume_on_its_own/
