### ISSUE TITLE
YouTubePlus is blocking CC subtitles

### ISSUE THREAD

**Issue by audjack99aus8** [ParticleCore/Particle#23]
the user script is stopping CC subtitles from working. the icon on the bottom right goes away.
Is there a option to enable them?

Thanks

**Comment by Yonezpt** [comment]
There is an option that disables subtitles under Video > Player Settings > Disable subtitles.

Deselecting it should allow for subtitles to appear again on videos that have it enabled.

**Comment by ParticleCore** [comment]
There is an option that disables subtitles under Video > Player Settings > Disable subtitles.

Deselecting it should allow for subtitles to appear again on videos that have it enabled.
