### ISSUE TITLE
Can't change Fit to Page Max Width option.

### ISSUE THREAD

**Issue by BoneofMalkav** [ParticleCore/Particle#230]
I noticed recently that apparently I can't change the Fit to Page Max Width option like I used to. Is it supposed to be like that?

**Comment by ParticleCore** [comment]
For it to work you need to have the [Fit to page in theater mode](https://github.com/ParticleCore/Particle/wiki/Features#fit_to_page) enabled and then in the max-width you insert your custom size in either px or %

So if you want it to be 1280px you have to add the **px** at the end too, if you want it to be 50% you have to add the **%** at the end too.

If all you add is just a number without its type then it will not work correctly.

**Comment by ParticleCore** [comment]
I will close this for now, if you still need more help just let me know.
