### ISSUE TITLE
MutationObserver slight fix

### ISSUE THREAD

**Issue by reyder** [ParticleCore/Particle#236]
According to [https://developer.mozilla.org/pl/docs/Web/API/MutationObserver](url)

`NOTE: At the very least, childList, attributes, or characterData must be set to true. Otherwise, "An invalid or illegal string was specified" error is thrown `

I replaced code with 

`{attributes: true, attributeFilter: ["data-" + key]}`

and error is gone. I'm using Safari on Mac which is not supported by you but it's working with no issues after this.

**Comment by ParticleCore** [comment]
Thanks for the heads up, it is always worth writing the code correctly. Will try to push the fix as soon as I can if no problems arise.

**Comment by ParticleCore** [comment]
This has been implemented in version 1.1.9, let me know if it works well for you too.

**Comment by reyder** [comment]
Yep, it works. Thanks
