### ISSUE TITLE
Option to disable share panel after liking any video on YouTube, maybe?

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#237]
I mean about almost the same option as disabling the share panel after video ended, but in this one, after liking any video on YouTube, because I don't like that share panel shows me after I like any video :/

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Particle/issues/43

**Comment by Piter432** [comment]
Ah, okay. Forgot to use search, he, he :P
