### ISSUE TITLE
Autoplay, autocontinue, autostart

### ISSUE THREAD

**Issue by BenWiederhake** [ParticleCore/Particle#238]
1. Since Youtube already has a feature called 'autoplay'.  Could you rename [the autoplay feature](https://github.com/ParticleCore/Particle/wiki/Features#adv_autoplay) to "autostart" or somethng?
2. Youtube's autplay feature has another "feautre for youtube": it tries to detect people who are afk.  [That's not new (here's my workaround from "back then")](http://userscripts-mirror.org/scripts/review/183897), but still annoying.  The autoplay-button is the only element of the website of class `ytp-upnext-autoplay-icon`, so `document.getElementByClass("ytp-upnext-autoplay-icon")[0].click()` works fine for me.  I propose the name "autocontinue" for this, or "true autoplay".  Whatever.  I just want to hear music, even when Youtube (falsely) thinks I'm afk.

**Comment by BenWiederhake** [comment]
A somewhat easy way to trigger this is to scroll down so that the video part is no longer visible, then change to a different tab, and wait for a while.  As soon as youtube thinks you're afk, you can view at it in peace, without racing against the timer.  (Scrolling down again resets the timer.)

**Comment by ParticleCore** [comment]
I am not interested in changing the Autoplay feature name. However you can edit your locale and change it to the name you prefer: https://github.com/ParticleCore/Particle/wiki/Features#custom_lang

Regarding the feature request to not pause Autoplay Up Next, I haven't felt the need to implement it yet.

**Comment by BenWiederhake** [comment]
Aww, dangit.  Thanks for the quick response though.
