### ISSUE TITLE
 width control panel

### ISSUE THREAD

**Issue by Alexey71** [ParticleCore/Particle#240]
Hi. The control panel is not the entire width
Fit to page in theater mode - true
Fit to page max width - 84%

![2016-03-26_190504](https://cloud.githubusercontent.com/assets/10572914/14061010/39bc6dc2-f386-11e5-94c2-b5f6fa31639a.jpg)

**Comment by ParticleCore** [comment]
Please provide the information requested in the troubleshooter: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#posting-a-new-issue

Which Operating System are you using, which browser, what browser version and extension version.

**Comment by Alexey71** [comment]
Browser Name: Firefox 
Browser Version: 45.0.1 x64
Operating System: Windows 10 x64
Software Type: Userscript
Software Version: 1.1.9
Userscript Manager: Greasemonke
Userscript Version: 3.7
Problem Description: The control panel is not the entire width
Steps to reproduce: Setting - Video - Fit to page in theater mode - true and Fit to page max width - 84%
https://www.youtube.com/watch?v=q2j7_oY6Kb8

**Comment by ParticleCore** [comment]
I am unable to replicate it on the same environment, can you share your YT+ settings so that I can see if this is a result of a certain combination? You don't have to include your blacklist.

**Comment by Alexey71** [comment]
Close, I solved the problem, clear the cache.

**Comment by ParticleCore** [comment]
Glad to hear that, if you have any other problem just let me know!
