### ISSUE TITLE
Select default video codec

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#243]
Provide users with the ability to select which codec (format, video type?) they prefer to be played by default whenever possible (mp4 or webm).

**Comment by Eisys** [comment]
@ParticleCore 

Sorry to make an unrelated comment here but I didn't want to make a new issue to ask a quick question. And github has no private message feature..

Is it just me or is the YT subbox broken lately? I've noticed quite a few videos not showing up. 
But when I go to a channel's videos page, the video is public. Sometimes it takes 30 minutes, sometimes hours from video upload, for them to finally show up on the subs page, even if I watch the video.
I get roughly 20-40 videos a day and about 2 or 3 of them won't show up right away.

Case in point:
http://i.imgur.com/98X3Mon.png
Subs page: http://i.imgur.com/JTMiECY.png
This is even after clearing browsing data and running CCleaner.

If it is just me then what could be the problem? This is getting really annoying.

And out of curiosity, what is the benefit of being able to change codecs?

**Comment by ParticleCore** [comment]
There's no problem with making a question, it might even help others with the same doubt.

You are not imagining things, YouTube has been recently a bit unstable. On my end I've noticed up to 5  new videos showing from my subscribed channels and then they disappear after I refresh the page some time later, and they don't reappear for a while either. I give this about a week to get fixed, it usually doesn't take any longer than that.

Regarding changing codecs, the benefit is on the processing cost for playback. Webm supposedly tools higher on the machine than mp4 but webm has been showing higher quality than mp4 as well, so this option will allow users to either favor quality (if they want webm by default in Firefox) or lighter playback (if they want mp4 by default on Chrome).

I am still not sure if I will add this feature, it will depend on the test results.
