### ISSUE TITLE
"Player always visible when reading comments" isn't working

### ISSUE THREAD

**Issue by Maheshchiramure** [ParticleCore/Particle#248]
Settings > Video > Player always visible when reading comments

Unchecked it, saved the settings, but the Player won't leave me alone. Why must be that ?

**Comment by ParticleCore** [comment]
Please provide more information than just that, it is not sufficient for me to replicate or understand the cause of this problem. Follow the reporting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having this problem follow the instructions in the previous reply.
