### ISSUE TITLE
Layout issue in grid subscriptions

### ISSUE THREAD

**Issue by mleyen** [ParticleCore/Particle#25]
Greetings. I found out about this addon today as I was looking for a replacement for YouTube Center (which has not been updated for 1 month now). And it seems to be doing great, definitely faster than YTC.
There are still some features I am missing, such as thumbnails with animations and like/dislike bar – I can make separate issues if needed –, but otherwise, great addon.

But enough with the formal blah blah blah. Here's what my subscriptions page looks like:
![mes_abonnements_-_youtube_-_2015-06-08_21 54 42](https://cloud.githubusercontent.com/assets/6747270/8043922/683da906-0e29-11e5-8fcf-8a20ab9cffef.png)

The video from Regular Ordinary Swedish Meal Time is offset by a few pixels because of the longer channel name.

Is there any way to fix that?

**Comment by ParticleCore** [comment]
I have fixed that issue recently, which I just confirmed via a quick test done on my end right now:

![ss](https://cloud.githubusercontent.com/assets/9222661/8047352/a5490fb6-0e33-11e5-993d-4c28d2a85aa7.png)


Are you using the most recent version? Currently the latest version is 0.1.4
