### ISSUE TITLE
blacklist controls conflict with YT ratings preview

### ISSUE THREAD

**Issue by honnza** [ParticleCore/Particle#250]
Browser Name: Firefox

Browser Version: 45.0.2

Operating System: Windows 7 Home Premium

Software Type: any

Software Version: 1.2.0

Steps to reproduce:  
* Install Greasemonkey and Youtube Plus into a fresh profile (first observed in the addon version, also reproduced with the userscript version).
* Install Youtube Ratings Preview from http://ratingspreview.com .
* Navigate to http://youtube.com (first observed on the subscription page and on a video page, also reproduced on the homepage).
* Hover a video thimbnail and click the "blacklist" button that appears.
* * Expected result: Video channel is added to the YT+ blacklist.
* * Actual result: Youtube navigates to the video page.

Additional information: The YTRP addon bug report page does not seem to be operating correctly at this moment, redirecting to an unrelated product's Chrome extension page instead.

**Comment by ParticleCore** [comment]
This should be fixed in the latest version, update and remember press Ctrl + F5 on a YouTube page. Let me know if it works for you too.
