### ISSUE TITLE
Stop Autoplay Video in Background Tabs like in chrome (feature request)

### ISSUE THREAD

**Issue by stalingraddd** [ParticleCore/Particle#255]
Currently YouTube+ addon has a feature to stop autoplay, but it will be better if you make an option to autostop playing only videos which where opened in background tabs and this tabs are not focused. If i click(focus) the tab that was previously opened in background, than video should begin autoplay without user interaction. 
In short - copy autostop behavior from chrome browser

**Comment by ParticleCore** [comment]
Duplicate of #52

**Comment by stalingraddd** [comment]
problem solved with this https://addons.mozilla.org/en-US/firefox/addon/youtube-enhancer-plus/?src=external-mrfdev
