### ISSUE TITLE
Unable to select settings

### ISSUE THREAD

**Issue by DustyF0X** [ParticleCore/Particle#256]
Browser Name: Firefox

Browser Version: 45.0.2

Operating System: Windows 7

Software Type: Add-on

Software Version: 1.2.3

Problem Description: Unable to select settings. 

Steps to reproduce: Install the add-on, go to youtube and click on the youtube+ button, then click on any setting option.

Additional details: 
Greasemonkey userscript works. I use userstyles(specifically darktube), so the userstyle might be interfering with the add-on, but does not affect userscript.

**Comment by DustyF0X** [comment]
Removing the userstyle fixed problem.

**Comment by ParticleCore** [comment]
Glad to hear you were able to fix it.
