### ISSUE TITLE
Its not really an issue; Its some requests. I dont know where to post requests.

### ISSUE THREAD

**Issue by TeenDroid** [ParticleCore/Particle#259]
First of all Thanks for this beautiful userscript, its so wonderful. I cant browser youtube without this anymore, pop up player, player visible in comments,...great.
I would like to see some more features here, pls add them if possible:

1) Video thumbnail animation
2) Download option
3) Country flag of the uploader &amp;amp;amp; comenters
4) Rating bar in video list(over the video)
(These are the features from 'YoutubeCenter' that I really wish to see here in 'YOUTUBE +'. Currently YTcenter and YT+ both cant be enabled together, then  the player wont work anymore, tried all different configurations but not working, may be you can guide me to make them use together!)

5) Buffering limiter(DASH not really limiting the buffering, what I mean is, if there is an option to 'buffer till only 1 minute ahead' or so, it will be a great option for users like me who have limited data plan.
6) Embedded video auto stop,auto buffer stop, auto quality change. (now youtube videos embedded in some sites are getting played in default youtube 360p where I setted it to 144p in youtube)
7) Live streams quality changer (like auto 144p)
8) 'Maximum data save mode' (where every other option like side bar, other data using contents stop downloaded to the browser, and only the video will be played in maximum data save mode like 144p)
9) Option to export-import settings

Hope I can see there feature in near feature. Thanks in advance.

**Comment by ParticleCore** [comment]
Hello TennDroid, I am sorry but as it is indicated in the add-on, extension details section and in the readme: 

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle

Nevertheless I still do check now and then for the possibility of adding or replacing a new feature whenever it is possible.

**Comment by q1k** [comment]
I'd really love to see the maximum video quality displayed on thumbnail on hover. That way it won't be necessary to open a video, we could easily pick the higher quality video to open first.
Also the thumbnail animation would be really nice, it is very useful to get a feeling if a video is legit or not.

I really miss those from youtube center

**Comment by Betsy25** [comment]
I also would love to see the max quality available when hovering thumbnails.
Really miss that feature since switching over from YT Center.

**Comment by thegrandpow** [comment]
I really need the quality indicator on hover (or not it doesn't really matter), and the animation.
