### ISSUE TITLE
Reporting Sexual content forces jump to General Settings interface

### ISSUE THREAD

**Issue by eld3bon** [ParticleCore/Particle#262]
Browser Name: Chrome

Browser Version: 49.0.2623.112 m

Operating System: Win 8.1 Pro

Software Type: Extension

Software Version: 1.2.5

Problem Description: Whenever I find a sexually explicit video and proceed to report it, once I click on the 'Sexual Content' to select the type of the issue, the extension jumps to the general setting page for some reason. It goes back to the page after I click anywhere else on the page it disappears and goes back to the page. It might not be a big deal, but I find it inconvenient and disorienting.

Steps to reproduce: 
>Open any youtube video.
>click More action > Report
> Under 'What is the issue?*' > choose 'Sexual Content'

Additional details:  It doesn't happen with any other option in the same list.

**Comment by ParticleCore** [comment]
Seen it happening on my end as well, will try to push a fix for it with the next update.
