### ISSUE TITLE
Top comment aren't showing even when selected

### ISSUE THREAD

**Issue by nicolasfreitas** [ParticleCore/Particle#264]
Browser Name: Chrome

Browser Version: Version 50.0.2661.102 m

Operating System: Windows 10

Software Type: Extension

Software Version: 1.2.6

Problem Description: Top comment aren't showing even when selected, it's always in "Newest first"

Steps to reproduce: Open any recent videos and the comments are always in Newest first, the only time it doesn't happen is older videos like 2 or 3 months ago.

**Comment by ParticleCore** [comment]
I have just tested on 10 different recent popular videos, they have no trouble sorting the comment section. Have you tried to see if the problem persists after YT+ is disabled and refreshing the YouTube page? As far as I can tell YT+ should not be interfering with the comment sorting and if it was then it would interfere for all videos.

**Comment by nicolasfreitas** [comment]
I have tried with the extension off and still has this problem.

**Comment by nicolasfreitas** [comment]
Just tried Incognito mode with the extension turned off and it now works.

**Comment by ParticleCore** [comment]
Then it is not being caused by YT+. If it works in incognito mode then it is likely there is another extension causing this, disable each one individually until the problem disappears.

Let me know which one it was so that it might help others in the future under the same situation.

**Comment by nicolasfreitas** [comment]
I have tried clearing cookies and with no extension, still didn't work. But with Incognito works.... Hmmm

**Comment by ParticleCore** [comment]
That is very strange. If by "clearing cookies" you mean clear all data from Chrome's setting `chrome://settings/clearBrowserData` and selected `Obliterate the following items from: the beginning of time` then I can't think what else could be causing this on your end.
