### ISSUE TITLE
Don't play seen videos / more videos

### ISSUE THREAD

**Issue by WurstCommander** [ParticleCore/Particle#269]
Hi,

first of all thank you for your great extension.

Is it possbile that the extension won't play seen videos with "Play recent videos" and where can I change the settings that it plays more than 20 or even all videos at once?

Thank you!

**Comment by ParticleCore** [comment]
The extension does not offer the ability to filter watched videos and the 20 video limit is a limitation on the YouTube side for temporary playlists.
