### ISSUE TITLE
Cinema mode

### ISSUE THREAD

**Issue by motlee** [ParticleCore/Particle#27]
New Cinema mode is a a good idea, but I suggest it be not applied to paused playing and playing with scrolling down when we are usually reading or looking for something.

**Comment by ParticleCore** [comment]
This depends on each person, some would prefer the way it is now, others wouldn't, so I chose to go with the way I prefer the most which is if the user wants cinema mode on then it stays on until the end of the video, when he wants it off then the user has to turn it off.

There's no other way to please both types of users without adding even more code, making the software heavier, and I am trying to keep the software as small and light as possible.
