### ISSUE TITLE
SHOW  HIDE MARK ALL VIDEOS WATCHED

### ISSUE THREAD

**Issue by silat** [ParticleCore/Particle#270]
I will gladly donate if this wonderful extension adds the following items to the subscription grid:

SHOW  
HIDE 
MARK ALL VIDEOS WATCHED

**Comment by ParticleCore** [comment]
I am sorry, but as it is already explained in the readme, userscript and extension descriptions:

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by silat** [comment]
Just thought I would ask:)

**Comment by ParticleCore** [comment]
It's not a problem, I always go through all feature requests whenever I have some time to see if there is one I can implement, but current conditions do not allow me to add all of them.
