### ISSUE TITLE
Advanced options not showing

### ISSUE THREAD

**Issue by dougbenham** [ParticleCore/Particle#274]
advanced-options section beneath the video isn't showing buttons.
Only showing the close button:
`<button id="console-button" data-p="ttl|ADV_OPTS" title="Advanced options" class=""></button>`

No pertinent errors in the console log.

**Comment by Eisys** [comment]
Same problem here.

And the floating player isn't working either, it seems.

Reverting back to 1.3.0 for now.

**Comment by MarioLuigi55** [comment]
Same problem here: on both Firefox and Chrome. Please help.

**Comment by ParticleCore** [comment]
Thank you for the heads up, a fix is already about to be pushed online.

**Comment by ParticleCore** [comment]
1.3.2 includes the fix for this problem, let me know if it works for you as well.

**Comment by Eisys** [comment]
@ParticleCore Everything works perfectly for me now.
Thanks!

**Comment by MarioLuigi55** [comment]
@ParticleCore Everything works now. Thanks for quick response
