### ISSUE TITLE
Mark watched YT videos

### ISSUE THREAD

**Issue by wjk82** [ParticleCore/Particle#276]
Hi!

Many screenshost from Wiki contain marked videos as WATCHED. This is very cool feature, that I can't find anywehere in options page, nor in Wiki pages of YT+. Is this function a part of YouTube+ and I need to look for reason why I'm missing it or do You using some external extension/script?

Bye.

**Comment by ParticleCore** [comment]
Hello, the Watched label you see in the pictures are a feature from the YouTube website itself, not YT+. It is only available for logged in users and it marks your watched videos up to a certain date (it doesn't mark all of them forever).

**Comment by wjk82** [comment]
Thanx for info. I did a research and apparently a lot of people complain about this function not working. I'm also the victim of YT bug. I always thought it was a external thing becouse I was using YTC this function worked fine, but when I switched to Yours plugin it stop working. Apparently becouse of faulty Google code.
