### ISSUE TITLE
Hide Header

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#278]
How do i hide the header so i can hover it like in ImprovedTube???
![4312432](https://cloud.githubusercontent.com/assets/18757054/16182877/116edc7a-36ab-11e6-8ae4-6e7832808c65.jpg)

**Comment by ParticleCore** [comment]
YT+ does not have nor advertises such a feature, you can see all the available features listed here: https://github.com/ParticleCore/Particle/wiki/Features

YouTube Plus is not part of or affiliated with ImprovedTube, the two are independent extensions and most likely incompatible seeing they both modify common cores.

**Comment by GKid94** [comment]
Well can you add that feature???

**Comment by ParticleCore** [comment]
I am sorry, but as it was already explained in the userscript, add-on and extension descriptions, and in the [GitHub readme](https://github.com/ParticleCore/Particle/blob/master/README.md):

>Due to time and framework limitations I am unable to accept any more feature requests.

**Comment by Eisys** [comment]
@GKid94 
You can use one of these scripts: http://i.imgur.com/0HAoWrX.png
From this page: https://gist.github.com/Yonezpt
Both still work. 
The first one should work like ImprovedTube. You might want to change some of the numbers in that script to make the animation faster or to change when it activates.

Or, you can this style: https://userstyles.org/styles/119282/youtube-no-masthead with Stylish. 
And make it only activate on the /watch page.

**Comment by q1k** [comment]
It's better to use > #masthead-positioner{position: absolute !important;}
That way it will disappear when scrolling down.

**Comment by GKid94** [comment]
idk how to insert scripts im not a programmer
