### ISSUE TITLE
extension looses all its settings after every update

### ISSUE THREAD

**Issue by phpmoli** [ParticleCore/Particle#279]
Browser Name: iceweasel
Browser Version: 38.8.0
Operating System: debian v8
Software Type: youtube plus
Software Version: 1.2.8
Userscript Manager: -
Userscript Version: -
Problem Description: it is the second time now the extension has been auto-updated, and it is the second time now, all my extension settings had been reset to default.
Steps to reproduce: i guess, update the extension.
Additional details: -

If you need further info, please ask.

**Comment by ParticleCore** [comment]
The most recent version of YT+ is 1.3.3 https://github.com/ParticleCore/Particle/releases/latest

If you are using the AMO version then it is stuck pending review.

Additionally YT+ is only supporting Firefox 38+ and Chrome 42+ https://github.com/ParticleCore/Particle/blob/master/README.md

The most likely cause of your problem is the use of a non-supported browser. Users in your situation have better results by using the userscript version, which supports more browsers depending on the userscript manager in use.

**Comment by phpmoli** [comment]
Hello Particle, thanks for the reply.

> The most recent version of YT+ is 1.3.3 https://github.com/ParticleCore/Particle/releases/latest
> If you are using the AMO version then it is stuck pending review.

the latest version in the mozilla store is [1.2.8](https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/). i think users (using this word in the derogatory way) update their extensions automatically through the stores (every stores, like android, etc) and not manually, so thats can not be expected nor required.

> Additionally YT+ is only supporting Firefox 38+ and Chrome 42+ 
> The most likely cause of your problem is the use of a non-supported browser.

iceweasel is "firefox". for more info: [https://en.wikipedia.org/wiki/Iceweasel](https://en.wikipedia.org/wiki/Iceweasel)

**Comment by ParticleCore** [comment]
Iceweasel (just like Palemoon and many others) is not Firefox. Iceweasel is a Firefox fork and that is not the same as being Firefox itself:

>Iceweasel is a fork [from Firefox] with the following purpose

https://wiki.debian.org/Iceweasel

And that is the main reason for why you are having your problem.

**Comment by phpmoli** [comment]
as far as i know, iceweasel is not a real fork fork, it is just firefox with some text labels and icon images changed.
at that's all, really. nothing more. just some text and icons.

**Comment by ParticleCore** [comment]
The fork quote was taken directly from the Iceweasel's developers themselves. If YT+ is not working correctly but it does work correctly with Firefox then there is without a doubt something more modified besides text labels and icon images. Whatever the case may be, it is not a supported browser.
