### ISSUE TITLE
Player half visible when reading comments

### ISSUE THREAD

**Issue by LouLeGrain** [ParticleCore/Particle#28]
Hi ! Amazing script, but i've got an issue with this feature... The video gets on the sidebar well, but way too large (& high). Here's a screenshot. I'm on fullscreen, i've just croped the image to hide the top bar
![capture du 2015-06-18 21 45 36](https://cloud.githubusercontent.com/assets/9808953/8240596/0e9613ce-1604-11e5-99eb-6be4edf938df.png)
I'm on ubuntu 14.04 with Firefox 38.0 (Greasemonkey 3.2) & Y+ 0.1.8

**Comment by ParticleCore** [comment]
Could you follow the steps mentioned in the troubleshooting guide to rule out any possible conflict caused by other add-on/userscript? https://github.com/ParticleCore/Particle/wiki/Report-a-problem

Also make sure that you are using the most recent Firefox version 38.0.5

**Comment by LouLeGrain** [comment]
I did it before posting this issue, thought it was a conflict with Stylish (https://addons.mozilla.org/fr/firefox/addon/stylish/)
I re did it by disabling other userscript (youtube to mp3) & stylish and restarting firefox.. Got the same issue :/
apt-get update / upgrade doesn't change anything to the mozilla version

**Comment by ParticleCore** [comment]
The mozilla auto update is not enabled until they approve my add-on, which is still in the position 150 out of 258. To update the latest version you have to go to the page and install it manually like you did the first time.

That is, if you are not using the latest YT+ v. 0.1.8

**Comment by LouLeGrain** [comment]
Excuse my english, i'm afraid i don't understand... In my first post i said i was using your userscript (v. 0.1.8) with Greasemonkey 3.2. Are we talking about that, or about an add-on for firefox ?

**Comment by ParticleCore** [comment]
Yes, you are right, I already corrected my previous reply, if you refresh you should see the correction with the new information I need to know.

**Comment by ParticleCore** [comment]
Oh you already included the version you are using, which is indeed the latest YT+ version. Do you have any other add-ons and userscripts running besides the ones you mentioned before? Any adblocker too?

**Comment by LouLeGrain** [comment]
Yes, but nothing to worry about i guess...
![capture du 2015-06-18 22 46 02](https://cloud.githubusercontent.com/assets/9808953/8241864/06619ae0-160c-11e5-881c-a137fa8ce78d.png)
I have an adblocker (adblock plus) i will disable it then restart firefox, i'll tell you.

**Comment by ParticleCore** [comment]
I'd prefer if you disable everything except YT+ like the troubleshooting guide instructed, this way it will be easier to see if there's any conflict with another add-on.

**Comment by LouLeGrain** [comment]
Ok, disabled everything except Greasemonkey & YT+ (nothing changes)
Suggested videos aren't removed or blocked (everything is disabled)
I'll try to reset all the YT+ parameters

**Comment by ParticleCore** [comment]
Could you try installing the add-on version to see if the issue is specific to the Greasemonkey add-on or not? https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/

I am still downloading Ubuntu, until then I am unable to test this on my end, so apologies for making so many questions.

**Comment by ParticleCore** [comment]
The suggested videos I am refering to are not the ones that can be disabled in the YT+ options, I am talking about this sidebar: 
![ss](https://cloud.githubusercontent.com/assets/9222661/8242128/db1e9eaa-15fc-11e5-8ce3-84524968c378.png)

Could you try installing the add-on version to see if the issue is specific to the Greasemonkey add-on or not? https://addons.mozilla.org/en-US/firefox/addon/youtube-plus/

I am still downloading Ubuntu, until then I am unable to test this on my end, so apologies for making so many questions.

**Comment by LouLeGrain** [comment]
No problem !
I have a lot of css bugs in the firefox dev console, but only one warning for JS which says getPreventDefault() is obsolete
I install the add-on and i'll tell you what's up

**Comment by ParticleCore** [comment]
What about the sidebar screenshot I posted, is that one still present in the YouTube pages or is it changed/removed via Stylish or Adblock?

**Comment by LouLeGrain** [comment]
Here it is :) As i said, i disabled everything except the add-on.
![capture du 2015-06-18 23 10 32](https://cloud.githubusercontent.com/assets/9808953/8242425/770b08b4-160f-11e5-9f76-8aee0975de62.png)
And past 50% video height
![capture du 2015-06-18 21 45 36](https://cloud.githubusercontent.com/assets/9808953/8242462/b4524f98-160f-11e5-90b6-91d65c96734a.png)

**Comment by ParticleCore** [comment]
Thank you, it seems like I have exhausted all the possibilities, I will now have to test it by myself and see if I can replicate the issue to find out what is causing it. Until then, disabling the option "Player always visible when reading comments" should prevent this from happening.

**Comment by LouLeGrain** [comment]
You're welcome, contact me if you need more informations ;)
I saw other bugs too (blue notification seems to have a margin-left) but this one is the most embarassing
![capture du 2015-06-18 23 34 18](https://cloud.githubusercontent.com/assets/9808953/8242861/baaa55a4-1612-11e5-87ce-c858d344521c.png)
Have a nice debugging !

**Comment by ParticleCore** [comment]
That one is a result of having YouTube with a non-english language (notice the FR icon next to the logo), causes some shifting to occur. I'm still trying to figure a simple way to tackle that annoying bit.

**Comment by ParticleCore** [comment]
So I just tested with exactly the same builds as yours (Ubuntu 14.04.2 + Firefox 38.0) for both the add-on and userscript versions, but I cannot replicate your issue:

![ss](https://cloud.githubusercontent.com/assets/9222661/8244576/fb904386-1611-11e5-9e29-5dd8ccf8c945.png)

I also did the same tests with French language and then with French country selected, the result was the same.

I believe that you have something different in your Firefox profile which is causing this issue somehow, a simple changed setting in the about:config page might be enough to cause it, but the only way to be sure is if you try it again with a new profile: https://developer.mozilla.org/en-US/docs/Mozilla/Multiple_Firefox_Profiles

Section `Starting Profile Manager in Linux`, Create Profile, `Next`, `Finish`, Select the newly create profile, hit `Start Firefox`, check if the issue persists.

**Comment by LouLeGrain** [comment]
Sorry...
![capture du 2015-06-19 01 48 14](https://cloud.githubusercontent.com/assets/9808953/8244779/64bd5c6e-1625-11e5-91d3-0f3e0422cf32.png)

**Comment by ParticleCore** [comment]
This is so very strange... Can you send me that webpage's source code? You can use the http://paste2.org/ website for this.

Remember to share the html that is in the console, not in the page itself. Usually to open the console press F12, select the "Inspector" tab, right click the top most element that starts with `<html ...`, choose `Copy outer HTML`.

**Comment by ParticleCore** [comment]
Could you also right click the youtube player and send me a screenshot of the sub-menu that appears?

**Comment by LouLeGrain** [comment]
The HTML/JS : http://paste2.org/bjU7PNc8
And for the right click it's complicated, i can't do a screenshot while this submenu is activated... i search how to fix that. But if you want the flashplayer version : 11.2.202.466

**Comment by ParticleCore** [comment]
So that's it! You are getting the flash player which I am not providing support, this is the problem. You should be using the HTML5 instead for the software to work correctly. Why are you not receiving the HTML5 player is confusing, unless you disabled it in the Firefox about:config settings, did you?

**Comment by LouLeGrain** [comment]
Mhhh... I don't think so, however i'll search how to force HTML5 playing with youtube :) Thanks alot !

**Comment by ParticleCore** [comment]
It is weird that you are getting the flash player because you and I used the same platforms and you should be getting the same player as I. Try enabling it here: https://www.youtube.com/html5

There should be a blue button a the bottom named "Request the HTML5 player" if has that capability.

**Comment by LouLeGrain** [comment]
Exactly what i did :) 
![capture du 2015-06-19 02 12 49](https://cloud.githubusercontent.com/assets/9808953/8245012/c5bcc60a-1628-11e5-8dea-ad6bba3605be.png)

**Comment by ParticleCore** [comment]
Woo, guess that is done then! Thanks for being so patient.

**Comment by LouLeGrain** [comment]
Thank you too ! For the same thing :)
