### ISSUE TITLE
White Icon(s) in Cinema Mode

### ISSUE THREAD

**Issue by MailYouLater** [ParticleCore/Particle#280]
**Browser Name:** Firefox
**Browser Version:** 47.0 (Build ID: 20160604131506)
**Operating System:** Windows 7 (Windows_NT 6.1 x86)

**Software Type:** Add-on. (Installed from https://addons.mozilla.org/en-US/firefox/addon/youtube-plus)
**Software Version:** 1.2.8

**Problem Description:** I can't see any of the YT+ icons when in Cinema mode, which makes it difficult to exit Cinema mode.
**Steps to reproduce:** After installing YouTube Plus, play a video on YouTube, and click the "Cinema mode" icon. Everything but the video itself becomes black (or almost black), making it very difficult to find the "Cinema mode" icon, which as far as I can tell is the only way to exit Cinema mode.

**Additional details:** What I would like to see is that the YouTube Plus added icons become white when everything else turns black, so that one can still see them when in Cinema mode. Please at least make the "Cinema mode" icon more visible while in Cinema mode so that it's not so extremely difficult to find.

Thank you.

**Comment by ParticleCore** [comment]
The purpose of the cinema mode is to dim everything besides the video so that the user can focus on the video without distractions, having white icons would defeat that purpose. In the future I will consider finding a different way of controlling the cinema mode.
