### ISSUE TITLE
Fullscreen video button does not actually make video to go fullscreen (happens randomly)

### ISSUE THREAD

**Issue by xIxHATExMOBILExPROVIDERSx** [ParticleCore/Particle#281]
This is quite random issue because it doesn't happen all the time, but quite randomly. Time to time when clicking the Fullscreen button it will just stretch the video to the edges and not make it fullscreen.

Chromium 53.0.2780.0
YouTube+ 1.3.3

Pretty sure of that this is an issue on YouTube's side but is there a way to force it to go fullscreen no matter what?

**Comment by ParticleCore** [comment]
I am sorry but this is strictly YouTube dependent, they need to correct this problem:

https://www.reddit.com/r/youtube/comments/4httvq/what_is_wrong_with_the_fullscreen/

https://www.reddit.com/r/youtube/comments/4jgm0w/wtf_happened_to_fullscreen/

https://www.reddit.com/r/youtube/comments/4j4efi/youtube_fullscreen_mode_changed/

https://www.reddit.com/r/youtube/comments/4pjakq/why_does_this_happen_when_i_try_to_go_fullscreen/

https://www.reddit.com/r/youtube/comments/4hlbu3/hey_when_you_guys_fullscreen_your_video_is_it_not/

https://www.reddit.com/r/youtube/comments/4i6pgz/fullscreen_bug_youtube_doesnt_let_me_fullscreen/

The current workaround is to press F11 when that happens (it makes your browser go fullscreen along with the player). Remember to press F11 again to exit your browser from fullscreen.
