### ISSUE TITLE
UI to the right of videos does not extend past the window border

### ISSUE THREAD

**Issue by sxmichaels** [ParticleCore/Particle#282]
Browser Name: Firefox
Browser Version: 47.0.1
Operating System: OS X El Capitan 10.11.5
Software Type: Add-on
Software Version: 1.3.3
Problem Description: 
    With Youtube+ activated, the Youtube UI takes up exactly the size of the browser window, prioritizing the video player. The result is that if the browser window is not much bigger than the video player, the sidebar content gets collapsed into oblivion, only displaying a few characters, and the user cannot scroll horizontally to read the recommended video list because it cuts off at the point where the rightmost border of the browser was when the page loaded. This behavior seems intentional — is it possible to have an option to either 1) not attempt to limit the sidebar width to adhere to the browser window or 2) force the sidebar content below the video, as would happen if the browser window is made very small? As far as I can tell there is no existing option that does either.

Images below. I have scrolled as far as I can to the right in both cases.

With YT+
![](http://i.imgur.com/xdIHRw9.png)

Without YT+
![](http://i.imgur.com/7QX5k3n.png)

Steps to reproduce:
    1. Make the browser window only slightly larger than the YT video player
    2. Load a video and look at the sidebar

Additional details: None I can think of, but certainly tell me if you need any more information.

**Comment by ParticleCore** [comment]
It is an unfortunate side-effect for lots of features to work properly and I have yet to find a proper solution for this which doesn't entail lots of problems. Currently the best suggestion I can offer is to use the window at a size of 620px or less, which automatically switches to the mobile layout.
