### ISSUE TITLE
[Setting Issue] To open Setting script require connection to Github

### ISSUE THREAD

**Issue by ldgbc** [ParticleCore/Particle#283]
Browser Name: Firefox 
Browser Version: 47 stable
Operating System: Windows 10 x64
Software Type: YouTube +
Software Version: v.1.3.3
Userscript Manager: Greasemonkey
Userscript Version: 3.8

Problem Description: To open setting, I need to allow Youtube's 3rd party connection (CSS) to "particlecore.github.io"

Steps to reproduce: 
1. Install uMatrix
2. Block all 3rd party IMG and CSS with uMatrix
3. Open any Youtube page
4. Setting button to Youtube + script is missing.
5. Use uMatrix and enable 3rd party CSS "particlecore.github.io"
6. Refresh the page
7. Youtube+ setting button is now visible and you can change setting.

Additional details: I suppose most people will not have this problem. However is the script design in a way that it require CSS from Github?

**Comment by ParticleCore** [comment]
Yes, this is how it is suppose to work because Userscripts cannot pack images nor CSS stylesheets with them, so they need to be hosted somewhere.

**Comment by ParticleCore** [comment]
Alternatively you can use the add-on versions since you are using Firefox. Those versions are capable of loading files with them so they don't connect to remote resources like userscripts do.
