### ISSUE TITLE
[Feature] h264 instead of VP9

### ISSUE THREAD

**Issue by ldgbc** [ParticleCore/Particle#284]
Browser Name: Firefox 
Browser Version: 47 stable
Operating System: Windows 10 x64
Software Type: YouTube +
Software Version: v.1.3.3
Userscript Manager: Greasemonkey
Userscript Version: 3.8

Problem Description: Youtube default to using their VP8/VP9 codec (WebM), but it possible to enforce or default using their h264 version (MP4).

Steps to reproduce: 
1. Open any Youtube video
2. Right click on video
3. Choose "Stats"
4. Under MIME: video/webm, codecs="vp9"

Additional details: For references, see: https://addons.mozilla.org/en-US/firefox/addon/h264ify/?src=search on how it is done.

Thank you for making this script.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by GKid94** [comment]
@ldgbc Does the h264ify extension work if you already have the YT+ extension? 😕
