### ISSUE TITLE
Import settings is broken

### ISSUE THREAD

**Issue by BooBerry** [ParticleCore/Particle#287]
Greetings!

I've noticed that importing settings into YouTube+ isn't working currently - it resets back to the default settings. I've tested this in Greasemonkey, Tampermonkey and Adguard using Chrome and Firefox on Windows, Mac OS X and Arch Linux. And yes, I am clicking save and load then the blue save button when pasting the settings in.

My settings: http://pastebin.com/nZXpS0ay

Steps to reproduce:

1. Reset settings in YouTube+'s settings and save the settings. Close the YouTube tab/window.

2. Reopen the YouTube tab/window and import the settings, click save and load and click the blue save button. Again close the YouTube tab/window.

3. Reopen the YouTube tab/window and confirm that the settings weren't imported and thus they're back at the default settings.

**Comment by Eisys** [comment]
Can confirm.

It seems that the actual thing broken is the 'Save and Load' button/feature.
It used to load the actual settings and close the import/export part. That doesn't happen anymore.

**Comment by ParticleCore** [comment]
Will see what is causing this and try to publish a fix as soon as I can.

**Comment by ParticleCore** [comment]
This has been fixed in version 1.3.4 let me know if it works for you as well.

**Comment by Eisys** [comment]
Works for me. Thank you!

**Comment by BooBerry** [comment]
Works here too, thanks! :+1:
