### ISSUE TITLE
Video stops and reloads when + button is clicked

### ISSUE THREAD

**Issue by grenzor** [ParticleCore/Particle#288]
When you are playing a video go a bit into the video and then click the YT+ button, the video suddenly stops and when you click the button again to go back to the video it reloads the video from the start. As far as I can remember this didn't seem to happen a while back

**Comment by ParticleCore** [comment]
I cannot replicate this in either browser. Additional information is necessary, please follow the instructions was requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#posting-a-new-issue

**Comment by ParticleCore** [comment]
I will close this for now, if you still need help please follow the instructions in my previous reply.
