### ISSUE TITLE
Chrome extension, alternate download option

### ISSUE THREAD

**Issue by Tharn** [ParticleCore/Particle#289]
Hi,

I use Inox, a Chromium for Linux with certain patches built-in. As a result, I can't use the Chrome Store at all. It'd be cool if you could offer the extension as a Chrome package on GitHub so we can use the "Load unpacked extension.." option to get it installed anyway.

Cheers,

**Comment by ParticleCore** [comment]
I am sorry but I have no intentions of supporting other browsers besides Firefox and Chrome.

However, the version available in the webstore is a simple .zip file (with .crx name) containing the unpacked extension,  all that is required is to extract its contents into a folder and use that folder the way you described. There are many ways that you can use to download an extension without Chrome, an example is this website: http://chrome-extension-downloader.com/

**Comment by Tharn** [comment]
Actually hadn't heard about that website. That is immensely useful. Thanks!
