### ISSUE TITLE
Option to remove related videos at the end of videos

### ISSUE THREAD

**Issue by Reposium** [ParticleCore/Particle#29]
Hi!

I was wondering what your thoughts were on implementing an option to remove the related videos displayed at the end of a video, which is a feature I liked in Youtube Center.

Thanks.

p.s. Youtube Plus is an awesome addon! Keep up the great work!

**Comment by ParticleCore** [comment]
This isn't a feature that I found to be useful so I never had intentions to add it.

**Comment by q1k** [comment]
.html5-endscreen.ytp-player-content.videowall-endscreen {
    display: none !important;
}

**Comment by Reposium** [comment]
I've already gotten used to having an endscreen again to the point where I don't care either way whether it's there or not, but thanks anyawy! - I appreciate the input.

**Comment by reddit-is-fun** [comment]
###movie_player > .ytp-show-tiles.videowall-endscreen.ytp-player-content.html5-endscreen

Creating a filter in adblocker should remove the endscreen,
