### ISSUE TITLE
Theater mode doesn't account for vertical height

### ISSUE THREAD

**Issue by biiiipy** [ParticleCore/Particle#291]
Theater mode will expand horizontally, but the problem is when video's height is greater than available vertical space, then the bottom will not be visible. This is really not the way it should work. Theater mode should fill available space and resizing video to fit.
It should work like in "Full-Browser mode", but with the top bar visible and enabled scrolling etc.

**Comment by ParticleCore** [comment]
It is a limitation imposed by YouTube's layout and the workaround for some of the YT+ features to work.
It is for this reason that there is the possibility to choose how big the player can be in theater mode: https://github.com/ParticleCore/Particle/wiki/Features#fit_max_width

The alternative would cause a big code overhead which would not be worth it.

**Comment by biiiipy** [comment]
I don't see why that would be so hard. You have to change this line: https://github.com/ParticleCore/Particle/blob/master/src/Add-on/data/YouTubePlus.css#L699
to ```height: calc(100vh - 50px);```.
There's a small bug with this part - https://github.com/ParticleCore/Particle/blob/master/src/Add-on/data/YouTubePlus.css#L707-712 - but other than that it looks like it's working beautifully.
It depends of fixed toolbar height, so there's room for improvement, but it's infinitely better than the current behaviour.

**Comment by ParticleCore** [comment]
It depends on much more than that, there are also other dependent features that would be adversely affected by this change. I have already tried to do this when I was building the feature, there were too many problems to be worth it. The best overall solution I found was to let users set the max-width for themselves.

If you want to change the code on your end or use a stylish sheet to use your own method then feel free to do so.

**Comment by biiiipy** [comment]
Maybe you could point to the problems you encountered? I could take a look. I really like this extension, but this missing feature is the most important to me.

**Comment by ParticleCore** [comment]
I am sorry but I will not take up more time with this, I have already explained everything in detail and suggested some workarounds for what you are trying to achieve. I have limited time to dedicate to this extension and using it for something like this would be very wasteful for me, especially when it is something that I am not interested in.

**Comment by ParticleCore** [comment]
@biiiipy Took the liberty to implement his method in YT+, if anyone wishes to use it you can find the necessary changes available here: https://github.com/ParticleCore/Particle/pull/293
