### ISSUE TITLE
YouTube TV not working

### ISSUE THREAD

**Issue by vovokrall** [ParticleCore/Particle#292]
Since I installed YouTube Plus, YouTube TV (www.youtube.com/tv) is not working. I can access the site, choose a video, but it just does not play.

**Comment by mauriciocolli** [comment]
Simple fix is:
`// @exclude         *://www.youtube.com/tv*`

**Comment by vovokrall** [comment]
....what?

**Comment by ParticleCore** [comment]
YT+ is not compatible with YTGaming and YTtv, I will add that to the exclusion list, which is what @mauriciocolli was suggesting, although it is only applicable for the userscript versions.

**Comment by ParticleCore** [comment]
Version 1.3.5 comes with a fix for this issue, let me know if it works for you as well.

**Comment by Piter432** [comment]
> YT+ is not compatible with YTGaming and YTtv

For now or forever?

**Comment by ParticleCore** [comment]
@Piter432 Each of them is almost completely unique, making YT+ compatible for both would require me having to maintain daily 3 almost completely different extensions packed into one. Adding to that workload and my limited time schedule I also do not use either of them, so I have never been interested in extending support beyond vanilla YouTube.

**Comment by vovokrall** [comment]
Thank you!
It seems to work fine!
