### ISSUE TITLE
Checkboxes missing

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#294]
When going to the share tab, the checkboxes are missing.

**Comment by ParticleCore** [comment]
I am sorry but I cannot replicate this problem:

![ss](https://cloud.githubusercontent.com/assets/9222661/16714379/a6038b96-46b0-11e6-9dfa-af539a129f89.png)


Please follow the guide as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by q1k** [comment]
Oh, it's in the 'embed' tab.
The checkboxes are just invisible, but somehow working...

**Comment by ParticleCore** [comment]
Got it, those are unskinned checkboxes (oddly) so they work but they are invisible, will try to post a fix for this as soon as possible.

**Comment by ParticleCore** [comment]
Version 1.3.6 contains a fix for this problem, let me know if it works for you too.

**Comment by q1k** [comment]
Yes, it works.
