### ISSUE TITLE
Disable the new annotations/cards

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#298]
As you probably have seen, there are these new card annotations that only partners can use at the moment.
They work the same as annotations, except for the part where simply disabling annotations won't disable the cards.

What I'm asking of you, is to disable the link of these cards, so when annotations are switched off, these cards don't work either. Essentially making them click through so to be able to pause the video.

**Comment by ParticleCore** [comment]
During my tests, disabling annotations also disabled the new cards. Can you provide an example with instructions for me to replicate this?

**Comment by q1k** [comment]
I don't know, [here's a video](https://www.youtube.com/watch?v=2-dbZD-gXI0), at the end it has 4 of those cards.

BTW, the only option in the [playback settings](https://www.youtube.com/account_playback) is this:
http://i.imgur.com/j7NqY5W.png

**Comment by ParticleCore** [comment]
Seems like they finally split the cards from the annotations. Bad news is YT+ needs to be updated (if I manage to find a way to disable the cards), good news is users will now be able to disable annotations or cards, or both instead of either all or none.

**Comment by q1k** [comment]
Well if the cards are completely removed that part of the video will be empty, so I was thinking just disable the link.
But simply removing the href part doesn't help, even removing the whole a element doesn't help. It's somehow tied to the div... very strange.

**Comment by ParticleCore** [comment]
Yes, the div has properties attached to it. The new Material Layout makes heavy use of this method, which is why the only viable solution is to either disable it (same disadvantages as disabling annotations) or leave it enabled. Other alternatives are not worth it.

**Comment by ParticleCore** [comment]
The feature appears to be unstable, some channels have it, others don't. For the moment it will be tied to the annotations option, if they stabilize then I will split them into individual features, if they remove the cards then nothing much changes on YT+

**Comment by q1k** [comment]
I'd like that, disabling annotations, to disable cards as well.
ButI don't think youtube will remove these cards, since they are working on mobile as well as desktop. _Previously there were no annotations on mobile._

**Comment by Corruptinglyneedful** [comment]
I really hope we can do something about these.  They are so fucking annoying.

**Comment by ParticleCore** [comment]
I am really sorry, I was waiting for Firefox to release version 48 this week so that this fix would ship with the add-on overhaul. Only now I noticed [FF48 is to be released next week](https://wiki.mozilla.org/RapidRelease/Calendar), not this one. I will push the fix right away.

**Comment by ParticleCore** [comment]
Version 1.4.0 contains a fix for this, let me know if the cards are also removed for you with these new changes.

**Comment by q1k** [comment]
Yes it hides them, but when toggling the annotations trigger, it doesn't restore the cards.

**Comment by ParticleCore** [comment]
It is not toggle-able via the player, they are completely removed if the annotations are set to disabled in YT+ settings. There's no method to toggle them like before, this was the best overall workaround I could find for the moment.

**Comment by q1k** [comment]
Well I have only disabled the option in account playback settings. So the feature from YT+ wasn't needed to be ticked.

Anyway, I feel like there might be a way to do that.
When toggling the switch there is attribute `aria-checked` going back and forth **false/true**.

I think it might be possible to add some listener and remove and hide the cards as necessary?

**Comment by ParticleCore** [comment]
The cards are loaded with the player once it starts, after that they cannot be toggled. They either show or don't, depending on the YT+ setting choice. That's the problem with these cards no longer being tied with the annotations, they can no longer be toggled like before.

If I find a better alternative in the future I will improve it, or perhaps even reverse this change, until then it will stay as it is.

**Comment by q1k** [comment]
Can this help?
https://jsfiddle.net/h81w6cpa/

**Comment by ParticleCore** [comment]
That is the kind of workaround I mentioned before. It is a hack and it is something I am not interested in adding to the code. It relies on values that are not all known, may change and above all it is related to a recent feature that might change drastically. I appreciate the help, but as I said it will stay as it is for now.

**Comment by q1k** [comment]
OK, you're the boss.

But I can't seem to make it work as a userscript.
Can you see what's wrong?
http://pastebin.com/axZAbBMn

**Comment by Corruptinglyneedful** [comment]
My take on it is, that we do not need hovercards or annotations.  It's just a way to have more ads shoved in our faces.

**Comment by ParticleCore** [comment]
@q1k I am sorry, only saw your reply today.  This issue tracker is not the right place for this kind of thing, but from a quick look it seems you are telling jQuery to listen for a click on an element (`.ytp-menuitem`) but you are not making sure if the element exists when you are registering that instruction to jQuery. So what is probably happening is that when it runs, that element does not exist yet so it fails to listen for any clicks on it.

Regarding the endscreen cards, I have decided that I will revert the change on the next version update. Too many videos are relying 100% on this new type of endscreen resulting in strange endscreens when they are removed.

I will still try to find a better alternative, such as disabling click interaction as q1k suggested, but better implemented. If that doesn't happen with the next update then the new cards will return until I find a better solution.

**Comment by Corruptinglyneedful** [comment]
Glad I read this.

I won't be updating.

I don't care about their stupid ads and hovercards.  It actually works just fine.  I'm having no issues on videos.  Everything is playing just fine and staying disabled, including hovercards.

I don't want Hovercards enabled, period.

**Comment by q1k** [comment]
> I will still try to find a better alternative, such as disabling click interaction as q1k suggested, but better implemented.

I'd appreciate that, thanks

**Comment by Corruptinglyneedful** [comment]
I don't get why this is such an issue, just toggle annotations on when you need them.  Works for me.

Seriously, don't want ads, flyouts, clicking, none of it.

If you want to turn it back on, give those of us that don't want that crap a way to disable it please.

That's all I ask.

**Comment by q1k** [comment]
Today I got annoyed for the last time I couldn't toggle the cards with a simple click on the "Annotations" button.
So I spent some time to create this small script. I know it's not the best way to achieve this, but it does work and gets the job done nicely.

http://pastebin.com/CCUzSfuu
