### ISSUE TITLE
YouTube Top Bar Still Present In Fullbrowser Mode

### ISSUE THREAD

**Issue by PXAbstraction** [ParticleCore/Particle#299]
Browser Name:  Chrome

Browser Version:  52.0.2743.22

Operating System: Windows 10 x64

Software Type: Extension

Software Version: 1.3.9

Problem Description: I was asked to post this issue here from the Chrome Web Store support section for YouTube Plus. In short: When in Fullbrowser mode, the top YouTube bar that has the logo, search bar etc. stays on top and can't be removed. This is particularly annoying when trying to watch a darker video. I've attached a screenshot of the issue.

Steps to reproduce: Open any video in Fullbrowser mode.

Additional details: See attached screenshot.

Thanks for your help! Keep up the good work!

**Comment by ParticleCore** [comment]
Hello, yes this is the correct place. Unfortunately there is no screenshot attached, could you try again?

**Comment by PXAbstraction** [comment]
Shoot, it didn't stick for some reason. Sorry about that! Here it is.
![youtube plus issue](https://cloud.githubusercontent.com/assets/20633413/17089460/0ddca3f2-51f5-11e6-95be-4bc88f9d9940.png)

**Comment by PXAbstraction** [comment]
Actually, right after I posted this, I believe I discovered the issue. I also use the TubeBuddy extension for managing my YouTube channel, which adds a button to the top bar. I disabled that extension and now Fullbrowser properly clears the bar. Well, that's annoying. :) I'll submit an issue with them as well.

**Comment by ParticleCore** [comment]
I was just about to suggest that another extension could be causing this, glad that you managed to work it out so quick. If you still have any trouble just let me know!
