### ISSUE TITLE
Have separate autoplay settings/toggles for playlists

### ISSUE THREAD

**Issue by Reposium** [ParticleCore/Particle#30]
Hi!

I want to have individual videos not autoplay, but for playlist videos to automatically start (different from the "playlist autoplay control" that load the page for the next video in the playlist. At the moment, this not possible since the autoplay setting applies to both. Is it possible to have separate setting for each type of video?

Thanks.

p.s. On the other hand, I love how easy it is to toggle the setting without having to go into the full settings menu - those small things really add up and make this an awesome addon. Keep it up!

**Comment by ParticleCore** [comment]
I was going to say that it was for that exact reason I added the autoplay on the fly, until I read your P.S.

Thanks for the support!

**Comment by HifeFish** [comment]
I came here to ask pretty much this. At the moment it seems the global autoplay option and the autoplay button on playlists seem to be working independently of each other:
- global autoplay changes whether a video will start playing when the page is opened
- playlist autoplay changes whether the next video of the list will be opened
This means when global autoplay is disabled and playlist autoplay enabled, the next video page will load, but the video will not start playing.
Unless the "autoplay on the fly control" mentioned here is a different thing I've missed, I currently have no way of continuing playlists automatically, but not autoplaying videos on load.

What I definitely never want to autoplay, are videos on a channel page or embedded on a different page altogether.

**Comment by ParticleCore** [comment]
@HifeFish I have already explained why it behaves the current way in https://github.com/ParticleCore/Particle/issues/123#issuecomment-153432345

>In short, if users want the playlist to change to the next video but not have the video playing automatically they can't if I change it to the way you want because this option would not exist. They would be forced to have playlist autoplay on and playing the videos automatically with no alternative other than playlist autoplay off.

Regarding the channel video having independent autoplay control, I have not find it useful for me so far.
Regarding embedded videos, YT+ is only supporting videos in the YouTube pages, there are no intentions for external or embedded videos support.

**Comment by HifeFish** [comment]
@ParticleCore The comment linked in the comment you linked (https://github.com/ParticleCore/Particle/issues/48#issuecomment-125728945) showed me the "global autoplay on the fly control" that I was missing. That should work for me for now. Thank you.
