### ISSUE TITLE
Feature: Up Next

### ISSUE THREAD

**Issue by E-RELevant** [ParticleCore/Particle#300]
Let me start by saying thanks a lot for the amazing script which contains so much!
"Autoplay" feature is great, but many times when I start to play a "playlist" of uploads, or even just playing some music videos through YouTube, it has its "Up Next" feature: http://image.prntscr.com/image/fe4253df42af4a439da760c188245b86.png

It would be great if, instead of waiting these 15 seconds between the ending of the current video to the next one, you'll be able to skip this time and go straight away to the next one ("Up Next"), as "Autoplay" mode allows you to do.

I hope what I have requested is possible and really appreciate any help you can provide.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by mauriciocolli** [comment]
I think this feature is useful to me, so I decided to implement:
https://github.com/mauriciocolli/Particle/commit/52d3f1fcc4721cf27561d1c1c126b4a13e4576d3
If you like I can open a pull request

**Comment by E-RELevant** [comment]
Would appreciate it! Thank you! is there any way in which I can add the edited code to the offical script?
