### ISSUE TITLE
[FF Extension]Lost all settings/blacklist after 1.4.2 update (08/08)

### ISSUE THREAD

**Issue by rscm** [ParticleCore/Particle#301]
**Browser Name:** Firefox Developer Edition 64bits

**Browser Version:** 50.0a2 (2016-08-07)

**Operating System:** Windows 10 64bits

**Software Type:** Greasemonkey [Anti-Adblock Reek], InlineDisposition, InstaDown, Stylish, Ublock Origin, User Agent Switcher, Youtube Plus

**Software Version:** 1.4.2

**Userscript Manager:** I'm using the extension version

**Problem Description:** Lost all settings and blacklist after the extension got updated

**Steps to reproduce:** Install previous version, define some settings in Youtube. Update extension. Check if setting still exists.

**Additional details:** none

---
**Comments:** I'm going to try the script version. I don't like to have to redo all the settings, specially the blacklist. I asume that the script version should be better in ths area than the extensión.

**Comment by abc9987** [comment]
Same here! Automatically updated on 07th august, now all settings and blacklist are gone ):

**Comment by ParticleCore** [comment]
I am really sorry for this situation, I noticed the same a few hours ago when I returned to the normal setup and noticed everything was gone. Unfortunately the settings from the previous add-on did not carry during migration to webextension, fortunately the same settings are saved in a file which theoretically is intact with everything you need to restore the previous settings, as well as the precious blacklist.

To find your previous settings head to:

`C:\Users\<your user name>\AppData\Roaming\Mozilla\Firefox\Profiles\<your firefox profile>\jetpack\particle@particlecore.github.io\simple-storage`

And there should be a file named `store.json`, simply open it using any text editor, copy all the text and import them into the updated add-on via its settings menu.

For now this will have to do (which is a horrible workaround, but at least the settings are not lost) and I will work on making this automatic with a version update.

Thanks for letting me know and I apologize again for this, I was not expecting something like this would happen.

**Comment by ParticleCore** [comment]
It looks like this unfortunate situation was unavoidable, Mozilla does not provide any method for data migration when moving from previous add-on to webextension:

https://bugzilla.mozilla.org/show_bug.cgi?id=1214790

https://discourse.mozilla-community.org/t/updating-users-from-sdk-based-extension-to-webextension/9974

For this reason the only viable solution is the one I presented. I will make a cleaner tutorial to instruct the add-on users on how to migrate their settings to the new version, and link it on a new version for the next week or so to give most users enough time to become aware of this change and what they can do to restore their settings if they want to.

And this only affects Firefox webextension, the other versions are not affected by this (userscript and Chrome extension).

**Comment by ParticleCore** [comment]
I've added a simple warning link to instructions on how to restore previous settings. The guide can be found here: https://github.com/ParticleCore/Particle/wiki/Restore-settings

Let me know if you were able to import your settings with success.

**Comment by rscm** [comment]
Thank you and thanks for your work
