### ISSUE TITLE
Missing Button in video upload overview

### ISSUE THREAD

**Issue by TomPiXX** [ParticleCore/Particle#307]
I'm missing the pop-out button in the video overview of a channel.

![14-08-_2016_01-27-16](https://cloud.githubusercontent.com/assets/9993839/17646160/5984a79a-61be-11e6-8ab8-f254171e9a00.jpg)

**Comment by ParticleCore** [comment]
This happens for any channels, will push a fix with the next update.

**Comment by ParticleCore** [comment]
The channel videos should now have the pop-up button available, let me know if it works well for you too.

**Comment by TomPiXX** [comment]
Thanks, mate! It's working again.
