### ISSUE TITLE
Incompatibility with /shared URLs

### ISSUE THREAD

**Issue by Sukigu** [ParticleCore/Particle#308]
**Browser Name:** Firefox

**Browser Version:** 51.0a1 (2016-08-14)

**Operating System:** Windows 10

**Software Type:** Userscript

**Software Version:** 1.4.7

**Userscript Manager:** Greasemonkey

**Userscript Version:** 3.9beta2

**Problem Description:** YouTube + doesn't work with YouTube's /shared URLs. I came across one today, though I don't know how they're created.

**Steps to reproduce:**

1. Visit https://www.youtube.com/shared?ci=lB1Lk21WVTs with YouTube + enabled.
2. The video doesn't load.

**Comment by ParticleCore** [comment]
I was not aware of such type link, don't know if it will be possible to extend compatibility for it but I will try.

**Comment by ParticleCore** [comment]
Looks like this is a feature from the YouTube app, I believe it shouldn't be accessible on desktop and instead a redirect was suppose to occur, at least that is how something like this is suppose to work. There are a lot of incompatibilities with YT+ on that new page so for the time being the solution will be a redirect to the video itself, there's nothing important in that page that won't be available on the video page directly.
