### ISSUE TITLE
Feature Request: Additional Title

### ISSUE THREAD

**Issue by TomPiXX** [ParticleCore/Particle#312]
Hey,

I'm wondering if it would be possible to add a keyword behind the video title in the popout-window.
Why? That would give us the possibility to handle this window with scripting tools like AutoIt or something similar.
For me I want to keep it always on top and starting at a specific position.

Maybe you could add something like " - Popout-Player" or something like that?

Thanks for your great work!

Regards
Tom

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
