### ISSUE TITLE
[Improvement] Fullbrowser when window is small

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#313]
When in `Fullbrowser Mode` and the window is small (width < 640px, conflict with other rule) the searchbar appear:

![capture](https://cloud.githubusercontent.com/assets/13389907/17721619/fbcf3c0a-6401-11e6-87d6-6d1a10299458.PNG)

EDIT: A simple fix:
```
.part_fullbrowser div#movie_player{
  top: 0 !important;
}
```

**Comment by ParticleCore** [comment]
It's a bug, it should be behaving as you said. Will push the update for userscripts as soon as possible, but for the add-on and extension I will wait 2 days to see if there's any other change needed besides this one.

**Comment by ParticleCore** [comment]
The change for the userscripts is already live, if you are using the userscript version all you need to do is press Ctrl + F5 in a YouTube page. For the other versions the release will be made in about 2 days.

**Comment by mauriciocolli** [comment]
It's fixed, thanks!
