### ISSUE TITLE
youtube+1.4.9

### ISSUE THREAD

**Issue by Jason4774** [ParticleCore/Particle#316]
youtube+ is conflicted with theater mode,please fix it ,thanks.
![image](https://cloud.githubusercontent.com/assets/19594338/17879375/21159c44-6924-11e6-9d10-8123693c50ba.png)

**Comment by ParticleCore** [comment]
Please follow the instructions for reporting a problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Jason4774** [comment]
I do it before,I close the youtube+,it become normal
![image](https://cloud.githubusercontent.com/assets/19594338/17879427/7f9b072c-6924-11e6-8a92-d483a4662706.png)
and I open the same website in IE ,it's also normal.
![image](https://cloud.githubusercontent.com/assets/19594338/17879453/a95cf41c-6924-11e6-8b1f-1cf78185a534.png)

so, please fix it.thank you.

**Comment by ParticleCore** [comment]
I still don't know what the problem is, it could be another extension causing a conflict with YT+, it can be anything, all you showed me was how YouTube looks normally, there isn't even the problem shown in those pictures.
Please follow the instructions otherwise I will have to repeat them again here.

**Comment by ParticleCore** [comment]
I see you added a new picture to your first post showing the problem. I don't have it happening to me so I ask again that you follow the troubleshooter to confirm that this is limited to YT+

Disable all extensions (all of them, not just a few) and userscripts, except YT+. Restart the browser and see if the problem still persists.

**Comment by Jason4774** [comment]
sorry,I show you again.
please wait

**Comment by ParticleCore** [comment]
I will be waiting for your results. By the looks of it I suspect it is another extension or userscript that is conflicting with YT+, which is why it is important to follow the troubleshooting and find out whether the problem is really with YT+ or not.

**Comment by Jason4774** [comment]
https://drive.google.com/open?id=0B4JqQmSXEl47Y2stVnNHQVZHMGM
this is  a  gif picture

**Comment by ParticleCore** [comment]
I cannot access that file without an account, please post it here or on a public hosting website like imgur or gyazo.

**Comment by Jason4774** [comment]
http://7xnarc.com1.z0.glb.clouddn.com/YT+.gif
sorry.I am in china.

**Comment by ParticleCore** [comment]
Thanks for the gif, but in the future don't post such large gifs, the one you posted was over 70MB, use a video format instead for such large recordings.

From what I could see there were no conflicts with theater mode, the YouTube layout was working as expected. Remember that you have an option that modifies that page layout (which may cause the video to become larger than normal) which is called Fit to page in theater mode: https://github.com/ParticleCore/Particle/wiki/Features#fit_to_page

I am certain that you have that option enabled, causing the player to become abnormaly large which is not ideal for normal lapop size experience. You can either turn that feature off or reduce the max width the player can take: https://github.com/ParticleCore/Particle/wiki/Features#fit-to-page-max-width

Let me know if that fixed your problem.

**Comment by Jason4774** [comment]
no,it has a problem ,you cannot see it ? I already reset YT+ before.if I open the YT+,and then I　open the  theater mode,the hight of the video is BIGGER than normal.you can't see it ?please try it again.

PS：I use my sister's computer,so I wouldn't use my software to record a video for you.sorry.

**Comment by ParticleCore** [comment]
The height of the video is bigger than normal because `Fit to page in theater mode` is enabled.

Here is mine with that option turned off:

![ss1](https://cloud.githubusercontent.com/assets/9222661/17885199/a90672b8-690b-11e6-884a-eba8e7eb39c0.png)


And turned on:

![ss2](https://cloud.githubusercontent.com/assets/9222661/17885203/ae2a96b6-690b-11e6-829f-49d49c8ae8be.png)


Resetting the YT+ settings does not turn off all of the settings, it simply puts YT+ to its initial state which has a few options enabled, one of them being that option specifically (which in hindsight I should remove from default state).

Go to the YT+ settings, turn that feature off and try again.

**Comment by Jason4774** [comment]
![image](https://cloud.githubusercontent.com/assets/19594338/17887243/27c65bbc-6958-11e6-93d2-511802db77ca.png)
I closed this,it become normal,thank you for your reply.and sorry for wasting your much time.

**Comment by ParticleCore** [comment]
There is no problem, thank you for providing valuable feedback on what could have been a bug.

**Comment by Jason4774** [comment]
can you tell me why the two tabs are shorter than others?

**Comment by ParticleCore** [comment]
If I understand you correctly, you are asking about pinned tabs: http://lifehacker.com/5422014/make-google-chrome-open-with-permanently-pinned-tabs

When you pin a tab it will always open that tab again and whatever contents it last had every time you open your browser.

You can also do the same with Firefox.

**Comment by Jason4774** [comment]
Yes，thanks

**Comment by Jason4774** [comment]
I suggest that the next YT+ version,
![image](https://cloud.githubusercontent.com/assets/19594338/17932833/6991ac62-6a44-11e6-8503-0637bc385354.png)
i suggest remove "Fit to page in theater mode" from default state.and I　think that it's Not applicable for us.

**Comment by Jason4774** [comment]
YT+ is my favorite script. thank you

**Comment by ParticleCore** [comment]
I already said I would remove that feature from the list of features that are enabled by default, it is right in the text you quoted. The next version will not have it enabled by default.
