### ISSUE TITLE
Advanced options cover up video title

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Particle#317]
With some long video titles, the advanced options buttons can partially obscure the title.

For example here: https://www.youtube.com/watch?v=VTqQ6ZgjpNk

![snag 2016 08 23 02 23 58](https://cloud.githubusercontent.com/assets/5490615/17887012/448dcc00-68d9-11e6-9a84-079f5b78f824.png)

Options must be collapsed to see the full title:

![snag 2016 08 23 02 24 06](https://cloud.githubusercontent.com/assets/5490615/17887013/45ab4aea-68d9-11e6-9990-24fd8c54ab65.png)

-----

A suggestion is to maybe move the buttons to the same row as the like/dislike where there is enough empty space for them.

![snag 2016 08 23 02 24 17](https://cloud.githubusercontent.com/assets/5490615/17887050/7a5eac0a-68d9-11e6-9cfa-7b006ce72dfe.png)

**Comment by ParticleCore** [comment]
This behavior is intended and for the moment placing on the suggested location would not only conflict with a lot of other extensions as well as not work correctly when the YouTube buttons on the left have their labels visible. For the moment it will stay as it is.

If you wish to read the long title without having to close the advanced options you can simply put your mouse over the title and the full text will be shown on the tooltip:

![ss](https://cloud.githubusercontent.com/assets/9222661/17887426/f56ce07e-6915-11e6-8605-64f473012d4e.png)
