### ISSUE TITLE
Live streams are not working when DASH is disabled

### ISSUE THREAD

**Issue by Xima** [ParticleCore/Particle#321]
Browser Name: Firefox

Browser Version: 48.0.2

Operating System: Windows 10

Software Type: Add-on

Software Version: 1.4.9

Userscript Manager: Greasemonkey

Userscript Version: 3.9

Problem Description: Live streams are not working when DASH is disabled ( Player says : Your browser does not currently recognize any of the video formats available. )

Steps to reproduce: Disable DASH in  YT+ settings and try to play a live stream

Additional details: Re-enabling DASH solve the issue. Maybe YT+ should reactivate DASH only for live stream

**Comment by ParticleCore** [comment]
With the next version I will just remove the DASH-off feature completely, at this stage I don't find it useful any more and the benefits (which appears to no longer exist) are no longer worth the problems it brings.

**Comment by Xima** [comment]
I think it's useful to watch good quality with not so good internet speed ! But I understand if it brings too much problems.

**Comment by thegrandpow** [comment]
So you are saying it's not possible to detect if the video is a livestream and just ignore dash-off ?

**Comment by ParticleCore** [comment]
@thegrandpow It is very possible and no, I never said anything like that.
