### ISSUE TITLE
Can the theater mode be set as default?

### ISSUE THREAD

**Issue by 07416** [ParticleCore/Particle#326]
YouTube Center had this feature, when opening a video page the the theater mode will be used as default. No need to click the view button.

**Comment by ParticleCore** [comment]
YT+ has a memorize feature which restores whatever your last theater mode you had the last time you changed it: https://github.com/ParticleCore/Particle/wiki/Features#remember_mode

**Comment by 07416** [comment]
@ParticleCore YT settings don't when I clear cookies, I dump cookies when I close my browser. Would be nice to have this option in your script.

**Comment by ParticleCore** [comment]
The settings are independent of your cookies, YT+ applies the theater mode automatically if it was the last mode being used and the feature is enabled.
