### ISSUE TITLE
Option to disable YouTube auto-buffering

### ISSUE THREAD

**Issue by 07416** [ParticleCore/Particle#327]
YouTube Center had this feature, very useful for saving bandwidth: https://github.com/YePpHa/YouTubeCenter/wiki/Features#Prevent_AutoBuffering
No data was loaded before playing, different from video autoplay.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Particle/releases/tag/1.5.0

**Comment by ParticleCore** [comment]
>No data was loaded before playing, different from video autoplay.

How is that different from disabling autoplay? It also does not buffer the video unless you hit play.

**Comment by 07416** [comment]
@ParticleCore I'm very sorry, I've been using Firefox's autoplay setting `media.autoplay.enabled`. Feel free to add `invalid` label.

Sorry again, I have seen that info about feature requests, but absolutely forgot. Your work with this script has been stellar so far, hopefully development doesn't take too much of your time.

**Comment by ParticleCore** [comment]
It's ok, it is a feature that does not exist yet so it will remain labelled as such so that when I want to add a new feature I can quickly find all feature requests.
