### ISSUE TITLE
Top two rows are lost

### ISSUE THREAD

**Issue by roy192** [ParticleCore/Particle#329]
**Browser Name:** Firefox
**Browser Version:** 48.0.2
**Operating System:** Windows 7 Ultimate (x64)
**Software Type:** Userscript
**Software Version:** 1.5.0
**Userscript Manager:** Greasemonkey 
**Userscript Version:** 3.9
**Problem Description:** The video's top two rows of pixels are hidden under the masthead, which seems to be about 3 pixels taller than without the script enabled (see pictures below). This only happens in theatre mode.
**Steps to reproduce:** Turn the script on, make sure video is in theatre mode, and check the video's visible height.
**Additional details:** This also happens on chrome (48.0.2564.116 m).
**Pictures:** 
Without script, with video selected
![ytpbugsmalls](https://cloud.githubusercontent.com/assets/6928846/18311332/001ec682-7504-11e6-95b5-02bf97288534.png)
With script, with video selected
![ytpbugsmallps](https://cloud.githubusercontent.com/assets/6928846/18311331/00145576-7504-11e6-844e-8051e269f3b3.png)
Without script, nothing selected
![ytpbugsmall](https://cloud.githubusercontent.com/assets/6928846/18311330/fff7a728-7503-11e6-9db4-deb838fc63eb.png)
With script, nothing selected
![ytpbugsmallp](https://cloud.githubusercontent.com/assets/6928846/18311329/ffe0d976-7503-11e6-9457-2560b8698e4f.png)

**Comment by ParticleCore** [comment]
Thanks for bringing this up, the changes are already live for Userscript versions. To update it simply go to any YouTube page and press Ctrl + F5. Let me know if this is fixed for you too.

For the other versions this fix will be released in 2 days.

**Comment by roy192** [comment]
That fixed it, thanks.

**Comment by q1k** [comment]
Now the floater player is a few pixels lower than it was. before

**Comment by ParticleCore** [comment]
@q1k the changes made were to the YouTube logo only and nothing else: https://github.com/ParticleCore/Particle/commit/4c33ee19b7be04139c357b5672c948090dc0e99e

Your problem is a different problem, please open a new issue and include the necessary information to identify the problem.

**Comment by ParticleCore** [comment]
@q1k Are you referring to the floater not sticking exactly to the top bar where the search is? If so that's because I haven't yet released the updated Javascript code, only the CSS style has been changed.

**Comment by ParticleCore** [comment]
Version 1.5.1 comes with a fix for this problem as well the correct height offset in the floating player, let me know if it is working well for you too.

**Comment by q1k** [comment]
Yes, it's good now.
