### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by undido** [ParticleCore/Particle#330]
Browser Name: Fire Fox

Browser Version: 48.0.2

Operating System: Windows 10

Software Type: Add-on

Software Version: 1.5.0

Userscript Manager: none

Userscript Version: none

Problem Description: Blacklisting button is missing and blacklisted youtubers are appearing.

**Comment by ParticleCore** [comment]
Make sure you have not disabled the blacklist option in the YT+ settings: https://github.com/ParticleCore/Particle/wiki/Features#blacklist_on

If it is enabled then please follow the troubleshooting guide as it was requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you still have problems please follow the previous instructions.
