### ISSUE TITLE
Script not working in Chrome

### ISSUE THREAD

**Issue by halcion** [ParticleCore/Particle#331]
in fact. it never has. please consider supporting it in the future please and thank you

**Comment by ParticleCore** [comment]
Please provide more information as it was requested before you posted the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

The userscript and extension have always worked and still are working on the most recent Chrome version  42 and above.

**Comment by LuaTenshi** [comment]
Using this script in chrome. Found it yesterday actually. Works perfectly so far with Tampermonkey.

**Comment by ParticleCore** [comment]
I will close this for now, if you still have problems please follow the previous instructions.
