### ISSUE TITLE
Video Playlist by Channel

### ISSUE THREAD

**Issue by digitalattorney** [ParticleCore/Particle#335]
Thank you for explaining the other day why you're "Enable subscription playlist" (#333) feature can only load twenty videos. I have another similar question.

If I go to a Channel, then click Videos, I can see all the videos they have. They are listed from newest to oldest. Do you have, or can you make, a similar playlist feature like the "Enable subscription playlist" so that I can limit the playlist to only that Channels vdeos?

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by ParticleCore** [comment]
For what you need you don't even require any extension. While in the channel you wish to watch the videos you can find the channel ID (usually on the location bar) by right-clicking the channel name.
That id is usually something like this "UCxxxxxxxxxxxxxxx", copy that value, replace the "UC" with "PL" and add it to the following link:

`https://www.youtube.com/playlist?list=PLxxxxxxxxxxxxxxx`

This will open the playlist containing all the public uploads of that channel.
