### ISSUE TITLE
"Memorize audio volume" disabled setting not honored

### ISSUE THREAD

**Issue by BlueNinja0** [ParticleCore/Particle#337]
Browser Name: Firefox

Browser Version: 48.0.2 (64-bit)

Operating System: Windows 10 (64-bit)

Software Type: Extension

Software Version: 1.5.2

Problem Description: "Memorize audio volume" disabled setting not honored

Steps to reproduce: 
1) Reduce volume on a video.
2) Refresh video page or load another video.
3) Video retains the previous volume, even though it should be back at full volume (I suppose) because the option is disabled.

**Comment by ParticleCore** [comment]
YouTube itself memorizes in cookies a few player settings changed by the user. Disable YT+ and you can see that YouTube retains your previous volume level, unless you clear your cookies.
The feature allows you to memorize the volume level even if the cookies are deleted, disabling it never does not mean that the volume level would not be memorized.

**Comment by BlueNinja0** [comment]
I've read the troubleshooting guide and I am aware YouTube might be saving the volume information independently of YT+
But I assumed that by having the setting disabled would force YouTube to forget the volume, otherwise, in a normal situation, the setting serves no purpose. Perhaps a more in-depth description in the wiki would help, or forcing YouTube to forget the volume if the setting is disabled would be even better.

**Comment by ParticleCore** [comment]
This setting, and a few others like memorize player mode, help users maintain their player settings under privacy enabled environments (incognito mode) or to keep their choices after the setting expiration date is reached.
But I agree that it will benefit from a more detailed explanation and I will immediately do this.

**Comment by BlueNinja0** [comment]
Alright. Thank you for your explanation and for this amazing add-on!
