### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#339]
Is there a code for Stylish for the Youtube video controls to always keep showing? :)

**Comment by ParticleCore** [comment]
This issue tracker is for issues related to YT+. For Stylish questions it is best to make them on Stylish dedicated forums.

**Comment by GKid94** [comment]
Ok thx

**Comment by q1k** [comment]
https://greasyfork.org/en/scripts/11485-youtube-new-ui-fix
Always show the controls

**Comment by GKid94** [comment]
@q1k It shows and red "X" when i put those commands and it says:
-Expected LBRACE at line 1, col 4
-Unexpected token '(' at line 1, col 4
-Expected IDENT at line 1, col 14
