### ISSUE TITLE
[Grid Layout] Livestream thumbnails are unaligned

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Particle#34]
This has been bothering me for a while now.
A picture is easier to illustrate:
![grid](https://cloud.githubusercontent.com/assets/6627739/8382555/4cbaf25a-1c2b-11e5-87f0-2e516596278e.png)

I've tried changing the CSS a bit to get it more in-line with the video thumbnails but it doesn't quite look good, so I was thinking if you could try it yourself.

**Comment by ParticleCore** [comment]
I haven't encountered that yet, it is suppose to be hidden while in Grid layout, will try to fix it.

**Comment by SW1FT** [comment]
Also, when the livestreams are LIVE, it appears LIVE NOW instead. `.yt-lockup-badges` and `.yt-lockup-meta` need to be hidden. (I'm sure you know this already though).

**Comment by ParticleCore** [comment]
The live now badge should already be hidden, does it show when you are searching or in your subscription?

**Comment by SW1FT** [comment]
Yes, it does show.

**Comment by ParticleCore** [comment]
But where does it show? In the search results or in your subscription list?

**Comment by SW1FT** [comment]
Subscription list.

**Comment by ParticleCore** [comment]
Thanks for the report, the fix was on time for the new release. You should be able to update now to the version 0.2.7
