### ISSUE TITLE
"YouTube logo redirects to subscriptions" not working

### ISSUE THREAD

**Issue by Stechi** [ParticleCore/Particle#342]
Browser Name:  Mozilla Firefox

Browser Version: 48.0

Operating System: Ubuntu 14.04

Software Type: Add-On

Software Version: 1.5.2

Problem Description: With "YouTube logo redirects to subscriptions" it still redirects  to Home

Steps to reproduce: Click Youtube-Logo

Additional details: It may be happening because of the #voteIRL stuff

**Comment by ParticleCore** [comment]
I had already accounted for this in the previous logo changes, but they decided to leave something behind again. Will update this as soon as I can.

**Comment by ParticleCore** [comment]
This should be fixed in version 1.5.3, let me know if it works for you too.

**Comment by Stechi** [comment]
Needed sometime until the addon got updated for me,
but now it works. 
Thank you very much
