### ISSUE TITLE
Support domain gaming.youtube.com

### ISSUE THREAD

**Issue by XCanG** [ParticleCore/Particle#345]
Currently plugin does not work at https://gaming.youtube.com/
Can you add script to this subdomain?

Browser Name: Firefox and Chrome
Browser Version: Firefox/52.0 and 53.0.2785.143 m
Operating System: Windows 10
Software Type: Userscript
Software Version: _see Userscript Version_
Userscript Manager: Tampermonkey
Userscript Version: v4.2.5291 by Jan Biniok (Firefox) and v4.1.10 by Jan Biniok (Chrome)
Problem Description: _see above_
Steps to reproduce: Go to https://gaming.youtube.com/ and open any video or stream.

**Comment by ParticleCore** [comment]
YT+ will not support the Gaming version of YouTube. It is barely used, I never use it and it would require a totally unique version of YT+ for it to work correctly, which would be the same as having to maintain two scripts instead of one.
