### ISSUE TITLE
playlist controls for next and prev video are hidden

### ISSUE THREAD

**Issue by stesachse** [ParticleCore/Particle#346]
**Browser Name:** google chrome
**Browser Version:** 53.0.2785.143 (64-bit)
**Operating System:** Linux 4.7.4-200.fc24.x86_64 Fedora 24 (Workstation Edition)
**Software Type:** extension
**Software Version:** 1.5.3

**Problem Description:** playlist controls for next and previous video are missing. there are only buttons for repeat and shuffle.

**Steps to reproduce:** open a new incognito window and got to this [playlist](https://www.youtube.com/watch?v=-8_2Ln0NkGA&list=PLVLumybx6MkdR7Zk6o15fxzKIaEFckGea)

![screenshot-youtube-playlist-controls-for-next-and-prev-video-are-hidden-2016-10-01-17-39-27](https://cloud.githubusercontent.com/assets/6449307/19015117/36dc4e44-87fe-11e6-8010-b37ed5303711.png)

**Additional details:** the buttons for prev and next are still there but hidden and in another div. here is a snippet script for chrome that unhides and moves the buttons after the shuffle button

```javascript
(function(){
    /* unhide the links to prev and next */
    for (var a of document.querySelectorAll(
            '.playlist-behavior-controls > a.hid')) {
        a.classList.remove('hid');
    }

    /* move the links behind the shuffle-button */
    var new_parent = document.querySelector(
        '#watch-appbar-playlist > div > div.playlist-header > div.control-bar.clearfix > div.playlist-nav-controls'
    );
    var old_parent = document.querySelector(
        '#watch-appbar-playlist > div > div.playlist-header > div.control-bar.clearfix > div.playlist-behavior-controls'
    );

    if (new_parent === null || old_parent === null) {
        return false;
    }

    /* get the next button after the shuffle-button and insert before this
       button. or use null as reference and append to the end */
    var reference = new_parent.querySelector('button.shuffle-playlist + button');

    /* finally move all nodes to the new parent */
    while (old_parent.childNodes.length > 0) {
        new_parent.insertBefore(old_parent.childNodes[0], reference);
    }

    return true;
})();
```

thanks for your work

**Comment by ParticleCore** [comment]
This has nothing to do with YT+, it is the YouTube website itself that has hidden those buttons on purpose a long time ago.
