### ISSUE TITLE
Retina icons

### ISSUE THREAD

**Issue by valera5505** [ParticleCore/Particle#347]
Browser Name: Safari
Browser Version: 10.0
Operating System: macOS
Software Type: Userscript
Software Version: 1.5.3
Userscript Manager: Tampermonkey
Userscript Version: 4.2
Problem Description: I'm using Macbook Pro Retina and icons (save and settings) of Youtube+ looks blurry, can you increase resolution of icons?
<img width="336" alt="2016-10-01 19 35 24" src="https://cloud.githubusercontent.com/assets/3050013/19015635/766a2330-8810-11e6-806a-eb3407fde31b.png">
Steps to reproduce: just open youtube on HiDPI screen

**Comment by ParticleCore** [comment]
I don't have any retina screen, but I will consider converting them into SVG format which should improve this situation.

**Comment by valera5505** [comment]
It would be really nice, thank you.

**Comment by ParticleCore** [comment]
@valera5505 YT+ version 1.5.7 is now using SVG only icons, let me know if it is better for you now.

**Comment by valera5505** [comment]
Now it looks sharp. Thank you!
