### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by delicacy1** [ParticleCore/Particle#348]
Hi,

I discussed with you about a past issue where i can't update yt+ after 1.4.0 or it breaks functions,
unfortunately, i have other issues, but i had mainly used it for a function, it would be nice if you could provide me the part of the script in yt+ 1.4.0 that makes all disordered & mixed urls per video appear like one link.

**Comment by ParticleCore** [comment]
I am afraid that I don't know what you are asking for, could you please be more specific?

**Comment by delicacy1** [comment]
A part of your yt+ script cleans garbage around youtube links.. which makes them 
openable using snaplink addons.

Exemple, this script i found, removes some extra parameters from YouTube video links,
it cleans them, so when i use snaplinksplus, to open several links in the background,
it doesn't either open needless links or bugs by not responding.

With that script below, it works for suggested links on the right, but not on videos 
that appear below the search box .. . tested with snaplinks plus. 

window.addEventListener("load", convertMyLinks($('a[class*="spf-link"]')), false);
if(document.readyState == "complete"){
	convertMyLinks($('a[class*="spf-link"]'));
}

function convertMyLinks(elemArray) {
	for (i = 0; i < elemArray.length; i += 1) {
		$(elemArray[i]).attr("href", elemArray[i].href).removeAttr('data-sessionlink').removeAttr('rel').attr('class', $(elemArray[i]).attr('class').split(" spf-link ")[0]);
	}
}

**Comment by delicacy1** [comment]
that part of your script, plus the autoplay button & default behavior removal are 2 crips i'd need to keep from yt+

if i had them in two separate scripts, it would be nice

**Comment by ParticleCore** [comment]
I'm sorry but I don't have anything in YT+ that cleans YouTube links, I think what you mean is disable SPF. You can accomplish this just by blocking (with any ad-blocker or script-blocker) the `spf.js` file YouTube uses.

**Comment by delicacy1** [comment]
i don't think it's the cause of what ur addon does since i already have it & it does nothing:
@@||ytimg.com/yts/jsbin/$script
its an easylist filter, unrelated

**Comment by ParticleCore** [comment]
That filter rule at the start is to allow, not block: https://adblockplus.org/filter-cheatsheet#exceptions1

You need to block the file, not allow it.

If you don't think it's the cause and you don't want to confirm it by doing what I suggested then there is nothing else I can help you with.

**Comment by delicacy1** [comment]
![1](https://cloud.githubusercontent.com/assets/7744210/19025096/6e1fbcd6-8913-11e6-813b-4bd34b5d9e82.jpg)
Without yt+ & in this case, snaplinksplus bugs & opens one link in the foreground instead
of opening the 3 in the background as tabs


![2](https://cloud.githubusercontent.com/assets/7744210/19025112/a2300670-8913-11e6-824b-8238ad19e1c3.jpg)
& here, with yt+ the three will open in 3 background tabs as expected because your script cleaned
the links..

**Comment by delicacy1** [comment]
let me try to disallow it then a min..

**Comment by ParticleCore** [comment]
There's no need, I already know what you are now talking about, this is what you need to do, or similar to it:
````js
click_title = document.querySelector(".yt-uix-tile");
while (click_title) {
    click_title.classList.remove("yt-uix-tile");
    click_title = document.querySelector(".yt-uix-tile");
}
````
https://github.com/ParticleCore/Particle/blob/master/src/Userscript/YouTubePlus.user.js#L1077

**Comment by delicacy1** [comment]
ok, it did it, but i haven't applied it to just "youtube", do you think it could cause me issues,
& that script could get rid of different urls that i select for a same selected element, in other websites ?

there are two last other scripts from yt+ that i'd like:

-the floating video that follows me when i scroll down to read lyrics in text for ex..
&
please look at this:
https://greasyfork.org/en/scripts/22303-youtube-autoplay-off

**Comment by ParticleCore** [comment]
I am sorry but this is not a place for teaching others how to make userscripts or for userscripts requests, please use the appropriated userscript forums instead.

**Comment by delicacy1** [comment]
i had done it already..
https://greasyfork.org/en/forum/discussion/11808/x

**Comment by ParticleCore** [comment]
That script has been discontinued, it is clearly stated in its description. I already have limited time for this extension, let alone to teach others how to create userscripts. You will have to seek help from other people besides me.

**Comment by delicacy1** [comment]
that's why your previous comment was needless & silence is more respectuous & than egomania.
