### ISSUE TITLE
Problem on Fit to page in theather mode

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#349]
When the feature `Fit to page in theather mode` is enable, it sets the `max-width` even when the player is not on Theather mode:
![crop](https://cloud.githubusercontent.com/assets/13389907/19047794/b4e0f174-8979-11e6-9970-76a04dbdcb63.png)
_Here i'm tested with the_ `Fit to page max width: 300px`

And there's another problem, when exiting from settings, and changing the `Fit to page max width`, the layout of the player don't update, similar to the #304, but thats a minor issue

It happens on both Chrome 53.0.2785.143 and Firefox 49.0.1

**Comment by ParticleCore** [comment]
Nice catch, will try to push a fix as soon as I can. Regarding the other one, it is a matter of refreshing the page, not all settings can be applied live, but I will see if I can do something about it.

**Comment by ParticleCore** [comment]
Can you provide more details on that last one? I am having a hard time understanding what you mean, or I just can't replicate it.

**Comment by ParticleCore** [comment]
This should be fixed in version 1.5.4, if you are using the userscript version remember to press Ctrl + F5 to refresh the YT+ stylesheet. Let me know if both problems are solved for you as well.

**Comment by mauriciocolli** [comment]
Yes, its working now, thanks for the quick fix!
