### ISSUE TITLE
Small suggestion regarding "Hide video details"

### ISSUE THREAD

**Issue by Betsy25** [ParticleCore/Particle#35]
Right now, there's an option to either completely remove it or else have it open in the expanded state,
is it possible to have some collapsed state, so that it is not expanded by default, but the user still can if he wants to ?

**Comment by ParticleCore** [comment]
The default YouTube behavior is already like that, you have the "Show more" option with a short visible intro. The existing option is aimed at allowing users to have a more minimalistic YouTube layout. Unlike the comments, this section doesn't load resources when visible, so I don't find useful to have a redundant feature.

**Comment by Betsy25** [comment]
Really ? For some reason it always shows expanded by default, with the "Show Less" button below.

**Comment by ParticleCore** [comment]
Go to the YT+ settings > Video > Auto expand video description, is it enabled?

**Comment by Betsy25** [comment]
Duh!?!?

It was ! Darn, sorry again for my stupidity.

**Comment by ParticleCore** [comment]
No worries, as long as it works out then its alright.

**Comment by Betsy25** [comment]
@ParticleCore 
For not filling up with unneeded issue requests, is it possible to add a bit to the wiki what the "Blacklist" is about, right now, clicking the help icon opens the wiki, but nothing about the blacklist to be found.

**Comment by ParticleCore** [comment]
Can't believe I missed that one, the link should be directing to here instead: https://github.com/ParticleCore/Particle/wiki/Features#enable-blacklist

Will add that correction in the next version, thanks for letting me know!

**Comment by Betsy25** [comment]
Yeah, i thought something was right, cause right after I posted it somehow worked lol ?
That's why I removed the post just when you were replying :D

**Comment by ParticleCore** [comment]
Don't know what they changed, but it seems that now the images loading times are causing the anchor tag to not work properly, the page scrolls to the correct place, but once the images load they offset the page Y position and GitHub doesn't update to the correct place when everything has finished loading. Will try to contact them about this issue, if nothing changes I will try to find a better way of making it work.

**Comment by Betsy25** [comment]
Thanks again for the help @ParticleCore !

**Comment by ParticleCore** [comment]
No problem, but it seems like it won't be fixable so I will instead try to change the images into clickable links, this way the issue shouldn't occur and the page will weight less which will benefit people with slow internet or low monthly caps.

**Comment by ParticleCore** [comment]
Just wanted to leave an update regarding the wiki issue, it has been fixed. For future reference, the solution is to add the image size so that when the page first loads it already has the full height with the images before they load, this way it won't offset once they load since it already knows how much space they should take.

**Comment by Betsy25** [comment]
Works fine now. :+1:
