### ISSUE TITLE
Intent to split Blacklist and Ad-Blocker into standalone extensions

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#351]
Both features have been frequently sought and used exclusively, quite a few users only use the add-on for either, or both of those features only so it would make sense to convert them into individual extensions.

Having these features made into individual extensions would allow me to provide a more rich experience for all extensions. Blacklist and Ad-blocker would have more features and since YT+ would be lighter I might be able to implement new features, such as thumbnail preview (although YouTube is already testing their own), video statistics (likes, dislikes, comments disabled, etc.) and/or other interesting requests.

This is an intent, so these plans might or might not move forward.

**Comment by ParticleCore** [comment]
I will be adding here the features that I would like to implement in the future. The feature names are not permanent and may change in the future:

 - Thumb info
  - Shows the number of dislikes, likes the video has, if comments are disabled and the max quality

 - User flag
  - For the users that have their country visible, a flag of that respective country will be shown

 - Video keywords
  - Show the keywords the video is using

 - Thumbnail map ([previously deprecated feature](https://github.com/ParticleCore/Particle/wiki/Features#adv_seek))
  - When available, it allows the user to open a map with all the thumbnails in the video positioned according to their position in time. Clicking in one of them will jump the video to its specific time. This feature was already made in the past, but dropped due to too many problems.

**Comment by 07416** [comment]
How does the ad-blocking differ from using a general blocker extension such as uBlock Origin?

**Comment by ParticleCore** [comment]
@07416 When all adblockers failed, the one in YT+ never failed because it makes use of the YouTube api to control ads instead of relying on lists. Black screen player problems were also a problem that it never had and the dedicated channel white-listing is easier than going through semi-complicate rule based processes.

Most important of all, this is an alternative, a complement, not a replacement. Having something dedicated to one website typically works better than something that tries to work everywhere.

**Comment by ParticleCore** [comment]
This will be placed on hold until the material version is finalized.
