### ISSUE TITLE
Cinema Mode not working properly

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#353]
With the recent introduction of the CSS `contain` rule and its recent application on the video player (`contain: strict`), the dark area surrounding the player no longer works correctly.
Currently only happening on Chrome since it is the only browser that supports it.

**Comment by Eisys** [comment]
Bit of a random question, which is why I'm asking on a closed issue.

Just found out that Youtube has a built-in frame-by-frame feature. Using the comma and period keys.
I was wondering if there is a difference between the built in option and what youtube+ does? Perhaps YT+'s way is better in some ways?

**Comment by ParticleCore** [comment]
@Eisys Now I know what those keys do when not pressing the Shift key. Since last year I inspected their source code and saw these two key shortcuts, example:

````js
case 190:         // period key code
    if (c) {      // if shift key is pressed
        if (e.ia) // increase playback speed
            for (b = a.b.ni(), c = a.b.app.g.F, e = 0; e < b.length - 1; e++)
                b[e] == c && (d = b[e + 1], a.b.pi(d, !0), t5(a.g, d, !1), d = !0)
    } else        // if shift key is not pressed
        $5(a, 1), // skip one frame forward
        d = !0;
    break;
case 188:          // comma key code
    if (c) {       // if shift key is pressed
        if (e.ia)  // decrease playback speed
            for (b = a.b.ni(),  c = a.b.app.g.F, e = b.length - 1; 1 <= e; e--)
                b[e] == c && (d = b[e - 1], a.b.pi(d, !0), t5(a.g, d, !0), d = !0)
    } else         // if shift key is not pressed
        $5(a, -1), // skip one frame back
        d = !0;
    break;

// frame by frame function
$5 = function(a, b) {
    if (Q(nn(a.b), 4)) {
        var c = a.b.getVideoData().g;
        c && (c = c.video) && a.b.Ed(b / (c.fps || 30))
    }
}
````

https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js:formatted

I knew the comma and period keys assigned to something, but I could never understand what they did because they appeared to do nothing during my tests, so I assumed it was some sort of TV only feature. Now I understand that the reason for why they appear to do nothing is because they were skipping frames, which was not easy to detect without paying close attention.

As far as I can see there is almost no differences from YT+ version, the only difference is that with YT+ you can enter frame-by-frame mode during playback by pressing the combination keys, while YouTube's version requires that you pause the video before using frame-by-frame buttons.

I will be removing this feature in the future since it is pretty much redundant and to help people be used to YouTube shortcuts I will be placing a button in the console area which will show a list with all the YouTube shortcuts. This way most users will not be confused was to why the feature was removed.

Thanks for bringing this up to me. And you can make new issues for questions, which is better because it will help others find it if they have the same question.
