### ISSUE TITLE
Feature removal: Frame-by-frame

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#354]
In light of [recent information brought to my attention](https://github.com/ParticleCore/Particle/issues/353#issuecomment-252490204), the frame-by-frame feature is redundant, YouTube already had this feature natively.
For this reason it will be removed in the foreseeable future and in its place will be available a list with all the YouTube shortcuts to help facilitate this transition to the users that made use of this feature, and provide a better understanding of YouTube shortcuts in general.

Once this feature is removed users will have to use the comma and period keys to skip frames.

**Comment by q1k** [comment]
Well that's no enhancement.
I always liked that I could enter frame by frame straight from playing a video without having to pause it.

**Comment by ParticleCore** [comment]
@q1k I understand what you are saying, but this is a redundant feature. Besides, with `Player shortcuts always active` you can press Space to pause the video and skip frames almost as fast as before. This feature is at best a shortcut key changer that is occupying quite a portion of code unnecessarily, as well as maintenance taxing, removing it will provide more space for any new feature addition.

**Comment by MrGoatsy** [comment]
I am also having issues with this feature being removed, I really dislike having to press space to pause the video and then using `,` or `.` to skip a frame, could you add it again but then have an option to enable it?
