### ISSUE TITLE
Get css file url

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#356]
So today you have rolled out a new version, which breaks the icons on the older version.
I would like to continue using the old version but the problem is the missing icons.
What do I need to do to fix this while keeping the older version (1.5.6) of the userscript

**Comment by ParticleCore** [comment]
You will have to fork version 1.5.6 and use the stylesheet and sprite icons from your fork.
Stylesheet and sprite commits can be found here: 

https://github.com/ParticleCore/Particle/commits/gh-pages/images/sprite.png

https://github.com/ParticleCore/Particle/commits/gh-pages/stylesheets/YouTubePlus.css

**Comment by ParticleCore** [comment]
Also make sure you press Ctrl + F5 to download the most recent stylesheet, in case it hasn't updated itself, it might be the cause of the broken icons.
