### ISSUE TITLE
Frames skip

### ISSUE THREAD

**Issue by thegrandpow** [ParticleCore/Particle#359]
Hello, so today I opened youtube and all the yt+ icons were missing. So I checked for updates and installed the new version.
The problem being, I can no longer skip frame with the shift+arrow combo, which always worked!

**Comment by ParticleCore** [comment]
Yes, this is the result of a feature removal, which can be read here in more detail: https://github.com/ParticleCore/Particle/issues/354

In short, YouTube already had that feature implemented, making YT+'s version redundant. The YouTube shortcut keys are the comma and period keys to go back and forward one frame, respectively.

**Comment by thegrandpow** [comment]
The `,` and `.` are just too close to other buttons which do other things, like `L` (skip 10 seconds) or `/` which selects the search bar thus disabling shortcuts. It is far less convenient and very annoying.

I would very much appreciate it if you would keep the shift+arrow combo, which could enter frame by frame mode immediately without the video needing to be paused.

**Comment by ParticleCore** [comment]
Please read the linked issue which already covers your point and other points:

>This feature is at best a shortcut key changer that is occupying quite a portion of code unnecessarily, as well as maintenance taxing, removing it will provide more space for any new feature addition.

**Comment by thegrandpow** [comment]
Well it doesn't need a lot, just map the combo to the appropriate buttons, with the added bonus of being able to enter frame mode while video is playing.

**Comment by Azelef** [comment]
Sadly, when using an AZERTY keyboard, there is no period key ("." is written with shift+";"), making that shortcut unusable. I need to switch my layout whenever I want to use this feature. [This update broke my workflow !](http://xkcd.com/1172/) . That's probably more Youtube's problem than yours but it would be great to be able to change the shortcut keys.

**Comment by ParticleCore** [comment]
@Azelef I was finally able to get a hold of an AZERTY keyboard to try it out and I was able to use the frame by frame function as normal with a twist: don't use shift for the period key, use `;` instead and let me know if it works so that I can update the shortcut list.

Also let me know if there is any other problem similar to this that you might know of.

**Comment by Azelef** [comment]
Simply using ; doesn't work for me (Windows 8, Firefox 49). However, I tried with Internet Explorer, and it works there. Shift+; works in IE, but not in Firefox. Shift is needed to write numbers, but not to use the number shortcuts : è will send you to 70% of the video (and - to 60%). +and = don't seem to work either. So there are five missing shortcuts in Firefox and three in IE.

**Comment by ParticleCore** [comment]
Don't understand why it doesn't work in Firefox but works in IE with Shift pressed. Which AZERTY layout are you using? Belgian or French?

**Comment by Azelef** [comment]
French.
I meant that in IE, ";" did what "." was supposed to do and "shift+;" did what "shift+." was supposed to do.

**Comment by ParticleCore** [comment]
Ah, so it works like it worked with me in IE but not in Firefox. So it advances frames and increases playback speed as expected, but only in one browser. We can assume that either Firefox is not interpreting the keys correctly or something in Firefox is not working as it should. Make sure you are not using the Flash Player version in Firefox (just right click on the player and see if there is no "Adobe Flash Player..." at the end of the context menu.

Next step is to check if the browser is receiving the correct keycodes associated to your keys. Go to this website in IE and Firefox http://keycode.info/ and then press in that page the `;` key (no shift). If everything is right it should show the number 190 in both browsers.

**Comment by Azelef** [comment]
I got code 59, keycode.info says it is : "semicolon (firefox), equals". Looks like it's a problem with Firefox.

**Comment by ParticleCore** [comment]
That makes more sense now, you will have to find out what is causing Firefox to receive or interpret the keys incorrectly and fix the problem:

Now the remaining shortcuts you mentioned, the numbers work perfectly, but it's the same problem as the period key, don't use Shift. Try it in IE since Firefox is with the problem, let me know if it jumps to the according positions described in the shortcut list.

**Comment by ParticleCore** [comment]
As for the `=` and `-` only one of them works, the `=` but if you don't notice the subtitles increasing size when you press it then it's very likely they arlready are at their max size, so you have to go to the video player subtitle options and reset or reduce their size.

Unfortunately YouTube apparently has not accounted the `-` not working with AZERTY, this is their source code:

````js
case 187: // increases font size
    U4(this, "fontSizeIncrement", !1, !0) && (h = !0);
    break;
case 189: // decreases font size
    U4(this, "fontSizeIncrement", !0, !0) && (h = !0)
}
````

During my tests I could not find any AZERTY key that had a keycode of 189, but it does have the key for 187 which is the equal (`=`) key.

To correct this I would suggest that you'd report them this problem, go to the bottom of any YouTube page, click the "Send feedback" link and tell them that you can increase the subtitles/cc font-size with `=` but you can't decrease them with any key. Remember to mention that you are using an AZERTY keyboard. With some luck they will update their source code to include one key that works for that layout.
