### ISSUE TITLE
Static header option

### ISSUE THREAD

**Issue by snintendog** [ParticleCore/Particle#36]
just a pet peeve i have with headers taking up space on the screen when scrolling. 
Thank you for creating this Script it seems to be more stable to YTC right now and is shaping up to be a good replacement to YTC.

**Comment by ParticleCore** [comment]
I don't find this to be a useful feature, sorry.

**Comment by OdinGitDat** [comment]
Hi, if OP still wants to achieve this he can install the stylish addon, create a new style and use this:

@-moz-document domain(youtube.com) {

  #masthead-positioner, .appbar-guide-menu-layout {
    position: absolute;
  }

}

**Comment by snintendog** [comment]
odingitdat thank you for that but I kinda of already did that....still thanks.
