### ISSUE TITLE
Pop out windows not show video

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Particle#360]
Browser Name: (Chrome)

Browser Version: (53.0.2785.154)

Operating System: (Windows 10)

Software Type: (Tried both. Extension and Userscript on TamperMonkey)

Software Version: (1.5.8)

Userscript Manager: (Tampermonkey)

Userscript Version: (4.1.10)

Problem Description: (When pop-out windows opens video starts to play but screen is black, when i resize window video shows bottom of windows. If i resize enough it fit to windows. I can't make it small.)

Steps to reproduce: (Open Youtube play video, than click pop-out video button)

![aaa](https://cloud.githubusercontent.com/assets/374042/19267833/9608b1d8-8fb9-11e6-9d26-ad470c9c56eb.png)

**Comment by ParticleCore** [comment]
This was already fixed in version 1.5.7, seems like they changed something again. Will try to fix this issue today and sorry for the trouble.

**Comment by adeep** [comment]
I newly start to use popout function. it working until yesterday.
Thanks for quick response. No problem :)

**Comment by ParticleCore** [comment]
This problem should now hopefully be fixed in version 1.5.9, update to the latest version and let me know if it is fixed for you as well.

**Comment by adeep** [comment]
Yes it fixed now with 1.5.9 update
Thanks a lot.
