### ISSUE TITLE
Minor bug with 'import/export settings' button

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#361]
Browser Name: Chrome

Browser Version: Version 54.0.2840.50 beta-m (64-bit)

Operating System: Win 10

Software Type: Affects both Chrome extension and userscript version.

Software Version: 1.5.7 & 1.5.8

Userscript Manager: Tampermonkey

Userscript Version: 4.1.10

Problem Description: Clicking the actual icon itself of the 'import/export settings' button doesn't work. It only works when clicking just around it.
Doesn't work: http://i.imgur.com/6fsUGJx.png
Works: http://i.imgur.com/DbOZ1OA.png

Steps to reproduce: ^^^^

Additional details: It works correctly in 1.5.6 and only seems to affect Chrome. Tested on firefox and it works correctly. Perhaps it's a bug with the new icon system you implemented.

Also, thank you for changing the movement method of the floating player.

**Comment by ParticleCore** [comment]
I forgot to ignore the new SVG icons from clicks, sorry about that. Will try to fix it today, sorry for the trouble.

**Comment by Eisys** [comment]
No trouble at all. Just something I noticed.

Yes, it's working perfectly. Perhaps the only thing to change would be the size of the grab area. The default floating player size is smaller than mine so it might be hard to see this new button for new-comers. But that's just my 2cents.

**Comment by ParticleCore** [comment]
This should be fixed in version 1.5.9, let me know if it works for you too.

**Comment by Eisys** [comment]
Yep, it's fixed. Thanks.
