### ISSUE TITLE
[bug] youtube video player frame shrunk to a super small frame with latest update..

### ISSUE THREAD

**Issue by JourneyOver** [ParticleCore/Particle#363]
Browser Name: Chrome

Browser Version:  53.0.2785.143

Operating System: Windows 10 x64 bit

Software Type: Userscript

Software Version: 1.5.9

Userscript Manager: tampermonkey

Userscript Version: 4.2.5318 beta

Problem Description: video pages squish video down to a super small frame so it's unwatchable. http://i.imgur.com/R8mbcBM.png

Steps to reproduce: Go to any video and try to watch it...

Additional details: Was watching videos just fine a few hours ago (about 6-7 hours ago) and then I had to leave for a while, I recently just got back home and decided to catch up on some youtube videos but when I went to load up a video the page was loading fine for a moment and then completely shrunk the video down to a super small frame making the video pretty much unwatchable as you can't see a thing other than the play/pause button and the next video button.. I go through the usual routine of checking extensions and such and I find out that youtube+ updated and well I go and disable it for a second and refresh page and youtube starts working like normal, enable it and it causes the issue all over again. I reset my settings for youtube+ and that doesn't seem to fix it so now I'm here posting a bug report.

**Comment by ParticleCore** [comment]
I was just informed of this and the problem was because the user was using a percentage value for the player max width. The recent update of the extension "ignores" percentages by mistake, something that I have to correct.
Can you confirm that you also set your player max width with a percentage value? If so please change to a pixel value temporarily until I post a fix for this.

**Comment by Eisys** [comment]
I just tried it with 70% and am getting the exact same bug.

**Comment by zach-adams** [comment]
Getting same bug as well. 
For the time being you can fix it by disabling the "Fit to page in theater mode" setting.

**Comment by JourneyOver** [comment]
Yep I was using percentages, moving over to pixel value has fixed the issue.

**Comment by ParticleCore** [comment]
Version 1.6.0 has a fix for this problem, for users with Userscript and GitHub hosted Add-on versions it should be available for update now. The other versions on the online stores are pending store approval.
Let me know if it is working again for you.

**Comment by JourneyOver** [comment]
Yep it's working perfectly again :D thanks
