### ISSUE TITLE
Youtube+ nonresponsive

### ISSUE THREAD

**Issue by Mattk50** [ParticleCore/Particle#364]
Browser Name/Version: Firefox 48.0
Operating System: Win 7
Software Type: Userscript
Software Version: 1.5.3
Userscript Manager: greasemonkey 3.9
Problem Description: Having an odd issue where youtube+ has become nonresponsive, even with all my other extensions disabled, the settings window buttons dont respond, (the button has actually vanished, but if you click there the window still shows up), and none of my previous settings are being applied. What it looks like: 
http://i.imgur.com/r9kuYou.png

I havent made any recent changes to my browser which makes this unusual. I usually have a dark theme on as well but as you can see in the screenshot its nonresponsive either way.

**Comment by Mattk50** [comment]
You know, i checked for a new version before writing this, but right afterwards i got a 1.6 update notification. Thanks for the new update.

**Comment by ParticleCore** [comment]
I was just about to ask you to update it, glad to hear it is working well again.
