### ISSUE TITLE
Floating player + fullbrowser mode bug

### ISSUE THREAD

**Issue by MammothJerk** [ParticleCore/Particle#365]
Browser Name: Google Chrome

Browser Version: 53.0.2785.143 m (64-bit)

Operating System: Windows 10 Pro

Software Type: Youtube +

Software Version: 1.6.0

Userscript Manager: Tampermonkey

Userscript Version: 4.1.10 

Problem Description: With the fullbrowser mode toggled on without starting the video, if you scroll down with the floating player active and start the video from the floating player the video will take the floating player width and stick itself to the top left corner and scrolling becomes unresponsive.

Steps to reproduce:
New video without being played
fullbrowser mode toggled ON
floating player activated
scroll down to the comment section to activate floating player
play video

Additional details:

**Comment by ParticleCore** [comment]
Nice catch, thank you for letting me know, will try to fix this today.

**Comment by ParticleCore** [comment]
Version 1.6.1 fixes this issue, let me know if it works well for you too.

**Comment by MammothJerk** [comment]
It doesn't fix it for me

**Comment by ParticleCore** [comment]
Make sure you have updated YT+ to the latest version and press Ctrl + F5 in a YouTube page.

**Comment by MammothJerk** [comment]
Yeah im on 1.6.2 and i've restarted the browser, tried ctrl+ F5.
still nothing

**Comment by ParticleCore** [comment]
Was able to replicate it as soon as I used your settings, will try to find out what is causing the same problem again. Sorry for the trouble.

**Comment by ParticleCore** [comment]
I completely forgot to update the Stylesheet for the userscript version, which means the previous fix was only working for add-on and extension versions, but not userscript.
It should be fixed for you after you press Ctrl + F5 in a YouTube page, let me know if it works well now for you.

**Comment by MammothJerk** [comment]
Yes it's fixed for me now, thanks

**Comment by ParticleCore** [comment]
Glad to hear that, again sorry for the situation, it was a total oversight on my part.
