### ISSUE TITLE
Timestamps no longer function.

### ISSUE THREAD

**Issue by gyvess** [ParticleCore/Particle#368]
This very recently became an issue.  

Disabling Youtube+ in Greasemonkey and refreshing the page caused timestamps to work again.  Another person did the same with identical results, verifying that it is indeed a Youtube+ problem.

**Comment by ParticleCore** [comment]
Can you provide an example? Detailed steps so that I can reproduced?

**Comment by gyvess** [comment]
https://youtu.be/EdQJVGZmp-E?t=18s
https://www.youtube.com/watch?v=EdQJVGZmp-E&&t=18
https://www.youtube.com/watch?v=EdQJVGZmp-E&feature=youtu.be&t=18s&html5=1

None of these links jump to the time specified with Youtube+ enabled.  Instead it simply plays the video from the start.  If you open the drop down from the Greasemonkey menu, uncheck Youtube+, then refresh the page then the time jump will function once again.

I whittled it down to the "Autoplay videos" setting.  With this unchecked timestamp no longer works.  Functions as expected with it checked.

**Comment by ParticleCore** [comment]
I see, this is a consequence of fixing https://github.com/ParticleCore/Particle/issues/350, will try to find a solution for this problem as soon as I can.

**Comment by ParticleCore** [comment]
Version 1.6.3 fixes this issue, let me know if it works for you too and sorry for the delay.

**Comment by gyvess** [comment]
Tried a handful of videos and it is working again.  Great job.
