### ISSUE TITLE
Floating player controls active on regular player bug

### ISSUE THREAD

**Issue by MammothJerk** [ParticleCore/Particle#371]
Browser Name: Google Chrome

Browser Version: 54.0.2840.59 m (64-bit)

Operating System: Windows 10 Pro

Software Type: Youtube +

Software Version: 1.6.2

Userscript Manager: Tampermonkey

Userscript Version: 4.1.10

Problem Description: The floating players 'Move player' and 'Go to top' buttons seem to always be active even on the regular player, they are just invisible but when you hover in the top right and left corners you get the pointer cursor and the hover text

Steps to reproduce: 
Open any video

scroll down to activate floating player
scroll back up
OR have fullbrowser mode toggled ON

hover the mouse in the top left/right corner of the video

Additional details:

**Comment by ParticleCore** [comment]
Got it here too, will try to fix it as soon as I can.

**Comment by ParticleCore** [comment]
Version 1.6.3 has a fix for this issue, let me know if it is also fixed for you too and sorry for the delay.

**Comment by MammothJerk** [comment]
Yes it's fixed now, thanks
