### ISSUE TITLE
Unable to donate to the project using Bitcoin.

### ISSUE THREAD

**Issue by Mustard5** [ParticleCore/Particle#373]
Unable to donate to project using Bitcoin.  The convenience of using Bitcoin makes it the perfect method of sending charitable donation.  Might I suggest that you add that as a feature of your donations section?

**Comment by ParticleCore** [comment]
I never used Bitcoin and I don't understand how it works. Will try it and see how it works out, thank you for the suggestion.

**Comment by ParticleCore** [comment]
Sorry for the delay, but I have finally been able to work around BitCoin for the first time, I hope.

The bitcoin donation address can be found here: https://github.com/ParticleCore/Particle/wiki/Donate
