### ISSUE TITLE
Embed links not working

### ISSUE THREAD

**Issue by otsug** [ParticleCore/Particle#38]
I am using the add-on version 0.3.0 with Firefox 39 beta 64 bit (with the new HTML5 youtube player version) and also tested on Firefox developer edition 40.0a2 (2015-06-29) 64 bit (with the old HTML5 youtube player version) and when I open a tab with a embed link like this:

https://www.youtube.com/embed/VIDEOCODE

The player does not load anything and when I disable your add-on and reload the tab, the video is working fine, I don't know if is one specific setting, I tried changing some but the video didn't work, it would be nice if there was a export/import settings too in cases like this. I tested with many videos not a single one worked, just copy any of the videos codes after the watch?v= and change the VIDEOCODE of the link above. Thank you.

**Comment by ParticleCore** [comment]
There's no support for embed videos, I will update YT+ to not run when that kind of page is opened.
