### ISSUE TITLE
Popup window - small player hides the page

### ISSUE THREAD

**Issue by E-RELevant** [ParticleCore/Particle#383]
**Browser Name**: Chrome

**Browser Version**: 53

**Operating System**: Windows 10

**Problem Description**: When I make a small width window with youtube on it (main page: youtube.com or any other one), it puts what I think is the smaller player version on top of the page

**Screenshot**: http://i.imgur.com/lDso6cs.png

**Steps to reproduce**: Just open youtube, then reduce the web-browser width.

**Additional details**:  It might be always TO6Y7yQw-osgeY-T that shown as the minimized player video.

Would really appreciate a fix for that issue, since I use it all the time as a small window.

**Comment by ParticleCore** [comment]
Please follow the troubleshooting guide like it was requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by ParticleCore** [comment]
Version 1.6.4 comes with a fix for this problem, let me know if it works for you as well.
