### ISSUE TITLE
External Youtube Player not lets to switch Fullscreen 

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Particle#385]
Browser Name: (Chrome)

Browser Version: (55.0.2883.21 beta-m (64-bit))

Operating System: (Windows 10)

Software Type: (Extension)

Software Version: (1.6.4)

Problem Description: **This is feature request**. Can you alter this obstacle that some pages embeded external payers not give permission for going fullscreen? I think it is just small trigger in embed code.

Steps to reproduce: Open [http://www.theverge.com/2016/10/22/13358666/new-trailers-assassins-creed-arrival-planet-earth-logan](url) Play one Youtube video, try to click fullscreen button.
![ff](https://cloud.githubusercontent.com/assets/374042/19620362/a0fcb2d2-9884-11e6-8b14-1a9f7fd43c13.png)

**Comment by ParticleCore** [comment]
I am sorry but I have no intention of extending support for embedded YouTube videos for now.

**Comment by q1k** [comment]
In Firefox you can always use Shift+Right click to open the default context menu, there will be fullscreen option. In Chrome, you can open it with double right click, but there is no fullscreen option.

Of course there is [this script](https://greasyfork.org/en/scripts/9252-) which handles the youtube embeds to speed up the loading of pages with many videos. It also adds the fullscreen attribute to the iframe (`allowfullscreen`), so you can enter fullscreen anyway.

**Comment by adeep** [comment]
@q1k Thanks. it work like a charm.
