### ISSUE TITLE
Private playlist and autoplay

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#386]
When selecting another video in a **private playlist** (doesn't matter if it is by selecting a video, or clicking in the next button) and the autoplay is **disabled**:
https://1.sendvid.com/ivaq0t5j.mp4

A temp fix is disabling the SPF, or enabling the autoplay.

**Comment by ParticleCore** [comment]
Don't know if I will be able to correct this, will see what I can do.

**Comment by ParticleCore** [comment]
Version 1.6.5 has a fix for this problem, let me know if it works for you too.
