### ISSUE TITLE
Fit to page in theather mode in a playlist

### ISSUE THREAD

**Issue by mauriciocolli** [ParticleCore/Particle#387]
When the **width** of the Fit to page in theather mode is small, and you are on a **playlist**, the playlist box don't have the right margin:

![image](https://cloud.githubusercontent.com/assets/13389907/19630972/e320af84-9973-11e6-9ad1-80a892200183.png)

EDIT: Well, I guess it's a recent change on Youtube, the playlist box isn't centered when windows is small too:

![image](https://cloud.githubusercontent.com/assets/13389907/19631478/c6ccd968-997b-11e6-8cf6-649081f93aff.png)

**Comment by ParticleCore** [comment]
Thanks, will try to see what has changed.

**Comment by ParticleCore** [comment]
I just uploaded version 1.6.7 with a fix for this problem, let me know if it works well for you.
