### ISSUE TITLE
Grid layout in search

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#389]
For a little while now the thumbnails and stuff have been alot bigger in search. Combine that with the grid layout and you get this look:
https://i.imgur.com/Sjtlrac.png

Videos are overlapping and thumbnails are getting cut off.

**Comment by ParticleCore** [comment]
That isn't how they are suppose to look, others also had this problem: 

https://productforums.google.com/forum/#!topic/youtube/1QpEst7rxIo

https://productforums.google.com/forum/#!topic/youtube/Uyo_Uo_ownk

Follow the troubleshooting guide, something else is increasing the thumbnails and title sizes too much.

**Comment by Eisys** [comment]
Huh. Didn't realise it could be a bug on my side. Thought Youtube just changed it. Sorry about that.

It happened on Edge too, clearing all the data on that one fixed it.

Clearing data on Chrome doesn't fix it. Only thing that does, is creating a new fresh profile. Which I don't really want to commit to since I have so many extensions and their settings and data saved. Mainly all my random Stylish styles. So for now I'll just disable the grid option in settings and deal with. Perhaps it will fix itself eventually. I don't search all that often anyway.

And a quick question. Any idea what happened to the 'Worldwide' option under content location?
I used to have that one chosen but now it's forcing me to pick a country.

**Comment by ParticleCore** [comment]
Chrome's clean up is a bit tricky, they don't really clean everything as they should, so local storage, cookies, cache, etc. may still remain despite the clean up. I'd recommend the Clear Cache chrome extension, that one worked for me a few times when I needed to do a total clean up on YouTube domain.

`Worldwide` is now `United States`. YouTube never got around to making the worldwide version working correctly, so it was for the most part just work as US and they eventually changed it accordingly in the past few months. Nothing else changed, just the name.

**Comment by Eisys** [comment]
Clear Cache did the trick. Search is back to normal now. Thanks.
