### ISSUE TITLE
"Enable info bar with watch later button" not working.

### ISSUE THREAD

**Issue by MaximilianKohler** [ParticleCore/Particle#390]
Same problem as https://github.com/ParticleCore/Particle/issues/190

UPDATE: Started working again out of the blue. Maybe due to the fact that I used a playlist link (from email inbox subscription). Yes, it seems to only work when I use a link from my email. If I click on the Youtube icon at the top left of youtube.com, then click on a video from there it will not work. However, if I use a link from my email it works, and continues to work if I use that same tab to load other videos, including ones on the right side under "up next".

It also works if I paste a video url in a new tab. **It seems like the only thing that doesn't work is clicking on videos from youtube.com home, trending, or subscriptions tabs.** It even works if from the youtube.com home page I right click -> "open link in new tab".

Browser Name: Firefox

Browser Version: 49.0.2

Operating System: 8.1 x64

Software Type: firefox addon

Software Version: 1.6.7

So this happened during my first setup of this addon.

Pretty sure it did show up temporarily, then I changed some more settings (including various "fit to page in theater mode" settings) and it went away.

I tried restoring other settings but it never would come back. I clicked the YT+ "reset" button and restarted my browser, then pasted in my settings and clicked "save and load", but that didn't work. 

I reset the settings again, but this time also disabled then removed the whole addon. I restarted the browser, installed the addon and only checked this option. It showed while the ad of the first video I loaded played, then it went away permanently.

I made a completely new firefox profile and only installed YT+, only enabled the one option, and the exact same thing happened.

{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": true,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": false,
  "GEN_PPOT_ON": true,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd720",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": true,
  "VID_PPOT_SZ": false,
  "VID_PLR_HTML5": true,
  "BLK_ON": true,
  "floaterX": 2000,
  "floaterY": 2000,
  "firstTime": false,
  "volLev": 50,
  "advOpts": true,
  "blacklist": {},
  "extLang": {},
  "migration_instructions": true,
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": false,
  "GEN_YT_LOGO_LINK": false,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": false,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": false,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": "90%",
  "VID_PLR_FIT": true,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": true,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": true,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": false,
  "VID_PLR_CC": false,
  "VID_PLR_ALVIS_WDTH": false,
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": true,
  "lightsOut": false
}

**Comment by MaximilianKohler** [comment]
That userscript version works fine. Doesn't have the same bug.

**Comment by ParticleCore** [comment]
Thanks, that will help me eliminate a few things, will try to find out why this is happening.

**Comment by ParticleCore** [comment]
Was finally able to replicate it and will try to push a fix as soon as I can, thanks for the detailed report, it was really helpful for tracking this problem.

**Comment by MaximilianKohler** [comment]
Thanks! And thanks for the great addon!

**Comment by ParticleCore** [comment]
Version 1.6.8 contains a fix for this problem, let me know if it works for you too. Since the AMO add-on is pending review you can test or switch to the github hosted version available here: https://github.com/ParticleCore/Particle/raw/master/dist/YouTubePlus.xpi

To install it read the instructions at the end of this page: https://github.com/ParticleCore/Particle/wiki/Download#install_addon

**Comment by MaximilianKohler** [comment]
Works great, thanks a lot!
