### ISSUE TITLE
Full-sized viewer with end-screen

### ISSUE THREAD

**Issue by smithy1294** [ParticleCore/Particle#394]
Hey, so Youtube has recently added the end screen feature, however if you have recently watched a video in the full sized view that this extension adds then go to the dash to try and edit a endscreen it will show your preview video in the full sized view, which would not be a problem but for some reason the 'ESC' key doesn't work to get me out of this view resulting in me having to disable the extension when designing end screens.

Can we maybe get a toggle that pops up in the lower right as well when in this view (Magic actions had this) and can we look into whether this is a personal bug or if it is an actual issue.

Thanks

P.S - Browser - Mozilla Nightly 52.0a1 | Windows 10 AU | Latest update for extension

**Comment by ParticleCore** [comment]
Your explanation is quite confusing, I don't understand what you are trying to say, but if your main issue is that you cannot exit fullbrowser by pressing Esc, you can click on the player's resize button to exit as well. This is explained here: https://github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

Please try to explain the problem better or use screenshots/video examples detailing how I can try to replicate this problem.

**Comment by ParticleCore** [comment]
Ah, I think I was able to replicate the problem. Enable fullbrowser mode, edit endscreen cards after that video has ended, try to preview the video and it goes into fullbrowser mode with no way to exit. Will try to fix it as soon as I can.

**Comment by ParticleCore** [comment]
Version 1.6.9 fixes this problem, let me know if it works for you too.
