### ISSUE TITLE
<video> should resize according to parentNode

### ISSUE THREAD

**Issue by DRSDavidSoft** [ParticleCore/Particle#395]
Thanks for the great feature that keeps video floating when reading comments.

However, there is a problem in both `v1.6.8` and `v1.6.9`. The video doesn't resize properly:
![image](https://cloud.githubusercontent.com/assets/4673812/19840690/0164440e-9f11-11e6-8b42-527e1cac232e.png)

I've written a small fix to size both the video and the bottom timeline according to the parent element, which fixes this partially:
![image](https://cloud.githubusercontent.com/assets/4673812/19840715/d8b6dd5e-9f11-11e6-88c8-61cd073e5549.png)

However, I wasn't able to fix the draggable scrubber sizing. It's somewhere inside YT's internal .js codes which is a pain to reverse-engineer. My guess is that you should call a re-sizing callback when the video is detached to fix these problems.

Here's my code in jQuery (you have to re-write it in vanilla JS, I guess):
```
$(function() {
	// Call this function when both video is detached and attached
	var	$playerObj = $('#movie_player'),
		$btmObj = $playerObj.find('.ytp-chrome-bottom'),
		$vidObj = $playerObj.find('video');
	$btmObj.css('width', parseInt($playerObj.css('width')) - (2 * parseInt($btmObj.css('left'))) + 'px' );
	$vidObj.css('width', parseInt($playerObj.css('width')) + 'px').css('height', parseInt($playerObj.css('height')) + 'px');
});
```
It's really simple, sizes the `<video>` according to parent, and the controls minus the padding which YT team have defined with css `left`.

Sorry for the messy comment, but please fix this problem, it's really annoying to have only a portion of the video while it is detached. Thanks!

P.S. Why the Repo is named `Particle` rather than `YT+`?

**Comment by ParticleCore** [comment]
I am unable to replicate this problem, for me it is resizing properly when switching to floating player and back again. Please follow the troubleshooting guide: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

As for the repository name, the original project name is Particle and it is a backup name in case I might have to rename the extension for some reason.

**Comment by DRSDavidSoft** [comment]
I'm sorry, looks like one of my other Extensions are malfunctioning with the YT+ Tampermonkey script. It is weird though, none of them are related to Youtube.

Anyway, I think this issue is safe to be closed as the script works properly when I tested it on a clean profile of Chrome without any other scripts/extensions installed.

Thanks for your efforts for writing this great extension :)

**Comment by ParticleCore** [comment]
No need to apologize, glad to hear you found a clue for the cause of this problem.
