### ISSUE TITLE
Cannot display YT search history unless this extension is disabled

### ISSUE THREAD

**Issue by gms77** [ParticleCore/Particle#396]
Browser Name: Firefox
Browser Version: 50 beta 11
Operating System: Linux
Software Type: Extension
Software Version: 1.6.9

Problem Description: As title

Steps to reproduce: visit https://www.youtube.com/feed/history/search_history and notice the page is blank.  If I disable the extension then the search history shows up and I can remove entries etc.

![screenshot_20161031_211942](https://cloud.githubusercontent.com/assets/15159047/19872091/f097548c-9faf-11e6-8d66-07986e6c9d41.png)

**Comment by ParticleCore** [comment]
Thanks for the report, will try to push a fix as soon as I can.

**Comment by ParticleCore** [comment]
I am really sorry for the delay, I just uploaded version 1.7.0 with a fix for this problem, let me know if it works for you as well.

**Comment by gms77** [comment]
Yes, it's working now.  Thanks for the fix.
