### ISSUE TITLE
Certain annotations aren't blocked

### ISSUE THREAD

**Issue by DerpMcDerp** [ParticleCore/Particle#399]
It looks like youtube has a new kind of video annotation that doesn't get disabled when annotations are disabled. An example is the following video starting at the 30 second mark:

https://www.youtube.com/watch?v=d9TpRfDdyU0

A bunch of `<divs class="ytp-ce-element">` start to appear on top of the video.

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Particle/issues/298
