### ISSUE TITLE
Possible to add mouseover hover video thumbnails?

### ISSUE THREAD

**Issue by keLston** [ParticleCore/Particle#40]
Sorry, don't know how to label the issue as an enhancement request.

I'm wondering if it's possible to add video thumbnail previews sorta like playing through the video as I hover over it so I get some idea of what's in the video. I think i've seen this feature before but i'm not sure if it makes things bloated.

Thanks!

**Comment by ParticleCore** [comment]
Another user asked for the same, but I am not interested in adding this feature.
