### ISSUE TITLE
Make "Play all" button always visible

### ISSUE THREAD

**Issue by ganego** [ParticleCore/Particle#404]
When on the user page you have the category "Uploads" and the playlists (if any). If you hover them, you get a "Play all" button.
You could add an option to make it always visible by default.
Example of the button: http://webapps.stackexchange.com/a/82675/140373

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
