### ISSUE TITLE
[Req] Add Collapse button to folding player

### ISSUE THREAD

**Issue by yfdyh000** [ParticleCore/Particle#407]
Add to the left of `VID_PLR_ALVIS_SCRL_TOP: "Go to top"`, used to collapse the folding player (keep playing) to concentrate on reading comments or others uses (for example, someone was close behind, I want to read the comments and no picture).

It can be auto-expanded when the main player appears and is hidden again, or presented as a toolbar (like mini-player) or icon on corner.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
