### ISSUE TITLE
[Req] Allow mouse to resize the folding player

### ISSUE THREAD

**Issue by yfdyh000** [ParticleCore/Particle#408]
Like the folding player size on setting, but more intuitive. Just an idea, not a necessary. If possible, a tip appear on page to ask whether to save the new size.

**Comment by ParticleCore** [comment]
Ideally that was what I wanted the first time I added it, but found too many problems with it so it was scrapped unless I can find a better method, until then:
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
