### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by Ingrido** [ParticleCore/Particle#41]
Just some incredibly minor bugs I've seen.
Minor bug 1:
With YouTube+ installed the guide menu button (or whatever it's called) ignores any regional identifiers.
So these screenshots are without YT+ installed:
![1](https://cloud.githubusercontent.com/assets/11162568/8488702/8e7b0fdc-210c-11e5-9ee9-c1dac0fecc6b.png)
![2](https://cloud.githubusercontent.com/assets/11162568/8488703/8e7cdb5a-210c-11e5-8ee2-215abc6dd89c.png)
These screenshots are with YT+ installed:
![3](https://cloud.githubusercontent.com/assets/11162568/8488704/8e7f902a-210c-11e5-844c-e37e19b51abc.png)
![4](https://cloud.githubusercontent.com/assets/11162568/8488705/8e835872-210c-11e5-80b2-2065d4b05c5a.png)
Minor bug 2:
If you have your mouse over the video player and you scroll down (using the mouse wheel or arrow keys), when the scrolling video player appears, the white buttons, which allow the user to move the scrolling video player, will already be showing even if the mouse isn't over the video player.

**Comment by ParticleCore** [comment]
The first one is not a bug, it is on purpose so that the blue notification box will no longer be offset to the right when the country initials are present.


I can't replicate the second one, the buttons remain invisible until the mouse is directly over the player. Do you mean that they appear for a short time when it transitions from the normal mode to floating mode?

**Comment by ParticleCore** [comment]
Are you using the flash player? Because YT+ does not support the flash player, only the HTML5 player: https://github.com/ParticleCore/Particle/wiki

**Comment by Ingrido** [comment]
Took a video of it, only when I mouse over the video/off does the white buttons disappear. https://vid.me/XjLE

**Comment by ParticleCore** [comment]
That helped, I was able to replicate the issue, will see what is causing it. Thanks!

**Comment by ParticleCore** [comment]
So it appears to be a Firefox bug, for some reason the mouse hover state presists when the element changes position. That is why this doesn't happen if when you scroll down with the mouse outside the player area.

This is something I cannot fix, but I will still try to find a way to patch this.

In respect to your first issue, I'd suggest to disable the YT+ option "Improved blue notification box" in the "General" tab, it will restore the country ID position, as well as the blue box's.
