### ISSUE TITLE
[HRF 60fps] (issue)

### ISSUE THREAD

**Issue by ccman12345678** [ParticleCore/Particle#410]
So a few weeks ago, I was able to not view videos in 60fps (good) [With HFR enabled]
NOW It's forcing me to view at 50fps (bad) [With HRF enabled] 

What's the problem?

**Comment by ParticleCore** [comment]
I cannot reproduce this problem, could you provide an example?

**Comment by ccman12345678** [comment]
http://imgur.com/a/UbKmG

**Comment by ParticleCore** [comment]
That option you pointed with the arrow is in no way related to high frame rate streams, it is related to page navigation enhancements developed by Google, AKA SPF: https://github.com/ParticleCore/Particle/wiki/Features#spf_off

The option that disables 60fps, or 50fps, or any fps higher than 30 is this one: https://github.com/ParticleCore/Particle/wiki/Features#hfr_off

Try again with the correct option enabled and see if the 50fps option remains available.

**Comment by ccman12345678** [comment]
Working now, I guess the post I read about disabling 60fps was wrong.
Thanks
