### ISSUE TITLE
Pop-out mode seems down

### ISSUE THREAD

**Issue by kliop00023** [ParticleCore/Particle#413]
Browser : Maxthon 5.0.1.3000
Operating System: win7
Software Type: Userscript
Software Version: 1.7.3
Userscript Manager: Violentmonkey
Userscript Version: 2.6.2

Pop-out mode seems down.

**Comment by ParticleCore** [comment]
Please read the wiki, YT+ only supports Firefox and Chrome: https://github.com/ParticleCore/Particle/wiki
