### ISSUE TITLE
YouTube videos loop despite not enabling them

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Particle#418]
Observed on Firefox 51.0a2. To work around, I enable looping from HTML5 player context menu and immediately un-enable it. OS: `Linux hostname 4.8.0-32-lowlatency #34-Ubuntu SMP PREEMPT Tue Dec 13 15:10:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` Browser User-Agent:`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0` User script manager:Greasemonkey

**Comment by ParticleCore** [comment]
I am unable to replicate this problem, please follow the reporting guide like it was requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you still have any problems please follow the instructions in my previous reply.
