### ISSUE TITLE
Youtube+ seems to prevent the ability to enable closed captions

### ISSUE THREAD

**Issue by keLston** [ParticleCore/Particle#42]
Browser Name: Firefox

Browser Version: 38.0.5 also occurs in the just updated version 39.0

Operating System: Windows 7 x64

Software Type: Firefox addon

Software Version: 0.3.1

Problem Description: With Youtube+/Particle enabled, the player controls will never display the closed caption (cc) button to enable subtitles/captions on videos that have them. Disabling only Youtube+ restores that button so it appears addon specific.

Steps to reproduce: View a video with closed captions enabled by uploader using Youtube's default HTML5 player.

Additional details: Example video tested on: https://www.youtube.com/watch?v=p5vOC55m1Cw

**Comment by keLston** [comment]
Oops I messed something up

**Comment by TylerJS** [comment]
Mind explaining what you messed up? I'm having the same issue and its incredibly frustrating when people dont bother to give their solution like this.

**Comment by TylerJS** [comment]
Since this guy couldnt be bothered to help anyone else out with the solution its: settings > video > disabled subtitles, for those of us who were looking for a 'CC' or 'Closed' 'Captions' option.

**Comment by ParticleCore** [comment]
@TylerJS Perhaps It would be best to not have that option turned on by default, didn't think it would cause so much confusion. The next version will have it set to default, if users want to turn it on then they can activated it by their own choice instead of it being forced.

**Comment by TylerJS** [comment]
Simplest solution to solve any confusion in I think would be to add 'CC' or 'Closed Captions' in options or the wiki page for the option as thats what I myself was searching for, those keywords. Either way I dont think removing the button all together by default is necessary since it doesnt take up any otherwise used space and you dont have to actually have it enabled.

Thanks for the response!

**Comment by Yonezpt** [comment]
Thanks for the suggestion, will definetly include the CC information on both places.

**Comment by keLston** [comment]
@TylerJS The Help documentation for Features had mentioned under the "Video" section labelled "Disable Subtitles and CC" which is what I apparently missed when I checked it the first time.

**Comment by ParticleCore** [comment]
@keLston No, you didn't miss, I added it recently right after the Tyler's suggestion. It will also be added in the extension with the next release.
