### ISSUE TITLE
[Feature] Hover comment date/permalink to view exact date?

### ISSUE THREAD

**Issue by jimbo1qaz** [ParticleCore/Particle#420]
Can you add a feature, where hovering the date/permalink of a comment will show its exact date? Probably doesn't need an off switch.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by jimbo1qaz** [comment]
If I develop such a feature, do you accept pull requests? (Is this project
in maintenance mode?)

**Comment by ParticleCore** [comment]
Only translations are accepted: https://github.com/ParticleCore/Particle/wiki/Translation-template
