### ISSUE TITLE
Problem with the icons

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#428]
Since the return of the frame-by-frame feature I updated the script recently and the icons are not behaving properly as page loads.
![pr](https://cloud.githubusercontent.com/assets/7927176/21747333/595d08ba-d564-11e6-9f11-3dc17f2aa78d.png)
On the picture you can see one example. Pretty much every other icon has issues like these... It can be out of place, too big, too small... for a second or less, but sometimes longer, depending on how long it takes to retrieve the css file from github.

You should probably embed the stylesheet with the script. Or at least include some of the most necessary properties as inline to fix this.
Thank you

**Comment by ParticleCore** [comment]
Everything is behaving normally on my end in Firefox and Chrome

![ss](https://cloud.githubusercontent.com/assets/9222661/21749108/64f56b32-d586-11e6-8a46-4d692a4631b0.png)

Please follow the troubleshooting guide to see what is causing the problem in your end: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by ParticleCore** [comment]
If I understood correctly, this is only happening when the css file is loading from github, after that no problems exist. Since I cannot control that and I will not be embedding the css inside the userscript for the reasons I have already explained in the past, this is something that will not be fixed on my end.
An alternative exists which is the Firefox Add-on version which comes with the css inside the add-on package, so it will load as fast as your computer can since it no longer depends on remote hosting.

**Comment by q1k** [comment]
github today was unreachable (for me at least) for a few hours. So the [problems with the icons were back](https://greasyfork.org/en/forum/discussion/12188).
I will say again, a simple fix for this would be to add some of the most necessary properties as inline to the icons (i.e. height, width, display, and positioning).
This will not be all the css, just a few lines, and can be done in the extension versions as well so you can keep the differences to a minimum.

**Comment by ParticleCore** [comment]
I have already explained that I will not be embedding CSS in the code and why, and I even suggested the Add-on version which already comes with the CSS included, completely avoiding having to load the CSS file from GitHub. If you still insist on using the userscript version knowing fully well that it is not behaving as you'd like and refuse the alternative solution then that is your choice to make, but please do not insist on this again.
