### ISSUE TITLE
Feature Request : Disable  Share panel after voting a video.

### ISSUE THREAD

**Issue by Betsy25** [ParticleCore/Particle#43]
Hi,

Just like we have the option "Disable share panel when video ends"
.... is it possible to have the  same option for when having voted a video ?
"Disable share panel after voting video" ?

Thanks for thinking about it.

**Comment by ParticleCore** [comment]
The first one is easily controlled via a YouTube JS variable, the second one isn't and would require more than just a simple function to prevent it from opening after liking the video. Until I happen to find a simple way to control this behavior like the other one, I don't find the trouble and overhead worth adding for this feature.

**Comment by thegrandpow** [comment]
I would really like this feature.

And I do believe it is possible to disable the share panel on video like with a simple hack.
You see, when you press the "**share**" button an attribute is added `[aria-pressed="true"]`. So you could technically hide the share panel if this button isn't pressed.
I think this is doable.

**Comment by MattSturgeon** [comment]
This feature would be really useful for me. Not sure why it's closed, even if there are no plans it's normal to keep feature-requests open (unless there is some objection to them).
