### ISSUE TITLE
"Disable YouTube loudness normalisation" does not work

### ISSUE THREAD

**Issue by mkwstar** [ParticleCore/Particle#430]
Browser Name: Google Chrome

Browser Version: 55.0.2883.87 m (64-bit)

Operating System: Windows 10

Software Type: Userscript

Software Version: 1.7.5.

Userscript Manager: Tampermonkey

Userscript Version: 4.2.7

Problem Description: The loudness normalisation feature does simply not work. Videos still get played at exactly the same volume as without the feature.

Steps to reproduce: Test video: https://youtu.be/fbTlspIKptE

The volume only goes slightly above 50% at the louder parts. All volume sliders are fully turned up.

Second test video: https://youtu.be/Yq83rW7uHVc

Volume never goes above ~75%.

Aside from this specific problem I have to say Thank You! YouTube+ is very good :)

**Comment by RPGWiZ4RD** [comment]
Same issue, it was the reason I installed YouTube Plus, good timing as I viewed this thread right at the same time as you first posted it.

**Comment by ParticleCore** [comment]
YT+ does not interact with system controls or browser controls, that feature simply removes the artificial loudness normalization setting YouTube adds to videos.

After testing the video examples you posted I could confirm that it is working as expected, the videos are louder when compared with YT+ disabled.

The first video has a loudness control set to -15.0690002441 and the second -17.9290008545, after enabling YT+ and refreshing the videos the loudness value is completely removed as it is intended.

To verify this by yourselves open your browser console and enter the following with and without YT+ enabled:

    ytplayer.config.args.loudness

You will be able to verify that the loudness is being removed.

If you read the feature information you can see that it does not tell you it increases any volume, it simply removes the loudness set by YouTube on the client side: https://github.com/ParticleCore/Particle/wiki/Features#disable_normalisation

**Comment by RPGWiZ4RD** [comment]
It is NOT working for me. What do you suggest me trying?

**Comment by ParticleCore** [comment]
Please follow the troubleshooting guide as requested before opening an issue to see if you can identify what is the cause of this problem on your end: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

I tested with the same browser version as yours and the volume was noticeable louder, so there is something on your end affecting this.

**Comment by RPGWiZ4RD** [comment]
Unfortunately following those steps precisely didn't help (I already tried doing that before):

Browser Name: Chrome

Browser Version: 55.0.2883.87 m (64-bit) or 56.0.2924.51 beta (64-bit)

Operating System: Windows 10 Professional 64bit

Software Type: YouTube Plus

Software Version: 1.7.5

Problem Description: Disable YouTube normalization stopped working as Chrome got updated to 55.0.2883.87 m (64-bit)

Steps to reproduce: I've been unable to get the normalization gone, I've been for example tested following videos on my channel:
https://www.youtube.com/watch?v=2_vS0HwDPq0
https://www.youtube.com/watch?v=K1ll0s9ZP2w

Additional details: 

Tested now installing Firefox as well, same thing, not working, the videos doesn't play as loud (EDM "brickwalled" loud mastering) as they do on my computer before uploading to YouTube.

**Comment by ParticleCore** [comment]
I think this might be related to #432, so when I push the new update with the fix I will ask you to test the new version to see if it solves your issue as well, if you have the time for it. I assume it will because you explained that the audio sounds louder with the flash player, so if everything goes right the fix should also restore the higher levels for everyone.

**Comment by RPGWiZ4RD** [comment]
OK, thanks for the info, let's hope so :)

**Comment by ParticleCore** [comment]
Version 1.7.6 contains a fix for the linked issue which appears to be related to this one, as I suspected. YouTube decided to control how high the volume could go, which is lower than the actual max limit the HTML5 player can reach, which is why the videos sound lower than usual, even when loudness was removed.

Let me know if it works for you too now.

**Comment by ParticleCore** [comment]
Marking this as the original issue for organization purposes.

**Comment by RPGWiZ4RD** [comment]
Working now! Thanks a lot for the help 👍 Now where's that donate button :)

**Comment by ParticleCore** [comment]
Thanks for letting me know. If you wish to make a donation you can find the donate button in the YT+ settings list or here https://github.com/ParticleCore/Particle/wiki/Donate
