### ISSUE TITLE
[suggestion] Opera

### ISSUE THREAD

**Issue by Tox86** [ParticleCore/Particle#431]
Hi its possible port the extension to opera.

Cheers.

**Comment by q1k** [comment]
http://www.howtogeek.com/210925/how-to-install-chrome-extensions-in-opera-and-opera-extensions-in-chrome/

https://addons.opera.com/en/extensions/details/download-chrome-extension-9/

**Comment by ParticleCore** [comment]
There are no plans to support other browsers besides Firefox and Chrome for now.
