### ISSUE TITLE
Select audio output? Feature proposal 

### ISSUE THREAD

**Issue by jmsether** [ParticleCore/Particle#434]
I know this exists "Due to time and framework limitations I am unable to accept any more feature requests." but I figure that proposing can't hurt. Would it be possible to implement the ability to send the audio to a different audio out than the system default? Like the plugin by the way. Great work 👍

**Comment by ParticleCore** [comment]
That is a browser level access which this extension does not have access to, so on my part I have to say that I cannot do it, but I wouldn't be surprised if there is a dedicated extension capable of doing that.
