### ISSUE TITLE
Direct link to the 20 latest subscription videos playlist

### ISSUE THREAD

**Issue by admolot** [ParticleCore/Particle#436]
Could you be so kind as to provide a direct link to the 'Subscriptions' youtube page with the latest 20 videos. 

As described:
https://github.com/ParticleCore/Particle/issues/272
my playlist controls not showing.

So could you provide a direct link to the the 'Subscriptions' button depicted in this pic:
http://i.imgur.com/q9qgFhZ.png

Browser Name: Firefox

Browser Version: 50.1.0

Operating System: Windows 10

Software Type: Extension

Software Version: 1.7.3

Userscript Manager: Not sure what this has to do with anything, since I installed Greasemonkey 3.9 way before youtube+, and even when I disable Greasemonkey the youtube+ still appears to be working as usual 

Userscript Version: 3.9 

Problem Description: Above

**Comment by ParticleCore** [comment]
The button shows when you are in the subscriptions tab for a good reason. It needs to "see" the 20 latest videos that are available in that subscription page, otherwise it won't work, which is why the subscription page needs to be opened before loading those 20 videos into a playlist.

Also this has nothing to do with the issue you linked.

**Comment by admolot** [comment]
> The button shows when you are in the subscriptions tab 
There are no button showing. 

Is there a way to make the button to appear in the subscription page?

**Comment by ParticleCore** [comment]
If you turned that feature off you can enable it again via the YT+ settings > General > Enable Subscription Playlist
https://github.com/ParticleCore/Particle/wiki/Features#sub_playlist

**Comment by admolot** [comment]
The feature is turned on, and yet the 'Subscriptions' button is nowhere to be seen.

I want to see "Home Trending Subscriptions" in the top bar:
http://i.imgur.com/q9qgFhZ.png

I'm actually seeing this:
http://i.imgur.com/3Gsj28z.png

**Comment by ParticleCore** [comment]
That has nothing to do with YT+, something else is removing or hiding your tab bar. Follow the troubleshooting guide to find out what is causing this problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by admolot** [comment]
You seem to be right.

There are quite some number of people with a similar problem:
https://productforums.google.com/forum/#!msg/youtube/scKv7SsLtlw/ASkwtz7ZAQAJ

So, maybe when someday you'll fix the problem.

**Comment by ParticleCore** [comment]
Thanks for letting me know and I hope they get it fixed quick, it is quite annoying having to open the hamburger menu (top left 3 horizontal lines button) to switch pages every time.
