### ISSUE TITLE
Major FAIL and why I will stay with YepPha YouTube Center, you can't download video.

### ISSUE THREAD

**Issue by ArJunaZ** [ParticleCore/Particle#438]
Major FAIL and why I will stay with YepPha YouTube Center, you can't download video with Particle.

The primary interest in a YouTube plugin is to be able to download the videos.

**Comment by ParticleCore** [comment]
YT+ has never promised or stated that it had a download feature, furthermore having a download feature would result in getting the extension removed from the webstore for violating YouTube's ToS, which is what happened with YTC:

>~~Chrome Webstore Page: chrome.google.org~~ (taken down by Google, currently being reviewed)

https://github.com/YePpHa/YouTubeCenter/wiki#chrome--opera-15-extension

Also the download option would be very limited, even if it were implemented, it's just not worth it.

This was already explained here: https://github.com/ParticleCore/Particle/issues/32#issuecomment-115012788

Additionally this is not an extension focused on the users, but on me and shared publicly. What I like to have I add it, but any suggestions are always welcome, however it doesn't mean they will be added. You can read more about it here: https://github.com/ParticleCore/Particle/issues/412

Lastly, this is not a replacement for anything, it is just an alternative for anyone that finds these features useful for them. If you feel that YTC is a far better option or just right for you then that is the right choice to make.

**Comment by ArJunaZ** [comment]
BTW, sorry I dissed Particle with my OP. What you did here is actually kind of slick and well done.  Props to you.

**Comment by ParticleCore** [comment]
I can't make them work together, YTC has a ton of complexity which overrides almost all methods YT+ requires to function properly. At that point it is better to not have both running at the same time because they aren't compatible in any way and I can't make it happen just on my end, YTC would have to be updated for both to have a chance of working together.

**Comment by ArJunaZ** [comment]
Understood. How about an icon that can be used to turn on/off Particle. I'd like to use both this and YTC because I save a lot of videos.  As a retired computer engineer over 50 and now a researcher I am up to roughly 225TB on around 70 drives of actual DATA, much of it videos of global political related events.  This will be quicker than navigating repeatedly to add-ons. I can turn off YTC via Greasemonkey this way. It'd be a help and others might find it useful too.

**Comment by ArJunaZ** [comment]
Again, sorry for the grumpy OP.  I like what you've done with this. Downloading would be icing on the cake, but the cake is pretty good too.

**Comment by Keith94** [comment]
You can always try an additional script for downloading videos, such as this one: https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4

It's fully compatible with YouTube+.

**Comment by ArJunaZ** [comment]
Hi Keith94, thanks for the link.
