### ISSUE TITLE
Handle shared links

### ISSUE THREAD

**Issue by vzjrz** [ParticleCore/Particle#439]
Test: https://www.youtube.com/shared?ci=a5ulwT9Sgiw

Currently tabs infinitely reload.

**Comment by ParticleCore** [comment]
Cannot replicate, that shared page is correctly redirected to its video page. Please follow the troubleshooting guide, which was requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by vzjrz** [comment]
Yeah my bad, my original search didnt spot #308
