### ISSUE TITLE
Video will not load at max or selected quality upon first play untill I reselect video quality again.

### ISSUE THREAD

**Issue by Mariner1712** [ParticleCore/Particle#44]
This as been an issue for me since 0.1.8, but when I open any video, the quality is always one setting lower than whatever I set in the YT+ options (1080p), despite the video actually saying that max quality is selected on the player bar.

I always have to reselect the desired quality on the player, and then it reloads properly.

**Comment by ParticleCore** [comment]
Can you share a screenshot showing this issue?

**Comment by ParticleCore** [comment]
I will assume that the issue you are mentioning is not related to YT+, but rather to the way YouTube is starting their videos, which is with the next lowest quality on the first few seconds (or more) and then it switches to the selected quality. I have observed this happen very often with videos that have been posted recently, especially the ones from less popular channels.

This is not something I can change, it is the way their player has been working and it is a fairly recent change (probably from around when they released the new transparent player).
