### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by Compcort** [ParticleCore/Particle#440]
Using Chrome´s recent version on Chromebook.
I just discovered the screenshot feature and was so happy until I discovered that I cannot find the screenshots I took.
Thanks

**Comment by Yonezpt** [comment]
Each time you take a video screenshot, the resulting image shows at the bottom right corner of your browser so that you can either save it to your local drive or not: https://github.com/ParticleCore/Particle/wiki/Features#adv_screenshot

It does not save images automatically.

**Comment by ParticleCore** [comment]
Each time you take a video screenshot, the resulting image shows at the bottom right corner of your browser so that you can either save it to your local drive or not: https://github.com/ParticleCore/Particle/wiki/Features#adv_screenshot

It does not save images automatically.

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having trouble just reply.
