### ISSUE TITLE
YouTube+ tools do not show up under videos in Microsoft Edge

### ISSUE THREAD

**Issue by scottlow** [ParticleCore/Particle#441]
Browser Name: Microsoft Edge

Browser Version: 38.14393.X.X (Anniversary Update builds forward)

Operating System: Windows 10

Software Type: Userscript

Software Version: 1.7.6

Userscript Manager: Tampermonkey

Userscript Version: 4.2.5349

Problem Description: 

YouTube+ tools do not show up under videos in Microsoft Edge

Steps to reproduce: 

1. Install Tampermonkey from the Windows Store in Microsoft Edge
2. Install YouTube + from https://greasyfork.org/en/scripts/9932-youtube
3. Open any YouTube video and notice that the tools do not appear:

![youtube](https://cloud.githubusercontent.com/assets/2479615/22160403/2609b680-defa-11e6-95f9-6fc06c33c996.png)

Additional details: 

This occurs due to a bug in Edge that unfortunately will not make the bar for fixing in our next release. Based on the CSS specification (http://www.w3.org/TR/CSS22/visudet.html#inline-replaced-width) the width value for the SVGs should be computed as follows:

if 'width' has a computed value of 'auto', 'height' has some other computed value, and the element does have an intrinsic ratio; then the used value of 'width' is: (used height) * (intrinsic ratio)

Unfortunately, we do not respect this computation, and as a result, the width of the SVGs is 0, causing them to not display. A simple workaround can be achieved by giving these SVGs a specific width.

**Comment by ParticleCore** [comment]
Please read the description, YT+ is currently only supporting Firefox and Chrome:

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by q1k** [comment]
Adding width and height as inline will also take care of a problem happening when [github is unreachable.](https://greasyfork.org/en/forum/discussion/12188/x)
You can take care of two problems at once, yet, you always say 'no', not to just this but to lots other enhancements...
