### ISSUE TITLE
hide channel watermark inside player

### ISSUE THREAD

**Issue by disrupted** [ParticleCore/Particle#443]
![channel watermark](https://cloud.githubusercontent.com/assets/4771462/22216382/2ee02ca6-e19f-11e6-815e-7cc617c2fe5c.jpg)

would it be possible to hide the watermark used to subscribe to a channel in the lower right corner of the player?

**EDIT**
actually just tried it myself and got it working. if I can add it to the Particle source code I'm gonna submit a pull request.

**Comment by ParticleCore** [comment]
The watermark is linked to the annotations, if you turn them off you remove the watermark. I am sorry but I cannot accept code changes.

**Comment by disrupted** [comment]
well, then it simply doesn't work properly at the moment, because the setting to disable annotations is already enabled and the player still shows the watermark (other annotations don't show up however).

I wrote this tiny userscript to hide it. I would be happy if it would get merged into the Particle code but if you aren't willing to do so I am just gonna leave this here for others who might run into the same issue. https://github.com/disrupted/YouTube-watermark-cleaner

**Comment by ParticleCore** [comment]
With annotations enabled vs disabled:

![ss](https://cloud.githubusercontent.com/assets/9222661/22219709/5786125a-e19b-11e6-9815-70711f7c75ee.png)

This is default YouTube behavior, when you turn off annotations via the cogwheel menu in that screenshot. If yours isn't behaving like this then something is affecting the normal player behavior, perhaps another extension that changes YouTube and might be causing this conflict.
