### ISSUE TITLE
Adding Loop to Certain Time Frame

### ISSUE THREAD

**Issue by ricksee** [ParticleCore/Particle#445]
Is it possible to be adding looping to a certain time frame. Lets say I want the video to keep looping from 0:42 to 2:10 or something like that.

**Comment by ParticleCore** [comment]
>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by q1k** [comment]
Until (and if) this is added, you can use http://youtubeonrepeat.com/
