### ISSUE TITLE
Auto expand comments when linking to comment

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#450]
When visiting a page with a linked comment being highlighted, the comments should auto expand.
It feels weird when the page scrolls down to the comments, but they are hidden.

**Comment by ParticleCore** [comment]
I agree, but unless there is a key value in the url/link there is no way of knowing if it is a linked comment in order to override whichever user visibility the user has. Can you provide a link example to see if I can do anything about this?

**Comment by q1k** [comment]
Yes there is a part in the url. &lc
https://www.youtube.com/watch?v=09R8_2nJtjg&lc=z12qy15ymmr5dbpdr23nubhbqmjtx5uug
and on a reply
https://www.youtube.com/watch?v=09R8_2nJtjg&lc=z12qy15ymmr5dbpdr23nubhbqmjtx5uug.1485799307836213

**Comment by ParticleCore** [comment]
That's great, they both have a common GET so this will make the check even more simple, will try to implement this behavior as soon as I can.

**Comment by ParticleCore** [comment]
Version 1.7.8 comes with this enhancement, keep in mind that YouTube itself is not working with replies to comments, only direct links to 1st level replies.

**Comment by q1k** [comment]
Linking to a reply works, but not if that reply is hidden (visible when clicking 'view all replies').

**Comment by ParticleCore** [comment]
Yes, that is a YouTube limitation, nothing related to YT+

**Comment by q1k** [comment]
I just noticed that linking to comments is also done with `google_comment_id`
https://www.youtube.com/watch?v=09R8_2nJtjg&google_comment_id=z12qy15ymmr5dbpdr23nubhbqmjtx5uug
Will also scroll down to the comment section.

**Comment by ParticleCore** [comment]
Did not know about that one, will try to update it as soon as I can.
