### ISSUE TITLE
Embeded videos

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#451]
Please enable the options to work on embeds as well.
Not all, but those that can, like disabling annotations, loudness normalization, enabling frame-by-frame mode, and such... essentially those that don't do something with the page, but the video player.
Certainly there is no need to activate the part for changing the youtube logo link on the embedded videos.

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Particle/issues/38
