### ISSUE TITLE
[Feature Request] Hide/Remove recommendations sidebar

### ISSUE THREAD

**Issue by harl** [ParticleCore/Particle#452]
Here's just a minor feature request (minor as in not substantial to Particle's main scopes, I guess):

On a video page, it could be helpful to hide the sidebar (the one showing those video recommendations right next to the video frame). Maybe if you could apply the same mechanism you're using for the comments section (to Show/Hide/Remove them according to the setting), that would make it easier to keep that sidebar section (#watch7-sidebar) from distracting the viewer from watching the video at hand (and also reduce the initial traffic and rendering time of the page).
Hiding it with ABP or uBlock has a similar effect, except the page needs to be reloaded in case I really want to see those recommendations, so your approach would make this way more comfortable.

Ok, so don't let this pressure you or anything, because it's really mainly a kind of ornament.
Your work has resulted in a tremendously helpful add-on and I salute you for that.

**Comment by ParticleCore** [comment]
This is not a feature I find to be useful, the distraction sidebar can be moved down automatically when a user switches the player to theater mode.
