### ISSUE TITLE
Add button with input or a slider to control playback rate.

### ISSUE THREAD

**Issue by XCanG** [ParticleCore/Particle#454]
Sometimes need to setup different playback rate, than 0.25/0.5/1/1.25/1.5/2, would be good having small control of it. It may be input form or slider.

Changing playback speed is possible by JS, example for web console:
```
document.getElementsByClassName("html5-main-video")[0].playbackRate = 1.0;
```
*(where 1.0 is speed value)*

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

**Comment by q1k** [comment]
[Menu Wizard](https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/) on Firefox is how I made my own playback speeds.
