### ISSUE TITLE
add option to hide chat

### ISSUE THREAD

**Issue by MurkBRA** [ParticleCore/Particle#455]
There is a chat in [live videos](https://www.youtube.com/watch?v=qzMQza8xZCc)
I did a little code that hide this chat like you did in detail:
```
    var chat;
    chat = document.querySelector(".yt-uix-expander.live-chat-expander");
    if (window.location.pathname === "/watch" && chat) {
        chat.classList.add("yt-uix-expander-collapsed");
    }
```
can you implement this feature?

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
