### ISSUE TITLE
Greasyfork's link has been deleted 

### ISSUE THREAD

**Issue by fuaxio** [ParticleCore/Particle#459]
https://greasyfork.org/en/scripts/9932-youtube 

![capture](https://cloud.githubusercontent.com/assets/13122476/23128322/8753904c-f7a4-11e6-9c2a-a3eb37b8086a.PNG)

**Comment by amfakh** [comment]
![image](https://cloud.githubusercontent.com/assets/8016957/23136011/517734f0-f7cd-11e6-90c8-c67bc85c7e72.png)
this is what I got in my firefox, my Youtube feels kinda odd without this lol

**Comment by ganego** [comment]
This explains a lot. I thought YT changed stuff and this is why the addon broke. I just made sure it was still there and did not even read this description text, so I thought everything was ok.
Why was it deleted?

**Comment by ParticleCore** [comment]
The reasons for this decision have been explained here: https://greasyfork.org/en/forum/discussion/comment/31166/#Comment_31166

**Comment by GuardianMajor** [comment]
@ParticleCore just a heads up, the comment linked above doesn't exist anymore.

![capture](https://cloud.githubusercontent.com/assets/5274181/23816328/109994f0-05a1-11e7-867e-f7784ab441f9.PNG)

**Comment by ParticleCore** [comment]
@GuardianMajor Thank you for letting me know, I will update the above comment with the link to the cached version and include the exchange as well in case that version is also lost.

**Comment by ParticleCore** [comment]
The script has been restored to GreasyFork

**Comment by q1k** [comment]
Are you aware of [this](https://greasyfork.org/en/scripts/28576-youtube)?

**Comment by ParticleCore** [comment]
I was not aware, but as far as I can tell it is respecting the small license I put in place:

>Use of the software and its source code for sharing without unauthorized third party modifications
   with included easily visible linkbacks directing to the source of the original file(s) location(s) or main directory

https://github.com/ParticleCore/Particle/blob/master/LICENSE

If anything, it is the website owner that might not like having duplicates. Thanks for letting me know.
