### ISSUE TITLE
correct alignment

### ISSUE THREAD

**Issue by Artlant** [ParticleCore/Particle#461]
![screenshot from 2017-02-27 17-23-50](https://cloud.githubusercontent.com/assets/13064767/23367095/b90a1bd4-fd11-11e6-89f7-35cc8696355f.png)

**Comment by ParticleCore** [comment]
An annoying issue I wanted to correct a long time ago, but the solutions overhead were always too big to make it worthwhile. Will see if there is a way to do it better now, otherwise I won't fix it.

**Comment by Artlant** [comment]
@ParticleCore  add this to css file
```
.item-section > li:nth-of-type(1) {
    display: block;
}
```

**Comment by ParticleCore** [comment]
That is not a solution. Whenever there is no `Did you mean ...` message then whichever is the first `li` element will occupy the entire row.

I cannot find any reasonable solution for this, the problems remain the same as the ones I met before when I tried to correct this. For the time being this will stay unfixed.

**Comment by q1k** [comment]
$('.spell-correction').parent.css("display","block");

But I don't need it, since I don't use the grid view

**Comment by ParticleCore** [comment]
That's an overhead that I do not want to add to the extension. A solution for a problem as small and punctual as this must be as light as possible, otherwise it will always be running unnecessarily. Ideally the solution must be CSS, not JS, but it should help the user with what he wanted for now.

**Comment by mauriciocolli** [comment]
You can add the class `yt-lockup` to the element `spell-correction`
Or use the properties of this class:
```css
.spell-correction {
    width: 246px;
    border: initial;
    padding: initial;
    margin-right: 10px;
    margin-bottom: 12px;
}
```

**Comment by ParticleCore** [comment]
@mauriciocolli That will only make the list element look like another grid element, which is something that is already in place for the next release. The objective of this issue is to make that specific list element stay on top of everything instead of letting it be just another grid element, like what @Artlant did in his suggestion, except his solution does not differentiate between an actual video element from the spell correction.

**Comment by Artlant** [comment]
I think it is worth close this thread. I also tried the following options (generally many choices, this is the most simple): 
```
 property section > li: matches (div. spell-correction, spell-correction.-dym) 
 property section > li: has (spell-correction), 
 property section > li: has (> div. spell-correction), {
 background-color: red; display: block; 
} 
 ```
 but not one somehow does not work (
 
 the cleanest option simply create a new `div` from above and copy the value of `.spell-correction` (which would not violate the grid).  But because of his stubbornness "_and. .. the solution must be CSS, not JS_ ", hardly possible to implement. At least I didn't have enough skill to make a working combination of selectors (: has: hot, ...)  
 
 ps/ instead of a grid to better use Flexbox

**Comment by ParticleCore** [comment]
@Artlant Nothing is preventing you from using whichever solution you like, I even noted that the solution @q1k provided does exactly what you want, if you want to add it yourself.
