### ISSUE TITLE
Search results suggestion misalignment

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#462]
Continuing from the other issue #461 
The search results correction suggestion is considered part of the grid elements layout.

To fix this, one way is to add one line of javascript:
 
    $('.spell-correction').parent.css("display","block");

The other way is to add media queries in the CSS to account for the various breakpoints

    .spell-correction { margin-right: 0 !important; }
    
    @media (max-width: 704px) {
      .spell-correction{
        width: 406px !important;
      }
    }
    @media (min-width : 705px) and (max-width : 910px) {
      .spell-correction{
        width: 612px !important;
      }
    }
    @media (min-width : 911px) and (max-width : 1023px) {
      .spell-correction{
        width: 864px !important;
      }
    }
    @media (min-width : 1024px) and (max-width : 1300px) {
      .spell-correction{
        width: 970px !important;
      }
    }
    @media (min-width : 1301px) {
      .spell-correction{
        width: 1024px !important;
      }
    }

I'm sure this can be fine tuned even more to account for even more breakpoints. But this should do the job just right.

**Comment by ParticleCore** [comment]
Please don't post continuations of closed or locked issues, instead edit your comments in the original issue.
