### ISSUE TITLE
YouTube Video Page Fit To Screen Option

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#463]
Browser Name: Chrome

Browser Version: 56.0.2924.87 (64-bit)

Operating System: Windows 10 Pro

Software Type: YouTube Plus extension

Software Version: 1.7.9

Userscript Manager: /

Userscript Version: /

Problem Description: There is space between the YouTube video page and my screen

Steps to reproduce: Make an option to fit the YouTube video page to the screen

Additional details: /
![43242334](https://cloud.githubusercontent.com/assets/18757054/23529505/2ec8ed58-ff9e-11e6-957a-536041de71e1.jpg)

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
