### ISSUE TITLE
Can't turn off "Change volume with mouse wheel"

### ISSUE THREAD

**Issue by sirylj** [ParticleCore/Particle#467]
Option remains on (volume still controlled by mouse wheel, can't scroll down page when cursor is on video) after turning off in options and saving.

**Comment by ParticleCore** [comment]
Please follow the instructions like it was requested before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you still have any issues please follow the previous instructions.

**Comment by sirylj** [comment]
That's fine, I updated my browser and the on/off switch works now. Sorry
for the trouble.
