### ISSUE TITLE
Feature Request: Quality control for embedded videos

### ISSUE THREAD

**Issue by Morphello** [ParticleCore/Particle#47]
Hi! I was just wondering, if it would be easy to implement, if you could include a separate quality control for embedded videos. Every embedded video is 360p by default and it would be handy to be able to select something higher from the get-go.

Thanks!

**Comment by ParticleCore** [comment]
Sorry, but YT+ does not support embedded videos, see https://github.com/ParticleCore/Particle/issues/38#issuecomment-117966715 and https://greasyfork.org/en/forum/discussion/comment/14639/#Comment_14639
