### ISSUE TITLE
Any chance for support of m.youtube.com?

### ISSUE THREAD

**Issue by Novgorod** [ParticleCore/Particle#471]
Hi,

I'm aware that the project might be on halt soon. Still, it would be great to have (at least some) support for mobile devices through the m.youtube.com domain, as the desktop site is pretty unusable on mobile devices. The most useful feature would be to enable HD playback on m.youtube.com, and probably the adblocker. So far, it's impossible to play youtube videos in HD in any mobile browser (apart from the desktop version, which has issues with the player in every browser besides being unusable) and this script/addon could probably easily remedy this, since it's already compatible with Firefox for Android.

Thanks for considering!

**Comment by ParticleCore** [comment]
The mobile version of YouTube is completely different than the one YT+ currently supports, to make it compatible with it would require the reconstruction of the entire extension from scratch.
