### ISSUE TITLE
False Material Detection and Small Typo

### ISSUE THREAD

**Issue by roy192** [ParticleCore/Particle#474]
I was watching a video about a new plastic that conducts electricity ([link](https://www.youtube.com/watch?v=DlLZVxNK3Jg)), and got a message about the new youtube material layout, and that Youtube Plus is not compatible with it.

I looked around and saw nothing new, it looked exactly like the old layout... I looked at your source code, and found the isMaterial function. Which seems to check for a tag that matches: "ytd-app, [src*='polymer'],[href*='polymer']". It matched a link in the video description that had the word polymer in its url.

I also found a small typo in the troubleshooting section: 
> Make sure that you are using the most recent YouTube+ version. If you aren't then update it, restart the browser and see if the problem has **alerady** been fixed.

alerady -> already

**Comment by ParticleCore** [comment]
Thanks for the heads up, the wiki spell mistake has been corrected and I will try to push a fix for the incorrect detection.

**Comment by Drofseh** [comment]
I also got the same mistaken warning, on I believe the same video.

https://www.youtube.com/watch?v=DlLZVxNK3Jg

**Comment by Corruptinglyneedful** [comment]
I got this same warning on this same video.

**Comment by ParticleCore** [comment]
Sorry, for the delay, I have waited for another user to reply about another issue so that I could push two fixes at once. Version 1.8.3 fixes this problem, let me know if it works for you as well.

**Comment by Drofseh** [comment]
> let me know if it works for you as well.

Looks like it worked. I no longer get the warning on the video I linked.
