### ISSUE TITLE
Turn Off The Lights extension compatibility and video quality setting

### ISSUE THREAD

**Issue by mertkos** [ParticleCore/Particle#475]
Browser Name: Chrome

  Browser Version: 57.0.2987.110 (64-bit)

  Operating System: Windows 8.1

  Software Type: Extension

  Software Version: 1.8.2

  Userscript Manager: -

  Userscript Version: -

  Problem Description: For several weeks YouTube + no longer works with "Turn Off The Lights" Chrome extension's YouTube HTML5 atmosphere lighting feature. They used to work together before. I love both extensions. I use your extension to disable YouTube's loudness normalisation and Turn Off The Lights extension to add amazing ambient effects to YouTube videos.

  Steps to reproduce: 
Turn Off The Lights extension:
https://chrome.google.com/webstore/detail/turn-off-the-lights/bfbmjmiodbnnpllbbbfblcplfjjepjdn

The Turn Off The Lights extension's this feature requires YouTube HTML5 live ambient effects setting to be enabled from extension's settings. For you to easily find it, here's the screenshot of where this setting is located:
http://i.cubeupload.com/es9R0B.png

  Additional details: Thank you for taking your time to read this. I'll be so grateful if you help. Also thank you for developing this extension to give us a chance to disable YouTube's loudness normalisation. You are an awesome developer. Also you should also try YouTube ambient effects on your own browser. The two extensions together brings YouTube to future.

**Comment by mertkos** [comment]
Also "Default Video Quality" setting in YouTube + seems like not working properly like it was before. It looks like YouTube overrides your extension's quality settings as "auto quality". When I have high connection speed it loads videos as 4K from beginning as I selected 4K from your extension. I don't know it loads 4K by "auto quality" or your extension at the moment. Because when I have poor connection speed it loads 480p or 720p. Not the 4K. The extension's video quality override was working properly before. Even on poor connection speed it was loading 4K video (or 1080p if video has a maximum resolution of 1080p) directly from beginning. (Not switching to predefined quality after video starts like other YouTube auto HD extensions. For this reason I love your extension's video quality selection feature.) Now it loads videos as 720p or lower (like auto quality) even after I selected 4K from your extension. Over the setting cog it shows 4K icon but the video is 720p or lower.

Here's the screenshots of this issue.
480p: https://i.cubeupload.com/iQ8Q0L.png
720p: https://i.cubeupload.com/dwr5kB.png

Edit: It switches to 4K but not instantly like it was before. It switches to after 20-30 seconds later.

**Comment by ParticleCore** [comment]
Please do not couple issues, open a new one instead for the video quality problem you mention with all the details you included and remember to follow the troubleshooting guide to see if it really is a problem with YT+ or not. Each issue should be a new issue thread.

Regarding the original issue here, if they no longer work together then they are no longer compatible. I don't know if it was something the developer changed or I changed, but I do not have the time to make YT+ compatible other extensions. You could try asking the other developer if there is anything he can do.

**Comment by q1k** [comment]
[I had created this style](https://userstyles.org/styles/139690/youtube-simple-cinema-mode) a while back and only recently decided to put it up. When active when the video is playing the page will turn dark.

You can install it with stylish or stylus or any other fork of stylish. Or as a userscript with greasemonkey, tampermonkey etc.

**Comment by Keith94** [comment]
@q1k This style breaks the ability to toggle pause when clicking the video player. Known issue?

**Comment by q1k** [comment]
@Keith94 Hadn't realized... I had only checked on Firefox and it worked perfectly.
I have updated the style and it should work fine in Chrome too.

**Comment by Keith94** [comment]
Actually I'm using Firefox 55, but the issue is still not fixed for me. Please check it if you can.

**Comment by q1k** [comment]
I checked on Firefox Nightly 55 and it works fine for me. 
[Try this and see if it works](http://pastebin.com/cCvp3zR6). If that doesn't help, I don't know what else to do. There could be something on your end causing this.

**Comment by ParticleCore** [comment]
Please do not use this issue tracker for this kind of thing, it is preferred that you use a dedicated one instead.
