### ISSUE TITLE
Open thumbnail button not working

### ISSUE THREAD

**Issue by Mongogamer** [ParticleCore/Particle#478]
Browser Name: Firefox

Browser Version: 52.0.2

Operating System: Windows 7 64-bit

Software Type: Extension

Software Version: 1.8.3

Problem Description: 
The **Open thumbnail** button/function of the extension stopped working. To be more precise, instead of opening the thumbnail in a new tab it simply opens a blank tab. This issue was able to be reproduced on a version of Firefox 52.0.2 with multiple extensions as well as on a completely clean Windows 7 and Firefox 52.0.2 installation on a virtual machine.

Steps to reproduce: Open any YouTube video while having version 1.7.8 - 1.8.3 installed in Firefox and click on the **Open thumbnail** button.

Additional details: The function `getThumb()` relies on the data of `window.ytplayer.config.args.iurl_webp` which always returns undefined. It seems this value was removed by Youtube.

**Comment by ParticleCore** [comment]
Was already looking at it, it appears they moved it to a different path, will try to fix it as soon as I can.

**Comment by Mongogamer** [comment]
Managed to make a workaround for this issue. I haven't done extensive testing and the code is kind of dirty but it works well so far. Maybe you can use it as a base for a future fix.

```
function getThumb() {
	var img, imgheight, thumbresolutions, x, stopnow;
	img = new Image();
	imgheight = 0;
	thumbresolutions = ['maxresdefault', 'sddefault', 'hqdefault', 'mqdefault', 'default'];
	x = 0;
	stopnow = false;
	img.onload = function(){
		if(x < thumbresolutions.length && stopnow === false){
			imgheight = this.height;
			if(imgheight > 90){
				window.open(img.src);
				stopnow = true;
			}else{
				nextimage(x, thumbresolutions, img);
				}
			}
		}

	img.src = 'https://i.ytimg.com/vi/' + window.ytplayer.config.args.video_id + '/' + thumbresolutions[x] + '.jpg';

	var nextimage = function(){
		img.src = 'https://i.ytimg.com/vi/' + window.ytplayer.config.args.video_id + '/' + thumbresolutions[x] + '.jpg';
		x++;
	}
}
```

**Comment by ParticleCore** [comment]
Version 1.8.4 comes with a fix for this problem, let me know if it works for you too.

**Comment by Mongogamer** [comment]
Works on every video I tried so far. Glad it got fixed.
