### ISSUE TITLE
Option to remove video toolbar when paused

### ISSUE THREAD

**Issue by DAOWAce** [ParticleCore/Particle#482]
So when you pause a video there's now this toolbar that appears with videos on it. [Example](http://i.imgur.com/gdOTgsY.png)

I am requesting if you could possibly add an option that disables this.

With this new 'feature' I'm finding myself accidentally clicking on a video that comes up when I need to pause for just a moment.  Huge, huge annoyance.  Clicking the "x" only minimizes it for that video session, it doesn't remember it for later videos.

Additionally, is there anything you can do about the stuff that comes up at the end of a video?  Those GIANT boxes that show the user's profile box and other videos from them.  Disabling annotations doesn't remove it, and it blocks the last ~20 seconds of a video, which sometimes contains important things..

**Comment by ParticleCore** [comment]
That's something I will definitely add if I manage to make YT+ compatible with the upcoming YouTube Material Layout, but for now it will have to wait:

> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
