### ISSUE TITLE
the version in greasyfork need upgrade

### ISSUE THREAD

**Issue by czmecho** [ParticleCore/Particle#484]
https://greasyfork.org/zh-CN/scripts/9932-youtube

someone fork your project and upload your project. here:https://greasyfork.org/zh-CN/scripts/28576-youtube

**Comment by ParticleCore** [comment]
Thank you, I updated the userscript now in GreasyFork.

Another user already had told me about the other fork recently here: https://github.com/ParticleCore/Particle/issues/459#issuecomment-292688019
