### ISSUE TITLE
[Updated] YT+ is dropping Chrome support and moving to Opera

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#485]
EDIT: The Webstore team has restored the extension. I will see if things stabilize for the moment, if they do then I will not stop support for the Chrome browser

___

As a result of a recent situation explained in detail here https://github.com/ParticleCore/Particle/issues/483, I have decided to move the Chrome support to the Opera browser. The name has been changed from **YouTube Plus** to the codename **Particle** (which is the original name set precisely for a situation like this) due to requirements by the Opera reviewers, and expect the same to become global once the Material version of YT+ is launched.

Support for the Chrome users will continue to exist for a limited time, after that time ends no support will be provided for problems that exist only on Chrome.

I will also make it available to side-load ([Step 4](https://dev.opera.com/extensions/basics/)) the [Opera version](https://github.com/ParticleCore/Particle/tree/master/src/Opera), with the current downside of not having auto-update available, which is something I will try to find a solution for in the future.

**Comment by Corruptinglyneedful** [comment]
The problem with this is that Opera sucks at this point they are better off with Firefox or *shudder* Edge.

Can't you just make a userscript version?

**Comment by Corrodias** [comment]
There *is* a userscript version. At least, last I checked, ParticleCore intended to keep it going. It's just not getting updates until this whole Material redesign settles down and stops being a moving target.

**Comment by ParticleCore** [comment]
@Corruptinglyneedful All available versions are linked in the download section: https://github.com/ParticleCore/Particle/wiki/Download

There you can also find the userscript version.

**Comment by Corruptinglyneedful** [comment]
@Corrodias  Delete the cookie.

@ParticleCore You said you aren't supporting Chrome anymore, can't you just do that in the Userscript version?  That's what I meant.

**Comment by ParticleCore** [comment]
@Corruptinglyneedful There will be no fragmented support, users are free to use the userscript for any browser, but I will not be providing support for any problems that are specific to browsers that are not Firefox and Opera.

**Comment by Corruptinglyneedful** [comment]
@ParticleCore  So if there is a problem with the Userscript, specifically in Chrome, it will still not be fixed despite the fact that it is something you are actively maintaining that Userscript?

Am I understanding this correctly?

**Comment by ParticleCore** [comment]
@Corruptinglyneedful  I think I was very clear in the announcement: 

>Support for the Chrome users will continue to exist for a limited time, after that time ends no support will be provided for problems that exist only on Chrome.

That includes all YT+ versions: Extension, add-on and userscript. After that time is passed, any problems that exist only on Chrome, or any other browser that is not Firefox or Opera, will not receive support. If anyone wishes to provide support for those browsers then be my guest and fork the project.

**Comment by Corruptinglyneedful** [comment]
@ParticleCore Why are you not supporting Chrome through the userscript?  The userscript is not the same as Chrome extensions.

Are you just upset at Google, is that why?

**Comment by Corrodias** [comment]
To ask a related question, what does the extension version bring to the table that the script version does not, whether to users or to you? That is, why does it exist? I understand the explanation - you don't want to try to support more than a couple of browsers, and Chrome's repository has essentially banned the extension version - except for that.

For the record, **I'm** upset at Google for this and other things and don't like the way they never communicate with their users.

**Comment by ParticleCore** [comment]
@Corruptinglyneedful  I do not provide support to browsers that I do not use on a daily basis. This is something I have always stood by since when I first made the project public. I am upset at Google for what they did, but I harbor no negativity towards them or any sort of revenge. Their webstore was just a good place for plenty of users to discover this extension and that's the only reason I chose to adopt a second browser besides Firefox, otherwise it would have been just Firefox from day one and that was something I was considering doing.

With the webstore gone there are no reasons for me to continue using Chrome, the Opera addon store became my next logical choice for the very same reason I chose the webstore in the past, and now I have chosen to use Opera as my second browser.

I believe that I have explained everything as best as I could and I would appreciate if you didn't insist on this any longer, I am sorry if this isn't something you'd like to hear or if you still don't get it, but that's the decision I made and, like I said before, it does not forbid anyone from forking on their own and extend support by themselves for Chrome after the migration is completed.

@Corrodias The extension/addon versions exist for those users that do not want to install a userscript manager just to install the userscript. Additionally, quite a large number of extension/addon users are "vagrants", for them a userscript is something that they do not understand how to use and what they need in order to use it, making it hard for them to get it working.
While on the other way around, I made my choice to assure that everything in YT+ extension versions had to be available in the userscript version, no exceptions. This was to help bring more users to the Greasemonkey and Tampermonkey extensions (and others like it) as a way of showing my appreciation for the developers behind them. It also allows extreme flexibility, meaning that enthusiastic userscript users can just take the code apart and make their tweaked version the way they want, or even use the userscript on browsers that I do not provide support for, but actually works well, such as updated Chrome forks.

**Comment by Corruptinglyneedful** [comment]
@ParticleCore Actually you explained it just fine. I fully get it.  I use Firefox myself, I was just curious as to your reasoning.  I think Chrome is shite, honestly and yes like @Corrodias I do not like how Google handles their customer support, through that shitty forum.

Also, what do you mean by the webstore is gone?

I prefer Userscripts, honestly, easier to use, maintain, and update.

**Comment by ParticleCore** [comment]
>Also, what do you mean by the webstore is gone?

It is linked in the announcement: https://github.com/ParticleCore/Particle/issues/483

**Comment by Corruptinglyneedful** [comment]
@ParticleCore That's just the extension not the entire store.  You said they got rid of the webstore.

**Comment by ParticleCore** [comment]
This is what I really said:

>With the webstore gone ( . . . )

As in "I no longer can use the webstore to publish the extension" or "The webstore is no longer an option". 

This thread has already ran off course too much, I don't see any point on continuing with this. Hopefully what has been written is enough to satisfy the curiosity of others as well.

**Comment by ParticleCore** [comment]
It appears the Webstore has restored the extension, I will see if it remains up and if it does then I will not stop Chrome support.
