### ISSUE TITLE
Feature request: Zoom shortcut keys

### ISSUE THREAD

**Issue by Sokonomi** [ParticleCore/Particle#486]
Id like to suggest a feature : Zooming

I seem to be one of the very few souls on the internet who uses an ultrawide monitor, and unfortunately youtube is still denying the existence of letterbox videos, bordering it up instead. The result of this is ultrawide monitors get black borders on all 4 sides, rather than filling out the screen.

So I would like to see the ability to zoom in on boxed letterbox videos so it fills the entire screen again.

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
