### ISSUE TITLE
full-screen conflict

### ISSUE THREAD

**Issue by Jason4774** [ParticleCore/Particle#487]
Youtube + and [YouTube Auto Buffer & Auto HD](https://greasyfork.org/zh-CN/scripts/494-youtube-auto-buffer-auto-hd) conflict, causing youtube + full-screen button can not be used normally.Can you help me?

**Comment by ParticleCore** [comment]
They are not compatible with each other, that script makes too many core changes to be worth "fixing" on my end. If the author is willing, then he could try to make it work together on his end, in which case you should contact him on the greasyfork forum.
