### ISSUE TITLE
Youtube+ completely invisible when user signed in

### ISSUE THREAD

**Issue by wirandhika** [ParticleCore/Particle#488]
windows 10 | mozilla firefox 53.0(64bit)
the option to restore the youtube classic theme are visible when user didnt sign in
but, once user signed in its not visible at all

and also, when user signed in. and try to watch video and then scrolled down the page. the video is breaking, turned into small video screen,and stay as it is even user already scroll up 

and the default option from youtube material also disappear 
so by default, if user sign in youtube material layout will be set

**Comment by ParticleCore** [comment]
Please follow the instructions as it was requested, here you can find two ways to exit the material layout: https://github.com/ParticleCore/Particle/wiki/Restore-classic-YouTube

If the running man icon is not present then click on your account icon and select the last option "Restore classic YouTube".

I will update those screenshots to include the case for when a user is signed in.
