### ISSUE TITLE
Blacklist no longer working

### ISSUE THREAD

**Issue by max6166** [ParticleCore/Particle#489]
The blacklist seems to have stopped working recently. The thumbnail icon to blacklist a channel no longer appears, and videos from blacklisted channels are now showing but with the channel name missing.

**Comment by ParticleCore** [comment]
The blacklist is working correctly on my end.

Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
Version 1.8.5 fixes this problem, let me know if it works for you too.

**Comment by max6166** [comment]
The blacklist seems to be working again, but my Trending page is now empty.

**Comment by ParticleCore** [comment]
Completely forgot to test that page, I am also having the same problem, will address it asap.

**Comment by ParticleCore** [comment]
Version 1.8.6 should now have all problems fixed, let me know if you find any other issues related to this one, or open a new issue if you find other problems unrelated to this one.

**Comment by max6166** [comment]
Looks great! Thanks for the quick fix!
