### ISSUE TITLE
Clicking the YouTube logo from the YT+ settings page does not take me to the YT homepage

### ISSUE THREAD

**Issue by n-o-o-b** [ParticleCore/Particle#492]
Browser Name: Firefox

  Browser Version: 53.0

  Operating System: Windows 10

  Software Type: Add-on, I think. Got it from the Firefox add-ons store.

  Software Version: 1.8.6

  Problem Description: If I click on the YouTube logo from YouTube Plus' settings page, it doesn't take me to the YouTube homepage. The red bar goes across the top of the screen but it doesn't take me anywhere. Edit: the same goes for the Home, Trending and Subscriptions buttons.

  Steps to reproduce: Open YT+ settings page, click on YouTube logo in top left.

  Additional details: I also would like to use this opportunity to ask a couple of questions. Firstly, is having the "Use the HTML5 player when possible" box ticked or unticked closer to what YouTube would do by default without YT+ installed? Secondly, I read on here that YT+ does not have an effect on YT videos embedded in third-party websites. Does this mean there is no way to remove the bar showing recommended/similar videos that appears in the video screen of embedded videos when I pause the video?

Lastly, is there any way you could add the option of completely hiding the advanced options that come with YT+ from the video page, including the small hamburger button in the corner? I read that you're not accepting any more feature requests but I just wanted to put this out there so that it's on record.

P.S. I would just like to say that I am very grateful for the existence of this add-on, so thank you.

**Comment by ParticleCore** [comment]
The pages are changing, but you never closed the settings menu so it appears that the page never changes. If you close it you will see the pages changing.

As for your question, unticked is the default without YT+ installed.

YT+ does not affect anything outside the youtube.com domain, including embedded videos.

As for your request, it has already been asked before: https://github.com/ParticleCore/Particle/issues/31

**Comment by n-o-o-b** [comment]
I'm assuming the correct way to close it is to once again click on the YouTube+ button. And I'm also assuming that it's not that easy to make it redirect to the homepage from the settings page? Either that or you wanted to prevent people from accidentally closing the the settings? The only reason I'm saying this is that it seems the intuitive thing for it to do, to redirect to the homepage. In my opinion you should also add a close button somewhere at the top near Reset and Save to make it clearer how to close the settings.

In any case, thanks for clarifying the answers to my questions.

**Comment by ParticleCore** [comment]
Yes, to close the settings you can either click on the YT+ button again or click on an empty area around the settings menu.
