### ISSUE TITLE
Particle Alpha version for YouTube Material Layout is now public

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#493]
EDIT: An update regarding this has been posted here: https://github.com/ParticleCore/Particle/issues/504

___

As of the next version of YouTube Plus the name will be changed to the original codename Particle for the upcoming Material Layout compatible version, this means that soon YT+ will no longer be the name of this extension and it will be replaced with Particle.

As previously mentioned, this process will be slow and full of bugs. For now the development will be around the core code, meaning that only the userscript version will be developed in the beginning.

The Alpha versions should always be minimally functional and bugs are expected, in which case I appreciate any and all reports that interested users want to contribute if they wish to take part on this "public alpha" testing. Do not expect the alpha version to be a stable version for normal day use, it is a work in progress and the main focus should be for testing.

For now it is only capable of controlling video auto play (including the channel trailers) and there is no easy toggle options working yet, this means that the option to not play videos automatically permanently enabled in the code until I have time to work the settings toggles correctly.

Another difference from the previous YT+ is that now the settings menu will be located in a dedicated page built by the userscript itself, this will hopefully reduce the confusion caused to extension users looking for the options button in their browser extension list. While no button is yet available to access it, it can be accessed via the following link after installing the userscript: https://www.youtube.com/particle-settings

A fork has been created just for the Particle development until I can find a better repository structure to avoid having to share this one between two different versions.

The Particle Material version can be found in the respective fork:  https://github.com/ParticleCore/Particle/tree/material

For anyone interested in participating on this next chapter: the ride will be bumpy.

**Comment by ParticleCore** [comment]
Closing in favor of a more recent update in https://github.com/ParticleCore/Particle/issues/504

**Comment by rosemariesoleil** [comment]
les video ne  marche  pas  sur  youtube merci

**Comment by ParticleCore** [comment]
@rosemariesoleil English only.

**Comment by zZmanYTB** [comment]
@ParticleCore When I want to reset my YT to old one I can't because of this : 
https://screenshots.firefox.com/f3sU3fFQTMMVnPIt/www.youtube.com
PLEASE HELP!

**Comment by ParticleCore** [comment]
@zZmanYTB Search the next time: https://github.com/ParticleCore/Particle/issues/550
