### ISSUE TITLE
Allow disabling double click=fullscreen

### ISSUE THREAD

**Issue by PiotrGrochowski** [ParticleCore/Particle#498]
In a youtube, doubleclicking a video fullscreens it. This is annoying issue when you want to move forward a fraction of a second to pause on the right moment.

**Comment by Eisys** [comment]
Just use the period and comma keys when the video is paused. This action moves either back or forward one frame.
Youtube+ has this built in as well. Shift + arrow keys!

**Comment by ParticleCore** [comment]
Like @Eisys said, you can use the YouTube frame by frame shortcuts or even the extra shortcuts in the extension for the same effect: https://github.com/ParticleCore/Particle/wiki/Features#adv_frame

**Comment by PiotrGrochowski** [comment]
Just because you can use these keys to move a frame doesn't mean that I don't want double click=full screen removal. For example, what if the pause is unstable and I end up fullscreening it? Please, but PLEASE remove this double click≠double click but double click=full screen mess.

**Comment by ParticleCore** [comment]
In that case that is a different thing, but still read the readme file:

>Due to time and framework limitations I am unable to accept any more feature requests.

Also this extension is at the end of its life and I am focusing the rest of my free time into building a new extension just for the new YouTube layout.
