### ISSUE TITLE
Youtube new dark theme

### ISSUE THREAD

**Issue by iHanyAdel** [ParticleCore/Particle#499]
so recently youtube launch a new dark theme which is super cool

https://www.youtube.com/new

but unfortuanly the plugins still not supported it and after i try the dark theme the plugin says i have to restore my youtube to classic look 

so i hope the new dark theme may be implement to the plugin

**Comment by ParticleCore** [comment]
Please use the search box the next time: https://github.com/ParticleCore/Particle/issues/448
