### ISSUE TITLE
Open Video Thumnail functions opens Channel Icon instead of Video Thumbnail

### ISSUE THREAD

**Issue by naobug** [ParticleCore/Particle#501]
Instead of open the Video Thumbnail, the function opens Channel Icon instead.
FF 53
YT+ 1.8.6

Here was a similar issue, https://github.com/ParticleCore/Particle/issues/478 but not the same.

**Comment by ParticleCore** [comment]
Please provide the steps to reproduce this problem with an example video.

**Comment by naobug** [comment]
I first thought it only happens on videos from channels that you are not subscribed to. But I also found a user I am subscribed to where it opens the channel Icon instead of video thumbnail.

For example on his videos the feature opens the channel icon:
https://www.youtube.com/channel/UC2dBZuI6gS-jv7PCIDXkXag/videos
here as well:
https://www.youtube.com/user/Trizzle126/videos

If I use the same Firefox Tab where I got shown the channel icon of https://www.youtube.com/user/Trizzle126/videos, then select this channel on the left list with my subscriptions https://www.youtube.com/user/Olli43/videos then use the thumbnail function, then it showns my the channel I con of https://www.youtube.com/user/Trizzle126/videos on the videos of Olli43.

If I use a new tab to open the channel of Olli43, then the thumnaill function at least shows the correct channel Icon in large.

**Comment by ParticleCore** [comment]
Now I was able to reproduce the problem, it happens when you open a video from a channel page. A simple temporary fix is to just refresh the page when that happens, will try to push the fix as soon as I can.

**Comment by ParticleCore** [comment]
Sorry for the delay. Version 1.8.7 contains a fix for this issue, let me know if it works for you as well.
