### ISSUE TITLE
"Loop" issue

### ISSUE THREAD

**Issue by PiotrGrochowski** [ParticleCore/Particle#503]
I have an issue called "Loop". By default, when a video ends, it loops with YouTube+. When I toggle loop, it still loops. When I toggle loop second time, it no longer loops. Please fix "Loop".

**Comment by ParticleCore** [comment]
Please follow the instructions like it was asked before opening the issue: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you still have an issue please follow the instructions in the previous reply.

**Comment by PiotrGrochowski** [comment]
I reinstalled YouTube+, it worked, but after a few days "Loop" came back to haunt me. :(
