### ISSUE TITLE
YouTube+ / Particle current direction is a mess, here is the final plan for the future of this extension

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#504]
For those of you that haven't been following the events around YT+ lately, [the extension was placed on EOL support](https://github.com/ParticleCore/Particle/issues/448) due to the new YouTube layout being drastically different than the classic layout - demanding a complete rework of the extension - and my limited time to spare for working on the extension. On top of that the extension was also banned from the Chrome webstore with no reason given, [a situation](https://github.com/ParticleCore/Particle/issues/485) which led me to move the extension to Opera and drop Chrome once the new extension version is finalized.

Fortunately I was able to finally find a way to work around the complexity that is the new YouTube layout and [I am currently working](https://github.com/ParticleCore/Particle/issues/493) from scratch on a new and modular version of the extension just for the new layout, but this will still be a slow process. 

Unfortunately, with all of this happening in such a short period of time a mess was generated. Because the Opera add-on store did not accept the YouTube name in the extension I had to change it to Particle, but I was planning on using that name for the new version of the extension and now I have this name collision on the Opera side if I try to keep the same name for a different version. Another issue that has raised is the repository itself, it is called Particle as well, but it is being used for the YouTube Plus name.

You see now the mess that this is heading into and I have decided to re think the plan while I am still on an early stage of development for the new extension.

I have finally made a decision and the new extension version will be called **Iridium** and it will be located in the respective repository located here: https://github.com/ParticleCore/Iridium

As of today the entire development of this version will be done on that repository and this one (Particle) will remain as it is for the YouTube Plus version. This way I am able to keep everything organized and avoid development collision regarding wikis, issues and other unforeseen problems that could occur due to the way things were now.

I apologize for this mess that I have done, but hopefully it will just be a stepping stone that was prevented from becoming an avalanche of problems.

**Comment by ddd111ddd** [comment]
Don't worry, the name is not that important. Google screwed us twice, first with the layout changes and now with the extension ban. Chrome is doing things that would make IE6 jealous.

ps: the developer from YouTubeCenter started a [project](https://github.com/YePpHa/maia-yt) to deal with the new material layout

**Comment by rEnr3n** [comment]
The name reminds me of this browser which is based on Chromium. https://iridiumbrowser.de/
Want to change the name one more time to avoid confusion?

**Comment by ParticleCore** [comment]
@rEnr3n If that were an extension then I would consider change name again, but I checked and I did not find any with this name. A browser is not the same thing as an extension, the name will stay.

**Comment by DFNCTSC** [comment]
So much wasted potential. So much time wasted on choosing a name, all of which sound stupid and pretentious -- Particle/Iridium oooh so edgy you know science terms. This is the death of this extension.
Good luck with your future endeavors!

**Comment by Corruptinglyneedful** [comment]
So wait does that mean Youtube Plus is no longer getting updates and is just going to be static and if I want  a more updated version I have to go to Iridium?

**Comment by ParticleCore** [comment]
@Corruptinglyneedful YT+ will only end when the new layout is officially released. Until that day arrives any bugs and problems with YT+ will be resolved as quick as possible like always, that part never changed.

**Comment by Corruptinglyneedful** [comment]
OK, thank you Mr. Particle, sir.

**Comment by link6155** [comment]
I'm not going to switch browsers just for one extension. I can understand your frustration with the Chrome Web Store but I think it is ill-advised to switch to Opera, a browser that has privacy concerns, a much smaller user base, and relies heavily on Chromium still.

**Comment by ParticleCore** [comment]
@link6155  I will not, I am going to keep support for FF and Chrome only for Iridium.

**Comment by Corruptinglyneedful** [comment]
There's also Userscripts people.  Those support everything.  It's not all about browser extensions.

Well w/e you support, please for the love of God put in an option to hide notification numbers in tabs.

They are truly madening.

**Comment by s0j0urn** [comment]
Hi,

My comment is unrelated to this announcement but to what happened with chrome extension in particular to the discussion [https://github.com/ParticleCore/Particle/issues/528](#528 ).

I just wanted to let you know that the work you have done with Particle is great and you are morally as well as practically completely right to make money from it. The only thing that could have been done otherwise is making an announcement beforehand that the extension is changing ownership. I have read about it and will not go into discussing that. 

I do not understand why people expect that they should get software for free and on their own terms. It takes time, money and in some case health to develop skills at your competence level and then applying them to come up with something as useful as Particle. I am sure most of the commenters in that thread who disagreed with or tried to disparage you will continue using Particle in one form or another.

**Comment by Corruptinglyneedful** [comment]
What's your point though?

**Comment by s0j0urn** [comment]
@Corruptinglyneedful 
That he has done good work. I am thankful.
People may not understand how S/W development works and can be ungrateful.

**Comment by BiZZKeryear** [comment]
I dunno if the new design is released by now ... van't tell ... but the extension has stopped working ... ads are played and videos as well ... (I came back ... and windows decided to reboot my system in meanwhile ... and hundreds of open videos pages played in background ... it was a mess)
I use userscript / scriptmonkey for ages to run extensions ... since google has become a dick when it comes to yt extensions ... and lately YT has become a dick in general ...

**Comment by Corruptinglyneedful** [comment]
Yup, autoplay blocking not working for me either.  Currently looking for alternative since this has been deprecated

**Comment by ParticleCore** [comment]
Do not post unrelated issues here, open in a new one instead and this extension has not been deprecated until the Material layout can no longer be disabled.

**Comment by Corruptinglyneedful** [comment]
Hey, @ParticleCore how do you actually disable the new material layout if you get it?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Particle/wiki/Restore-classic-YouTube

**Comment by bel57** [comment]
Now the new layout is applied to everyone, seems that you can't opt out (plus they refreshed the logo).
Is your script somehow compatible, or still having issues?

Good luck!

**Comment by ParticleCore** [comment]
@bel57 Everything is already explained in the first post.

**Comment by Corruptinglyneedful** [comment]
Where is the change log for updates?  I can't find one and I don't understand the code I'm reading in the src tab.  Is there no changelog?  I want to know what's getting updated from version to version.

**Comment by sergeevabc** [comment]
There is “[Get me Old Youtube][1]” userscript which switches New design to Old one ( (as long as available).

[1]: https://greasyfork.org/en/scripts/32906-get-me-old-youtube

**Comment by ParticleCore** [comment]
Closing due to https://github.com/ParticleCore/Particle/issues/609
