### ISSUE TITLE
Subscribers count

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#505]
Any chance of showing the full number of subscribers to the right of the subscribe button, on channels, hovercards and videos (uploader).
Seeing something like 1M is very stupid and very inaccurate is it 1 or close to 2M..? For example CollegeHumor says 11M but they are just 250k short of 12M, so it would be better to show the whole number like it was until recently.
So can you please add this option to youtube+, it would be very helpful.

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
