### ISSUE TITLE
Seriously conflicts with extensions VidIQ & TubeBuddy

### ISSUE THREAD

**Issue by asencilius** [ParticleCore/Particle#506]
Browser Name: Chrome
Browser Version: Version 58.0.3029.110 (64-bit)
Operating System: Windows 7/Windows 8/Windows 8.1/Windows 10
Software Type: Userscript
Software Version: 1.8.7
Userscript Manager: Tampermonkey
Userscript Version: 4.2.7
Problem Description: 
Seriously conflicts with extensions VidIQ & TubeBuddy
If TubeBuddy is enabled, YT+ don't save settings
If VidIQ enabled, he is invisible with YT+.

**Comment by ParticleCore** [comment]
If they do not work well with each other then they are not compatible and should not be used at the same time. You'll have to ask those extension authors if they are willing to make their extensions not break YT+.

**Comment by asencilius** [comment]
VidIQ & TubeBuddy works fine without YT+
