### ISSUE TITLE
How to change the "Floating player width" parameter

### ISSUE THREAD

**Issue by Yamazaki-wu** [ParticleCore/Particle#508]
Change the size of the "Floating player width" parameter

**Comment by ParticleCore** [comment]
You can read how to do it here: https://github.com/ParticleCore/Particle/wiki/Features#floating_player_width

**Comment by Yamazaki-wu** [comment]
[image: 内嵌图片 1]
Very sorry, i did not find where can I change the size of the place or
button? And the player width in the options can only be 350, can not be
changed.

2017-06-03 2:17 GMT+08:00 Particle <notifications@github.com>:

**Comment by ParticleCore** [comment]
YT+ Settings > Video > Floating Player Width

![ss](https://cloud.githubusercontent.com/assets/9222661/26753818/696473e8-485e-11e7-96c3-8c8c23f54563.png)


The minimum width is 350, which is explained in the previously linked feature description. Don't forget to click the blue "Save" button on the top right so the new size is saved.

**Comment by Yamazaki-wu** [comment]
Sorry, the original selected text box to see the text color is gray, that
can not change so there is no fill in the number of attempts.

2017-06-03 21:14 GMT+08:00 Particle <notifications@github.com>:

**Comment by ParticleCore** [comment]
Which browser are you using?

**Comment by Yamazaki-wu** [comment]
firefox

2017-06-03 21:24 GMT+08:00 Particle <notifications@github.com>:

**Comment by ParticleCore** [comment]
Please follow the troubleshooting guide as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

And then try to set any number bigger than 350 inside that box and press save, restart and see if it saved.

**Comment by Yamazaki-wu** [comment]
Thank you for your patience, according to the previous answer, the problem
has been resolved.

2017-06-04 5:31 GMT+08:00 Particle <notifications@github.com>:
