### ISSUE TITLE
YouTube Plus icon looks weird with a dark mode..

### ISSUE THREAD

**Issue by oblivss** [ParticleCore/Particle#513]
YouTube Plus needs some sort of setting so that the YouTube Plus icon can be white, because I know there are a lot of people who use YouTube Plus with some sort of dark mode extension.

**Comment by ParticleCore** [comment]
YT+ does not provide support for dark modes, there's just no way of telling when a user is using them and there are no intentions of adding new features now.

>Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

It falls on the users or theme developers the responsibility to handle the correct contrast of the YT+ UI elements, if they wish to improve it.
