### ISSUE TITLE
Script for Loudness Normalization

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Particle#514]
Browser Name: Chrome

  Browser Version: 59.0.3071.104 (Official Build) (64-bit)

  Operating System: Windows 10 Pro

  Software Type: Tampermonkey

  Problem Description: I need a scrip to put in Tampermonkey to disable the loudness normalization

**Comment by ParticleCore** [comment]
This is not a place to request custom made scripts, please try asking on dedicated forums such as Greasyfork.
