### ISSUE TITLE
Logo is wrong size.

### ISSUE THREAD

**Issue by redperson11** [ParticleCore/Particle#515]
The Main logo no matter where ever it is is always the wrong size.
![screen shot 2017-06-21 at 8 41 19 am](https://user-images.githubusercontent.com/19433347/27384589-6cafc78e-565d-11e7-9ce1-b37a4d7c9afa.png)
I fix it by setting the background size to 60%.
![screen shot 2017-06-21 at 8 42 40 am](https://user-images.githubusercontent.com/19433347/27384650-a083185e-565d-11e7-9fc6-7c91f2f85683.png)

**Comment by ParticleCore** [comment]
I do not have this problem. Please follow the troubleshooting guide as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having troubles please follow the above instructions.
