### ISSUE TITLE
Chrome store still has the app "Particle

### ISSUE THREAD

**Issue by Kontorted** [ParticleCore/Particle#516]
You state that Chrome support will be dropped due to the app being taken down, with no notice. 
I can affirm it is still uploaded.
I am in Canada, if that means anything for you.
Proof:
http://hnng.moe/f/S86

**Comment by ParticleCore** [comment]
I know, I clearly indicated everything in the same post that the situation has been resolved:

>EDIT: The Webstore team has restored the extension. I will see if things stabilize for the moment, if they do then I will not stop support for the Chrome browser

https://github.com/ParticleCore/Particle/issues/485

The issue has been left opened for the time being so that previous readers have a chance to read the update.
