### ISSUE TITLE
Problem with "show how long the video has been published"

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#517]
Just recently I noticed that instead having the "ago" part, it adds the number of views next to the published date.
This is on firefox 54, with greasemonkey 3.1.1 and the userscript 1.8.7

**Comment by ParticleCore** [comment]
Cannot replicate, it is till adding the relative time correctly for the videos that I tested on. Please follow the report instructions as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having troubles please follow the above instructions.
