### ISSUE TITLE
[Feature] Full browser mode by default

### ISSUE THREAD

**Issue by Symbai** [ParticleCore/Particle#519]
I would like to request an option to enable full browser mode by default instead of clicking on the button each time. (If i fit player to 100%, it does not center the video. I have to scroll down every time so I would like to use full browser mode then)

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md

Also: github.com/ParticleCore/Particle/wiki/Features#adv_fullbrowser

This means that once activate it stays activate and it is only turned off when you exit the full browser mode or turn it off manually.
