### ISSUE TITLE
Redirect to homepage when visiting a blocked channel/video via a link

### ISSUE THREAD

**Issue by andorank** [ParticleCore/Particle#523]
Like https://addons.mozilla.org/en-US/firefox/addon/video-blocker does.
> Toggle if you want to be redirected to the homepage when you visit a video that should be blocked (e.g. via a link).

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
