### ISSUE TITLE
Invasive permissions in latest Chrome update

### ISSUE THREAD

**Issue by wickles** [ParticleCore/Particle#527]
Latest Chrome update requests new permissions: 
* Read and change data on (all) websites visited
* Manage apps, extensions, and themes

These seem highly excessive, since the extension should only need to read and change data on youtube.com. Please fix or explain the change? Thanks

**Comment by ParticleCore** [comment]
Hello Wickles, those are not my changes, the Chrome extension has changed ownership, I no longer have any control over it.

I am going to inform about this.

**Comment by q1k** [comment]
First Stylish and Userstyles.org "changed" ownership and now this.
Such a shame...

**Comment by rogeriomarques** [comment]
What a sleazy move!

**Comment by alphapapa** [comment]
The extension "changed ownership"?  I don't understand.  Who changed its ownership?  Who owns it now?  Why was it changed?  How should we install it now, from where?  Is the extension now hostile?

**Comment by Caraxi** [comment]
The original extension is now infected with adware. remove at all costs.

**Comment by RayKoopa** [comment]
@ParticleCore Can't be any more dubious! Bye and thanks for your originally great work.

**Comment by vovokrall** [comment]
What?! It changed ownership and you didn't warn us about it? Now it's infected?! Not cool!

**Comment by OmerSchechter** [comment]
This is my solution:
https://greasyfork.org/en/scripts/9932-youtube
https://greasyfork.org/en/scripts/9932-youtube/code

Works perfectly. No invasive permissions.

**Comment by ParticleCore** [comment]
I have updated the announcement in #528  with information regarding this situation.
