### ISSUE TITLE
Not an issue, just a comment

### ISSUE THREAD

**Issue by dinosw** [ParticleCore/Particle#532]
This is not an issue, but simply a comment.
I use Vivaldi Browser, and run your script with TamperMonkey without any issues.
I just thought that you would like to know, that there is an additional browser where your script runs perfectly =)

I have also tested it with Pale Moon + Gurilla Scripting, where it also seems to work just fine. However, I have only tested it for a short time with this setup.

**Comment by ParticleCore** [comment]
Thanks for the information, the extension should be compatible with a wide range of Firefox and Chrome forks, but I only provide bug support to the browsers that I use.
