### ISSUE TITLE
YT Notifications, thumbnails overlapping text

### ISSUE THREAD

**Issue by harl** [ParticleCore/Particle#536]
Firefox 54.0.1 (32-bit, stable channel)
Particle/YT+ 1.8.7

In YouTube's notifications drop-down, the text preview is overlapped by the video thumbnail.
I'm experiencing this issue only with YT+ enabled (and no other scripts or userchrome).
To the best of my knowledge, this isn't related to: cookies, cache (both cleared), this particular browser (or even this PC (my mom's), as this also happens on my own (same versions of FF & YT+) and she probably never changed any settings).
If there's anything I can try/do to help solve this issue, though, please let me know.

![particle_004](https://user-images.githubusercontent.com/1159811/28621494-73b96b50-7211-11e7-8d12-9ae8342f2863.png)
![particle_noparticle_006](https://user-images.githubusercontent.com/1159811/28621504-7b6fdcda-7211-11e7-99a2-60301bef06fe.png)

**Comment by ParticleCore** [comment]
It is very likely YT+ doing that, will try it on my end to see what is causing it.

**Comment by ParticleCore** [comment]
Sorry for the delay, version 1.8.8 should fix this problem.

**Comment by harl** [comment]
Thank youuuu 🐺
