### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Tomatoide** [ParticleCore/Particle#538]
Browser Name: Firefox

  Browser Version: 54.0.1 (64bit)

  Operating System: Windows 10 1703

  Software Type: Extension

  Software Version: 1.8.7

  Problem Description: Nasty memory leak that eventually leads to total system freeze. I've been troubleshooting this for a week now but it seems that YT+ is the culprit. (tried everything in the troubleshooting guide)

  Steps to reproduce: 1. Open a youtube video and play it.
                                 2. Leave the video playing for a minute
                                 3. Open about:performance in another tab
                                 4. Notice how memory starts shooting up for the youtube process
                                 5. Notice the lag in the youtube tab and eventually system freezes

Additional notes: my settings:
{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": false,
  "GEN_INF_SCRL": false,
  "GEN_BLUE_GLOW": true,
  "GEN_PPOT_ON": false,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "large",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": false,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": false,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": false,
  "VID_PPOT_SZ": false,
  "VID_PLR_HTML5": true,
  "BLK_ON": true,
  "floaterX": 2000,
  "floaterY": 2000,
  "firstTime": false,
  "volLev": 50,
  "advOpts": false,
  "blacklist": {},
  "extLang": {},
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": true,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": false,
  "GEN_YT_LOGO_LINK": false,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": false,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": false,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": false,
  "VID_PLR_FIT": false,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_INFO": false,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": false,
  "VID_PLR_CC": false,
  "VID_PLR_ALVIS_WDTH": false,
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": true
}

Also I get this error in the console:
TypeError: k.Nn is not a function               base.js:3999:7
	y0 https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:3999:7
	g.h.Gj https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:7061:312
	bound  self-hosted:917:17
	g.h.W https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:5739:258
	g.h.W https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6033:198
	g.h.Is https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:7208:198
	g.h.W https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:5739:258
	g.vG.prototype.W https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:5802:52
	uV https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:3432:18
	g.h.Ix https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6517:410
	FF.prototype.then https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:5788:2306
	g.h.Mw https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6513:123
	AV https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:3384:399
	CV https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:3385:29
	E1 https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:4162:363
	FZ https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:4201:45
	g.h.Vd https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6575:69
	g.h.Vs https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6915:79
	g.h.KR https://www.youtube.com/yts/jsbin/player-vfl_oYWG-/en_US/base.js:6914:348
	bound  self-hosted:913:17

**Comment by ParticleCore** [comment]
I just tested with your configuration on a 30+min video, there is no memory leak

![ss](https://user-images.githubusercontent.com/9222661/28936995-ead41aec-7878-11e7-8b39-0cd3e353620e.png)


I also don't have the errors you had, but that doesn't mean much because that source file is often different for all users. I use Firefox and this extension on a daily basis for over 6h in a row, never did any memory leak with it.

I know you already said that you tried everything in the troubleshooting, but have you really tested this problem on a new Firefox profile and only YT+ installed and with it uninstalled to see if the problem still happens with the extension running and not when it is not running?

**Comment by ariefpizzuti** [comment]
It happened to me too .its kinda random .sometimes it happened sometimes not .if you sometimes view an old video .theres a chance the leak will happen .it'll suck your ram and cpu until that tab become freeze .using latest chrome+tampermonkey .iridium didnt have this problem .

**Comment by ParticleCore** [comment]
If it is random then it is very possible that the problem is not caused by YT+, but without a way for me to replicate it there is no way I can fix it, which is why it is extremely important that the problem is really caused by the extension as best as possible and that I can make it happen on my end so that I can find the cause and try to fix it.

**Comment by ParticleCore** [comment]
Also make sure that you are **not** using YT+ with the new YouTube Material Layout, YT+ is not compatible with it.

**Comment by ariefpizzuti** [comment]
Got it .I'll eventually switch to new layout+iridium anyway ,but youtube+ with the old layout is godly .Anyway ,any ETA on iridium extension ?

**Comment by ParticleCore** [comment]
No ETA, it will be ready once it is feasible to me.

**Comment by Tomatoide** [comment]
So today the memory leak is suddenly gone! Tried to check if anything has changed and all I have found was 2 updated extensions: h264ify and google search link fix.

**Comment by ParticleCore** [comment]
It was probably a bugged YouTube player source code that was generating a cascading error and you finally received a different player source code with the problem fixed.
