### ISSUE TITLE
Youtube+ extensions causes issues with click events for a youtube video element

### ISSUE THREAD

**Issue by anonym24** [ParticleCore/Particle#542]
https://bugzilla.mozilla.org/show_bug.cgi?id=1389813

![screenshot_1](https://user-images.githubusercontent.com/8851301/29248592-80de3326-8024-11e7-9d06-2a909d31fd56.png)

So when I disable Youtube+ then my extension works ok, I can override left and right click events for a youtube video element

What causes this behavior when Youtube+ is enabled and it doesn't allow to override clicks events of this element for other extensions?

```
var clickVideoMode = 2; // 0 - no override, 1 - right click override, 2 - left click override

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    alert("OK");
});

function clickVideo() {
    var clickEvent;
    if (clickVideoMode == 1) {
        clickEvent = "contextmenu";
    } else {
        clickEvent = "click";
    }
    var videoPlayer = document.getElementsByClassName('html5-main-video')[0];
    //alert(document.getElementsByClassName('html5-main-video').length);
    if (videoPlayer) {
        videoPlayer.addEventListener(clickEvent, function(event) {
            event.stopPropagation(); // stop pause/play video on the left click
            event.preventDefault(); // hide context menu if we right click;
            chrome.runtime.sendMessage({test: "test", redirect: window.location.href});
        });
    }
}
```

background.js:
```
chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    if (request.test == "test") {
        chrome.tabs.query( {currentWindow: true, active : true}, function(tabs) {
            chrome.tabs.sendMessage(tabs[0].id, {greeting: "test"});
        });
    }
});
```

So alert message won't appear if Youtube+ extension is enabled

**Comment by ParticleCore** [comment]
This issue tracker is not for the development of other extensions. If your extension does not work with YT+ enabled then they are not compatible with each other. Alternatively you can try to capture the clicks with the useCapture set to true, might be able to capture the events before they can be intercepted.

**Comment by anonym24** [comment]
I'm just curious what causes this in your code?
