### ISSUE TITLE
ntmxser.com Subframe

### ISSUE THREAD

**Issue by Jonatino** [ParticleCore/Particle#545]
What is this process that is running when the Particle extension is enabled?

https://dl.dropboxusercontent.com/s/qeqhvv75sj7ypx4/chrome_2017-08-26_00-10-05.png

**Comment by Zarggg** [comment]
It's probably related to the advertising inserted by the new owner of the Chrome Extension.

Particle is no longer involved with the Chrome Extension version of this script. I suggest you remove the extension and run the userscript with Tampermonkey or something similar.

**Comment by Jonatino** [comment]
@Zarggg Thanks! 🍻

**Comment by ParticleCore** [comment]
Read https://github.com/ParticleCore/Particle/issues/528
