### ISSUE TITLE
Video autoplay prevention not functioning as of ~29th Aug 2017

### ISSUE THREAD

**Issue by Xaphiosis** [ParticleCore/Particle#549]
Less than 24 hours ago, when I loaded a video on youtube, the video would not automatically play. This functionality no longer succeeds. I am using the latest version of the user.js variant in src/Userscript, on a chromium-based browser (in this case, Vivaldi).

**Comment by Xaphiosis** [comment]
Duplicate of #548, whoever wrote that types faster than me :)

**Comment by zvit** [comment]
Same issue. using ver 1.8.8, latest ver FF. Youtube autoplays videos even though I have "Autoplay videos" unchecked.
