### ISSUE TITLE
Blue warning box about new YT layout being incompatible with YT+ covers option to revert to old layout

### ISSUE THREAD

**Issue by DarionGey** [ParticleCore/Particle#550]
This makes it impossible to see how to revert without first disabling YT+. So the position of the blue warning box needs to be moved.

![yt - copy](https://user-images.githubusercontent.com/31485812/29886952-c4aea940-8db3-11e7-9164-89d2d3541649.png)

**Comment by ParticleCore** [comment]
You can zoom out in your page temporarily or temporarily disable the extension as a work around.

**Comment by DarionGey** [comment]
I already fixed it for myself, I just wanted to let you know that other people will have an issue with it so you could fix it. If they don't know the option to revert is there (and YT always change it around) they won't know to use the workaround unless they come here, which most won't. 

You should really move the position of the blue box. This issue should not have been closed.

**Comment by DarionGey** [comment]
Listen, I have zero experience of coding anything, I can barely put in my door alarm code, but I fixed this issue by searching the code and guessing that removing 'right' and replacing it with 'left' might work. It does work. Why not just change the code like I did?

}
            function isMaterial() {
                var temp;
                temp = document.querySelector("ytd-app, [src*='polymer'],link[href*='polymer']");
                if (temp && !document.getElementById("material-notice")) {
                    temp = document.createElement("template");
                    temp.innerHTML = //
                        `<div id='material-notice' style='border-radius:2px;color:#FFF;padding:10px;background-color:#09F;box-shadow:0 0 3px rgba(0,0,0,.5);font-size:12px;position:fixed;bottom:20px;left:50px;z-index:99999'>
                        YouTube Plus is not compatible with the YouTube beta Material Layout<br>
                        <a href='https://github.com/ParticleCore/Particle/wiki/Restore-classic-YouTube' target='_blank' style='color:#FFF;font-weight:bold;'>Click here</a> for instructions to restore classic YouTube and continue using YT+<br>
                        When an alpha version is ready for public testing it will be announced <a href='https://github.com/ParticleCore/Particle/issues/448' target='_blank' style='color:#FFF;font-weight:bold;'>here</a><br>
                        To keep using the current layout without this message please disable YT+
                        </div>`;
                    document.documentElement.appendChild(temp.content.firstChild);
                    document.documentElement.removeAttribute("data-user_settings");
                    return true;
                }

![ty - copy](https://user-images.githubusercontent.com/31485812/29895747-39546b86-8dd2-11e7-9810-b5d2a7ac3d35.png)
