### ISSUE TITLE
Firefox pop out confined to current tab only...

### ISSUE THREAD

**Issue by 4evermaat** [ParticleCore/Particle#559]
Browser Name: Firefox esr

  Browser Version: 52.3.0 32 bit

  Operating System:  Win 7 64 bit sp1

  Software Type:   YouTube Plus

  Software Version:  1.8.8

  Userscript Manager: 

  Userscript Version: 

  Problem Description: 
Popup window cannot be taken out of the tab or browser.  Chrome and Opera, the native youtube popout window can move outside the browser window.  

  Steps to reproduce: 
Open up the same youtube video in both Chrome and Firefox.  Then attempt to pop-out the video window. Use Youtube+ plugin for firefox.  pop-out the video.  In Chrome, the video will float over all browser tabs, and even outside the browser window.  Firefox the floating window is limited only to the current tab.

  Additional details:

**Comment by ParticleCore** [comment]
>*WARNING: For this feature to work correctly your browser settings must not block or modify normal pop-out behavior*

https://github.com/ParticleCore/Particle/wiki/Features#popout_on

Make sure you actually test this problem by following all the steps in the instructions, not just the ones you want to: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

Also there is no support for Firefox forks, only stable releases, which ESR is not one, please test with normal Firefox version.
