### ISSUE TITLE
Videos do not autoplay despite autoplay being selected

### ISSUE THREAD

**Issue by pierow** [ParticleCore/Particle#563]
Browser Name: Firefox 

  Browser Version: 55.0.3 32-bit

  Operating System: Windows 7 64bit

  Software Type: Addon

  Software Version: 1.8.9

  Problem Description: Pages load with the video paused desipite autoplay being selected.  This started happening in the past day without any changes on my end.  I ran through the troubleshooting procedures with no luck.  I'm not using the new version of youtube that is incompatible.

  Steps to reproduce: Install addon, make sure autoplay is enabled, try to watch a video.

**Comment by q1k** [comment]
I don't get it, it works fine for me on FF 55 64bit with the userscript version and greasemonkey

**Comment by ParticleCore** [comment]
@q1k He means that when he wants videos to autoplay automatically they are not. That's because I completely forgot to check the user setting before applying the recent update, meaning that it is ignoring the user choice. Will have this fix today.

**Comment by mikhaelkh** [comment]
@ParticleCore also you didn't change userscript version and my userscript wasn't autoupdated. (Chrome, Violentmonkey)

**Comment by ParticleCore** [comment]
@mikahelkh that's odd, don't know what happened. Will rectify it soon.

**Comment by for4zsozsi** [comment]
i hope you guys fix this as soon as possible, because this bug is very annoying. :)
