### ISSUE TITLE
Update broken video autostart

### ISSUE THREAD

**Issue by d3athwolf** [ParticleCore/Particle#564]
so the update on 4th of september that was ment to fix autoplay has now broken autostart

IE: right-click on video open to new tab ->video dosn't start -> have to click on center playbutton to start video

iv disabled the addon and the auto start works like normal and i dont have anything that would disable it turned on, as it was working fine on the 3rd of september

iv tryed having "autoplay videos" turned on and off to no advail
running most recent version of firefox as seen in this image
http://screencloud.net/v/yA98m

**Comment by ParticleCore** [comment]
An update that fixes this problem has already been published today: https://github.com/ParticleCore/Particle/releases

In the future please check if you are using the most recent version or not.
