### ISSUE TITLE
Updating to 1.9.0

### ISSUE THREAD

**Issue by DimplyPack** [ParticleCore/Particle#565]
I had the issue with Autoplay not working, and managed to find the 1.9.0 fix that says it fixed that issue, but I can't figure out how to actually apply the update. Checking the firefox addon page for it still lists it as 1.8.9, and I don't know how to use the source code to apply it.

**Comment by woodyrwac** [comment]
Follow instructions on installing it on Firefox here: https://github.com/ParticleCore/Particle/wiki/Download#firefox---how-to-install-add-on-from-github

**Comment by DimplyPack** [comment]
Thanks, got it working with that.
