### ISSUE TITLE
Autoplay disabling itself

### ISSUE THREAD

**Issue by MaulMachine** [ParticleCore/Particle#566]
Hello,

I recently downloaded and installed the most recent version of Youtube+ on my Firefox browser, and I've noticed that Autoplay on Playlists seems to never work, no matter how many times I try to enable and disable it, restart the browser, and reboot.  Is this a known problem?  Are the add-on and site settings somehow contradicting each other?  I'm using 1.8.9

Thanks,

A New User

**Comment by MaulMachine** [comment]
After examining the tree, I have found the source code for the 1.9.0.  When will be available for autoupdate?

**Comment by gordenfreechmen** [comment]
The same happens to me even outside playlists: load a video's page, and then need to click the video itself for it to start (regardless of Autoplay Videos option checked or not). Didn't have this problem a few days ago upon install.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Particle/wiki/Report-a-problem
