### ISSUE TITLE
Autoplay issue?

### ISSUE THREAD

**Issue by chromeisstupid** [ParticleCore/Particle#567]
Hi, for some time now I have this issue, when I try to open a new video, it doesn't autoplay when the player is ready. There's a preview image of the video, and the "play" button in the middle. It doesn't matter if the autoplay option is on or not, or if I start the video in current tab, or open it in a new one.
When Youtube Plus is disabled, everything works fine.
I think this started happening one or two days ago. The extension itself is up to dat, last update was today.
Any ideas what it is, how to fix this?

**Comment by ParticleCore** [comment]
Please follow the instructions: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by sutr90** [comment]
This is fixed in release 1.9.0. We have to wait for it to make it through Mozilla addons platform.

**Comment by chromeisstupid** [comment]
Hmm, I think it was updated, but something in the browser itself didn't make it work. Anyway, followed the instructions, made a new profile and it seems ok, for now at least. Thanks for the help :)

**Comment by ParticleCore** [comment]
Happy to hear you got it working.
