### ISSUE TITLE
Subscription playlist button no longer appears

### ISSUE THREAD

**Issue by cool-acid** [ParticleCore/Particle#568]
![image](https://user-images.githubusercontent.com/602870/30074724-2aaaea6e-9238-11e7-98af-84408328dc4a.png)
  Browser Name: Chrome

  Browser Version: 60.0.3112.113

  Operating System: OS X

  Userscript Version: 1.9.0

**Comment by ThatMandem** [comment]
Same for me on FireFox Add-On.
Both FireFox and plugin are latest version.

**Comment by ParticleCore** [comment]
YouTube completely removed the top bar where the button was placed on, will try to see what I can do to fix it.
