### ISSUE TITLE
Default video quality doesn't work

### ISSUE THREAD

**Issue by Leonida5** [ParticleCore/Particle#570]
it was working fine before youtube new layout,but after new layout it's not working,i set mine to 480 in yt+ setting,but its always chose auto whenever i play any video so i have to manually click on the video quality on every video to make it right,even after your latest script update this problem still persist 

  Browser Name: Firefox

  Browser Version: 50.1.0

  Operating System: Win7 64bit

  Software Type: UserScript 

  Software Version: 1.9.1

  Userscript Manager: Grease Monkey

  Userscript Version: 3.11

  Problem Description: Video Quality not working

  Steps to reproduce: click/open in any video on youtube

**Comment by mikhaelkh** [comment]
I thought this userscript doesn't support new layout. Use [Iridium](https://github.com/ParticleCore/Iridium) or switch back to old layout.

**Comment by ParticleCore** [comment]
I apologize for the delay on fixing this issue, I will try to get it done before the end of this week.

@mikhaelkh I believe the user is correct on the bug report, I am also not able to default the quality in the classic YouTube layout.

**Comment by mikhaelkh** [comment]
I have no problems with Chrome and Violentmonkey. Maybe this is Firefox-related issue.

**Comment by Leonida5** [comment]
@ParticleCore That's ok mate,i appreciate your reply

@mikhaelkh maybe it is related to firefox only,i don't have time to test it in other firefox version/other browser

**Comment by kilara1988** [comment]
It seems that this is still not fixed.I keep getting 360p or 480p(sometimes even 144p) quality for the first 10-20 sec and then it changes to the default quality i have set in the settings.

**Comment by Leonida5** [comment]
@kilara1988 it's already fixed for me

**Comment by ParticleCore** [comment]
@kilara1988 Make sure you have the up to date version: https://github.com/ParticleCore/Particle/releases/latest

**Comment by kilara1988** [comment]
I do(1.9.2).The script auto updated while i was watching YouTube videos and i checked what was changed/fixed.That is how i found out it was fixed in that update.But it still happened even after the script updated to 1.9.2(i restarted the browser).
Haven't happened again yet,but i will post if it does.

BTW i am using the script version with GreaseMonkey 3.11 on FF 55.0.3 32-bit/Win 10 64-bit.

**Comment by ParticleCore** [comment]
@kilara1988 Can you please open a new issue for yours with details and include your settings so that I can check it on my end.

**Comment by kilara1988** [comment]
It hasn't happened again for a while now and it used to happen at least few times per day before 1.9.2.
I don't know why it happened that one time after i updated to 1.9.2.
Do you still want me to open a new issue anyway or only if it happens again?

**Comment by ParticleCore** [comment]
That's good to hear. Open if it happens again please. I do believe you were really having that issue, but I couldn't understand why would it still be happening after this update.
