### ISSUE TITLE
Youtube New

### ISSUE THREAD

**Issue by Shubho1** [ParticleCore/Particle#572]
youtube+ is not working in current youtube interface can you update it so that it will be used in the new version.i like this script very much.

**Comment by vlatkosh** [comment]
He's making a successor to Youtube+ called Iridium, which works with the new layout. Here's a link where you can get the script: https://github.com/ParticleCore/Iridium

**Comment by ParticleCore** [comment]
YT+ clearly explains in a blue box and links to information regarding this situation.
