### ISSUE TITLE
Subtitles not available with 1.9.1

### ISSUE THREAD

**Issue by bennyhillthebest** [ParticleCore/Particle#574]
I installed 1.9.1 and although it is good to have back the autoplay block back, now videos with subtitles don't load them. I checked this video https://www.youtube.com/watch?v=J0ldO87Pprc with and without YT+ and i'm sure the problem is this script unfortunately.
I thank you for your incredible support, this script is amazing, i hope old layout never goes away :(

  Browser Name: Firefox

  Browser Version: 55.0.3

  Operating System: W10

  Software Type: Userscript

  Software Version: 1.9.1

  Userscript Manager: Greasemonkey

  Userscript Version: 3.11

  Problem Description: no subtitles on YT

  Steps to reproduce: https://www.youtube.com/watch?v=J0ldO87Pprc no subtitles in the gear menu

  Additional details: this script is what YT should have been but never had the balls to be

**Comment by mikhaelkh** [comment]
@bennyhillthebest All good with Chrome and Violentmonkey. Greasemonkey 3.11 is dated April 25, 2017, try [beta](https://addons.mozilla.org/firefox/addon/greasemonkey/versions/beta) or [Tampermonkey](https://addons.mozilla.org/firefox/addon/tampermonkey/) or [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/).

**Comment by ParticleCore** [comment]
I apologize for the delay on fixing this issue, I will try to get it done before the end of this week.

**Comment by ParticleCore** [comment]
Version 1.9.1 fixes this issue.

**Comment by Leonida5** [comment]
@ParticleCore for me it's stil not fixed,the cc button doesn't work if there's no cc where it should bring auto translate on,when i restart firefox with disabled add-ons it's work,the auto translate subtitle is appear and the cc button is working/clickable
