### ISSUE TITLE
Popout and Theater mode broken (minor bug)

### ISSUE THREAD

**Issue by Alstro20** [ParticleCore/Particle#578]
If you put your video into Theater mode, then pop out the video, then close the popout, the video will continue to play in Youtube's regular Theater mode.

Edit: I'm using Greesemonkey 3.11 on Firefox.

**Comment by ParticleCore** [comment]
Can't understand what the problem is, please read the instructions: https://github.com/ParticleCore/Particle/blob/master/CONTRIBUTING.md

**Comment by ParticleCore** [comment]
I will close this for now, if you are still having trouble please follow the instructions in my previous reply.
