### ISSUE TITLE
Resize the scrolling video?

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#58]
Is there a way to resize the small video? I looked all over but didn't find a way.

It's a really nice feature but the video is way too small, for me atleast.
Normal video: http://prntscr.com/865cnp
'Scrolling video': http://prntscr.com/865d2e

Also would it be possible to adjust when the small video appears? Right now it seems to appear when the main video is about 50% gone. This though, is not a big deal at all.

**Comment by ParticleCore** [comment]
The floating player size is related to the right sidebar width, there is no way of changing the size directly and I have no interest on adding such feature.

The same goes for when the player floats, it was designed with the 50% treshold to cover the average use behavior that I tested.

**Comment by ParticleCore** [comment]
I know it has been a long time but I've implemented [this feature](https://github.com/ParticleCore/Particle/wiki/Features#floating_player_width) recently in 1.1.3, hope it works well for you.

**Comment by Eisys** [comment]
Wow, thank you so much. Works great.

However I personally find the new way to move the floating player a bit annoying. By that I mean when I go to pause the video with my mouse, I usually do it quick and sort of run the mouse over the video and pause it. Which in turn sometimes moves the player a bit, and/or doesn't even pause it. So I would prefer the previous method.

But this is quite a small thing and overall the update is fantastic.

**Comment by mauriciocolli** [comment]
I think a toggle button in the player to block the dragging like that, would be good:
https://i.gyazo.com/7b6bb24bebca505801d1ca69bcc10fdd.mp4

What do you guys think?

**Comment by Eisys** [comment]
@mauriciocolli Something like that would be perfect.

**Comment by ParticleCore** [comment]
Perhaps dragging with the right mouse button would be a better alternative? This way it would not interfere with any left button functions. I would prefer not to restore a button for this feature.

**Comment by ParticleCore** [comment]
I have added a movement threshold of 10px before the player can be moved, this way you won't need to rest the mouse completely to play/pause the video. Let me know if it works well for you too.

**Comment by mauriciocolli** [comment]
Here it is working well, I think the idea of threshold is better than a toggle button.
But look at that bug in Chrome.
When you go to fullscreen they don't fill the screen, it just change the background because the size of the player doesn't change:
https://i.gyazo.com/108fe345dae4cf886057c0de30b20339.mp4
I think there's need to open an issue, but I open if you want.

**Comment by Eisys** [comment]
Definitely an improvement. It pauses nicely unless I really fly over the video.

Out of curiousity, why did you add this feature? I personally never move the floating player around so only need to move it once after a fresh install of YT+ so I'm just wondering.

And I can confirm the shown bug as well.

**Comment by mauriciocolli** [comment]
https://gyazo.com/1f3061cefbbe4467144d4b5e0177feab 
The bug occurs because the properties aren't removed, and strangely this bug occurs only when you have the "Inspect elements" closed, so I guess that have something with the width or the height of the page

**Comment by ParticleCore** [comment]
Press Ctrl + F5 and it should be working again. Don't know why Chrome is not overriding the elements' attributes when entering Fullscreen like Firefox does, but it should be working correctly now.

@Eisys  I use it all the time, I am constantly moving the player around on desktop pc and laptop so making it easier to do it helps a lot for me.

**Comment by mauriciocolli** [comment]
Now it works fine, I already tried the Ctrl + Shift + R thinking that both do the same, but ok..
Thanks!

**Comment by q1k** [comment]
I'd love a toggle button.
I mean, sometimes I just whiz over the video clicking to pause it, and with the threshold it would move the player...

**Comment by MyNameIsNotOrbit** [comment]
I agree with q1k.

While the 'delay' of 10 pixels is better, I often find myself moving the player while trying to pause a video.

**Comment by CyberMew** [comment]
One year late to the party but where can I change the size of the floating player? I think I saw it but it  doesn't have any effect (or maybe that was for the pop up player)

**Comment by ParticleCore** [comment]
@CyberMew it is right below the floating player toggle https://github.com/ParticleCore/Particle/wiki/Features#floating_player_width

**Comment by CyberMew** [comment]
I'm afraid I don't see anything that would allow me to adjust the size of the floating player. The linked you gave (which I have went to before) just shows the before and after effect with no specific  UI instructions. If you are referring that we can resize the floating directly and not inside the settings panel, I can only see the hover button located at the top left corner of the floating player.

**Comment by ParticleCore** [comment]
It also shows the name of the option and at the top you can see in which place that option is located at in respect to the YT+ settings menu: Settings > Video > Floating player width

**Comment by CyberMew** [comment]
Ah I TOTALLY missed that line! I kept referring to the Layout -> pop out player size and kept wondering where the heck is the floating player setting. Thank you! Works perfectly now. :)
