### ISSUE TITLE
Problems whit the new UI on Youtube

### ISSUE THREAD

**Issue by elajits** [ParticleCore/Particle#580]
hey my videos getting black when in turns into mini mode!

**Comment by ParticleCore** [comment]
Please read the instructions: https://github.com/ParticleCore/Particle/blob/master/CONTRIBUTING.md

**Comment by ParticleCore** [comment]
Also YT+ is not compatible with the new layout, it is clearly explained in the blue information balloon it displays at the bottom right corner.
