### ISSUE TITLE
restoring classic YouTube caused to stop responding

### ISSUE THREAD

**Issue by smdx** [ParticleCore/Particle#582]
restoring classic YouTube will cause the opening of the video page will cause the CPU to increase the browser to stop responding. Is there a way to support new designs? Thank you

Win10 1703 15063.608 64bit
FF52.2.0

**Comment by ParticleCore** [comment]
Please follow the instructions: https://github.com/ParticleCore/Particle/blob/master/CONTRIBUTING.md
