### ISSUE TITLE
Settings not saving.

### ISSUE THREAD

**Issue by Iysbaera** [ParticleCore/Particle#589]
Hello,

I use the latest chrome version and have a problem with youtube+ script installed from greasyfork through tampermonkey. 
After every reload of youtube page all of the settings are being reset to default and the message pop-ups as if i just installed the scrpit.

**Comment by ParticleCore** [comment]
I am not having this problem. Please follow the instructions as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Iysbaera** [comment]
Sorry for inappropriate issue template.

 Browser Name: Google Chrome

  Browser Version: Version 61.0.3163.100 (Official Build) (64-bit)

  Operating System: Windows 7, 64bit

  Software Type: Userscript

  Software Version: 1.9.2

  Userscript Manager: Tampermoney

  Userscript Version: 1.9.2, Tampermonkey v4.4

  Problem Description: After every youtube page reload, all settings are reset to defaults and i get [this](https://i.imgur.com/QZFfAHV.png) message.

  Steps to reproduce: Reload youtube page.

I tried to disable all of my extension, but the problem persists.

**Comment by ParticleCore** [comment]
The troubleshoot instructions are to be followed, all the steps, not just the ones you feel like trying, otherwise I will have to ask for you to do them here step by step. Follow the troubleshooting instructions as requested and then report back if the problem persists.

**Comment by Iysbaera** [comment]
It seems that the problem was in browser settings, but i don't know which one of them caused the issue.

**Comment by ParticleCore** [comment]
Glad to hear that it is working as normal again, sad to hear that the cause wasn't clear. If it happens again let me know, it could have been a problem with Tampermonkey, it is not impossible.

**Comment by Iysbaera** [comment]
It was working only with new chrome profile with tampermonkey.
But, fortunately, i fixed the problem by switching from tampermonkey to violentmonkey in my usual profile and now it works. 
Thank you for your time and awesome script. 
Now it's the best solution for someone who needs blacklist in old youtube layout after the video blocker extension switched to the new layout.
