### ISSUE TITLE
Bug with 'Player shortcuts always active'

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#59]
I found a bit of a bug with this update after using it for a while.

On a video, if I click anywhere else on the page, it jumps up to the video. If I scroll down and the small video comes up, I can click things again.
If I disable the 'Player always visible when reading comments' then I can't click anything on the video page, it just jumps up to the video.
It seems like it thinks I'm clicking on the video.
It's not that big of a deal to me, specially when using the small player cause everything clickable can be clicked if I scroll down enough. Just letting you know.

Using the userscript version with Tampermonkey, Chrome 44.0.2403.155 m (64-bit)

Continuing #56

Also, sorry, didn't notice the 2nd comment.

**Comment by ParticleCore** [comment]
Update to 0.5.1 and let me know if the problem is fixed for you.

**Comment by Eisys** [comment]
Yep, it's fixed. Thank you!

**Comment by q1k** [comment]
still doesn't work on flash player

**Comment by Eisys** [comment]
@q1k Pretty sure it's not supposed to. This addon is only made for use with HTML5

**Comment by ParticleCore** [comment]
@q1k In the previous issue I've linked to you it clearly explained that many features were not compatible with the Flash player and a warning is present in the wiki and repo's main page:

>YT+ supports only YouTube's HTML5 player, some features will not work when using YouTube's flash player.

https://github.com/ParticleCore/Particle/wiki
