### ISSUE TITLE
Suggest adding short cut.

### ISSUE THREAD

**Issue by Chigogo** [ParticleCore/Particle#592]
Shift + f seems like a good option.

**Comment by ParticleCore** [comment]
Sort cut for what purpose?

**Comment by Chigogo** [comment]
@ParticleCore ![2017-10-03_115508.jpg](https://i.loli.net/2017/10/03/59d30a5e26670.jpg)

**Comment by Chigogo** [comment]
@ParticleCore Will I be notified when feature is added.

**Comment by ParticleCore** [comment]
Yes, but the extension is currently at end of life status, meaning that no more features will be added, only bug fixes: https://github.com/ParticleCore/Particle/issues/504

**Comment by Chigogo** [comment]
@ParticleCore Then I use vimium to reach that.
