### ISSUE TITLE
Disabling YouTube loudness normalization doesn't work.

### ISSUE THREAD

**Issue by Ulisse54** [ParticleCore/Particle#593]
I tried it, but I can notice no difference between it on and off, videos that should go higher in volumeare still flattened.

**Comment by ParticleCore** [comment]
Some videos might not have a noticeable change, while others do. Please provide examples confirming that this feature is not working correctly.

**Comment by Ulisse54** [comment]
[Here's an example](https://www.youtube.com/watch?v=zUzd9KyIDrM).
Well, first of all sorry for the kinda "aggressive" genre, we all have different tastes.
I've listened to this song from a CD, the audio volume at 0:10 should nooooootably increase, however, it is really flattened down for me.

**Comment by ParticleCore** [comment]
You are telling me that you are comparing the YouTube video volume with the volume in your CD? That is not how you check to see if this is working or not. You have to test with a YouTube video that you know is louder than it is playing, such as a video you uploaded yourself.

Example: this video is noticeably louder when the normalization is turned off or on

https://www.youtube.com/watch?v=fbTlspIKptE

same for this one

https://youtu.be/Yq83rW7uHVc

So this feature is working correctly.
