### ISSUE TITLE
Instructions to restore old Youtube layout shown when they should not.

### ISSUE THREAD

**Issue by kilara1988** [ParticleCore/Particle#595]
As you can see from the screenshots the horizontal bar above videos and the dropdown menu on the left both have the Home/Trending/Subscriptions buttons.

However the buttons on the horizontal bar add a "?disable_polymer=1" string to the URL which causes the blue box with instructions to restore old YouTube layout to show even though you are using the old layout.
Using the buttons from the menu on the left doesn't add this string and the blue box does not show.
![1](https://user-images.githubusercontent.com/1025376/31240453-6aafcf7e-aa09-11e7-84a4-b48eb694fb61.png)
![2](https://user-images.githubusercontent.com/1025376/31240452-6aaa61c4-aa09-11e7-9f67-459cbe80d7a4.png)

**Comment by The-Euphoria** [comment]
I have the exact same issue, except YT+ is not working at all, the settings icon (top right) is missing but the extension is enabled.
Is still says; _"This extension violates the Chrome store policy"_ next to it, but it is enabled.

**Comment by ParticleCore** [comment]
Very likely to be a false positive, the extension had to be aggressive with material detection (basically whenever it finds file sources or links with polymer in them) to be more future proof to the constant changes they are making to the way they introduce the new layout. Will see what I can do to work around this.

**Comment by Eisys** [comment]
This also happens to me on someone's channel page.
For example, I click on someone's name. Which leadse me to:
https://www.youtube.com/user/GamersNexus/videos
Then click on 'Home' and then back to 'Videos', or any of the tabs, the YT+ icon disappears from top right and the blue box appears.

**Comment by ParticleCore** [comment]
@Eisys There are multiple links in that channel containing the polymer word in their href, causing the false positives.

**Comment by ParticleCore** [comment]
Version 1.9.3 should help reduce the false positives, but I cannot say they are completely fixed due to the constant changes YouTube is undergoing.
