### ISSUE TITLE
Prevent autoplay does not always work

### ISSUE THREAD

**Issue by ganego** [ParticleCore/Particle#60]
When I open videos from my subscription page roughly 50% of them automatically start even though they should not.
When I load those 'starting videos' again (even in a new tab), they still continue starting.
Other videos behave as expected and do not load.
The problem started a few weeks ago (maybe with 0.4?).
I'm using the greasyfork version on FF 43 (nightly) (same problem with FF 42 nightly) with HTML5 player.

One example video:
https://www.youtube.com/watch?v=9DuzKv-IRL0

**Comment by ParticleCore** [comment]
I've tested multiple videos, including the one you linked, and none of them played on their own, including in Firefox 43.0a1.

There are a few cases that might make the the videos autoplay, for example if the video you are currently watching is present in a playlist in the sidebar. If you click on that playlist it will resume the same video from where you were playing, this is YouTube's default behavior and I don't intend to change to avoid worse complications.

Other videos might have time anchors which make them automatically play from a certain point in the video. For example, this will make your linked video play automatically from the 4s mark: https://www.youtube.com/watch?v=9DuzKv-IRL0#t=4s

This is also something I don't intend to change for the same reasons as before.

If this is not what is happening with you then it is possible another add-on or userscript are causing a conflict. Disable everything except YT+ and see if the issue still persists.

Also which userscript manager are you using? Is it greasemonkey? Which version?

**Comment by ganego** [comment]
I deleted all my cookies, html5 storage, flashstorage and the browsercache and right now it seems to work as expected - no idea why anything of that has anything to do with why FF chose to autoplay, but anyway.
Sorry for wasting your time.

Got greasemonkey 3.3 btw, (didn't know there are others for FF, sorry).

**Comment by ParticleCore** [comment]
Thank you for letting me know. If it happens again please do report it.
