### ISSUE TITLE
Once the gap appears, as in the screenshot.

### ISSUE THREAD

**Issue by zihiwoz** [ParticleCore/Particle#602]
Once the gap appears, as in the screenshot.
http://i4.imageban.ru/out/2017/10/17/8ef71297643381a6d309babdcf5557c3.png

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Particle/blob/master/CONTRIBUTING.md

**Comment by ParticleCore** [comment]
This will be closed for now, if you still have any issues follow the instructions in the previous post.
