### ISSUE TITLE
How to reset the Blacklist?

### ISSUE THREAD

**Issue by KamtarGaming** [ParticleCore/Particle#603]
Browser Name: Firefox

  Browser Version: 56.0 32bits

  Operating System: Windows 7

  Software Type: Module

  Software Version: 1.9.3

  Problem Description: I accidentaly press the "Add to blacklist" button on my favorite channel and now I cannot find how reset the blacklist.

  Steps to reproduce: 1- Find ur favorite channel; 2- Press the little "x" on top corner right of any video

Thanks for reading and i'm french so, sorry for my bad english.

**Comment by ParticleCore** [comment]
You can edit your blacklist by going to the Settings (click the dark triangle with a plus sign on the top right of any YouTube page) and then select "Blacklist" from the left sidebar. There you can edit your blacklist.

**Comment by KamtarGaming** [comment]
Rhaa, finally! It make hours i search, thanks !
Annnnd..., just for ask, why don't u add a button here like some other addon does ?
https://i.imgur.com/ScNDcGw.png ("options" button)

**Comment by ParticleCore** [comment]
Because the settings are not in their own page, there is no way to provide a dedicated settings page with the current implementation. The next extension will have the dedicated options button to avoid this kind of confusion.

**Comment by KamtarGaming** [comment]
I see. Well, thanks u for all that awnser and have a nice day !
