### ISSUE TITLE
Autoplay keeps on switching on

### ISSUE THREAD

**Issue by skymonkey1993** [ParticleCore/Particle#604]
Issue just started today. I had unchecked it on the settings, yet two hours later it was checked again.

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by ParticleCore** [comment]
Closing this, if you are still having trouble follow the instructions in the previous reply.
