### ISSUE TITLE
Black list doesn't work any more.

### ISSUE THREAD

**Issue by lazy1azy** [ParticleCore/Particle#607]
Browser Name: Firefox

  Browser Version: 56.0.2 (64-bit)

  Operating System: Windows 7 64-bit

  Software Type: Add-on

  Software Version: 1.9.3

  Problem Description: When I try to use the blacklist function and click on the "Add to blacklist" button on video, nothing happens and the channel is not added to the blacklist. Also, previously blocked video channels are displayed on youtube.

  Steps to reproduce: I created a new firefox profile and added only youtube plus add-on. I tried the above described actions. Problem still exists.

**Comment by ariefpizzuti** [comment]
Show link with number of uploaded videos also doesn't work anymore

**Comment by stonecrusher** [comment]
In addition to lazy1azy's problem the `x` for adding to blacklist is only shown in search results, not on thumbnails of related videos (right sidebar) anymore.

**Comment by Eisys** [comment]
Can also confirm video count doesn't show up anymore.

**Comment by ParticleCore** [comment]
I can verify this. To everyone else, please don't mix issues, open in a new one instead.

**Comment by ParticleCore** [comment]
Looks like recent YouTube update is no longer serving the channels' UUID if the channel is verified, meaning that a lot of blacklisted channels will need to be re-added again.

I'm gonna try to make it correlate the canonical links with their respective UUID automatically, but if it becomes too troublesome I will push the current fix and users will have to add these channels again.

**Comment by ParticleCore** [comment]
Version 1.9.4 fixes the blacklist no longer working, however, in relation to what @ariefpizzuti  said, it is no longer possible to blacklist the videos in the right side due to YouTube no longer providing the channel data for those videos. It is an unfortunate change, but there is nothing that can be done outside of YouTube reverting that change.
