### ISSUE TITLE
"Remove autoplay up next" only works once, here's a fix

### ISSUE THREAD

**Issue by GrayFace** [ParticleCore/Particle#608]
This script works correctly: https://gist.github.com/Yonezpt/51adf278a24488f75ff0
YT+ only works when you refresh the page. Navigating to any other video re-enables the checkbox.

Browser Name: Cent Browser
Browser Version: Version 2.9.4.39 (Official Build) (32-bit) (portable) (Chromium 61.0.3163.100)
Userscript Manager: Tempermonkey
Userscript Version: 1.9.3

**Comment by ParticleCore** [comment]
Please read the instructions for reporting a problem. this extension does not provide support for the Cent Browser: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by GrayFace** [comment]
Cent Browser is the same as Chrome in terms of extensions support. It's up to use to use info I've provided, for me the issue is solved by an extra script I've linked to.

**Comment by ParticleCore** [comment]
A fork of Chrome is most definitely not the same as Chrome, it is different than Chrome and for that reason support is not provided outside the listed browsers. If it really was the same as Chrome then it would be pointless to have Chrome forks.
