### ISSUE TITLE
Iridium extension will be replacing YT+ for the new YouTube layout

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Particle#609]
The Iridium extension is close to final release (at the time of this writing) and is intended only for the new YouTube material layout.
Until it is released, the extension is only available as a userscript, meaning that it still does not have an add-on or extension version.
The initial release comes with less features than YT+, but their number is planned to grow with time.

Iridium is currently available here: https://github.com/ParticleCore/Iridium

This issue is not open for feature requests or issue reports related to Iridium, any such posts will be removed. Use the Iridium issue tracker for that purpose.

**Comment by sergeevabc** [comment]
Does not work with Pale Moon, albeit [Greasemonkey][1] supports Pale Moon. It is Javascript, not a Webextension, come on.

[1]: https://github.com/janekptacijarabaci/greasemonkey/releases

**Comment by ParticleCore** [comment]
>Does not work with Pale Moon, albeit Greasemonkey supports Pale Moon.

@sergeevabc we already had this nonsense conversation before in https://github.com/ParticleCore/Particle/issues/423#issuecomment-270000739, we won't be having again even if you didn't understood it the first time. I couldn't care less If it doesn't work with Pale Moon or with any fork users feel entitled to demand support for, I clearly described **AGAIN** in the requirements which browsers are receiving support: Firefox and Chrome, nothing more.

> It is Javascript, not a Webextension, come on.

Exactly, so you can make a compatible version for yourself.

Also, as I explained, your comment will be removed since you clearly didn't care to read a couple of lines, **AGAIN** before replying: 
>This issue is not open for feature requests or issue reports related to Iridium, any such posts will be removed.
>Use the Iridium issue tracker for that purpose.

**Comment by RAY41** [comment]
Hi (sorry for my english, i'm french)

I really like your extension and I have a question : Can you add a functionality : automatically disable autoplay in playlist.

-regards-
TB

**Comment by ParticleCore** [comment]
@RAY41 Please make your requests in the Iridium repository as requested.

**Comment by phil15world988** [comment]
the best
