### ISSUE TITLE
Resizable Player Window

### ISSUE THREAD

**Issue by diggitydogg** [ParticleCore/Particle#61]
Would it be possible to have the pop-out player window be resizable while scrolling up and down the page? Ideally I would like it to keep the same size as the theater mode player. Or if not able to make it dynamically resizable, perhaps an option to set it to a few predefined sizes such as small, normal, theater, full browser width.

**Comment by ParticleCore** [comment]
This was already requested in https://github.com/ParticleCore/Particle/issues/58
