### ISSUE TITLE
pupout mode not working on related videos

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Particle#610]
I enabled popout and it shows the button on my subscriptions page, but when I open a video, in the related videos sidebar the button doesn't appear.
I am using the yt+ userscript with tampermonkey on chrome.

**Comment by ParticleCore** [comment]
Same here, will fix it asap.

**Comment by ParticleCore** [comment]
@q1k Sorry for the delay on this, but it has been hard to find some time to fix this, but I haven't forgotten. I plan to have this fixed this weekend tops, if not sooner.

**Comment by bvjazz** [comment]
Thanks
