### ISSUE TITLE
reloadingisues

### ISSUE THREAD

**Issue by roppyntlnd** [ParticleCore/Particle#616]

**Comment by roppyntlnd** [comment]
https://github.com/ParticleCore/Particle.wiki.git

**Comment by ParticleCore** [comment]
Please follow the instructions for reporting a problem: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by bvjazz** [comment]
Thanks for the Hit Firefox just sent the updateBV

**Comment by bvjazz** [comment]
Thenks BV
