### ISSUE TITLE
Video playback tends to freeze after some skipping via arrow keys, FF 57

### ISSUE THREAD

**Issue by Mike500** [ParticleCore/Particle#617]
Browser Name: Firefox 57.0
Operating System: Windows 10
Software Type: Add-On
Software Version: 1.9.4
Problem:
After updating to Firefox 57, i noticed that with Youtube Plus loaded, the video tends to stop with a white "loading circle" in the middle, whenever i skip through the video with the right or left arrow key. For example, i hold right arrow for a second, the video stops playing (image freezes), the white circle appears, and it just keeps buffering. When i skip further, in an attempt to get it playing again, sometimes the audio will resume, but the video will go black. Why do i think this is a Youtube Plus issue? Simple, i can't reproduce it with the add-on disabled. With Youtube Plus active, it takes me maybe 10, 15 seconds of some arrow-key skipping forwards and/or backwards to provoke the problem.

Steps to reproduce:
Arrow-key skipping, either keeping the right/left arrow key pressed for a while, or fast tapping of the key to skip 5 seconds at a time.

**Comment by ParticleCore** [comment]
This might be a conflict with something else on top of YT+, please follow the troubleshooting guide as requested to rule out this possibility: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

**Comment by Mike500** [comment]
I disabled all other add-ons, but the problem still occurs. With a new Firefox profile, i could only trigger it once so far.

A rapid succession of forward- or backward-skip commands does it. I use the shortest "Repeat delay" in the Win10 keyboard properties (slider all the way to the right). When i use the default setting (one notch away from the right), it takes longer to trigger it, but i eventually manage to trigger it there as well, when i hold the right and then the left arrow key long enough back and forth.

Other changes of note to FF: layout.css.devPixelsPerPx to "1", Youtube page zoom to 110%. Windows 10 is set to 125% (i use a 32" 2560x1440 monitor that otherwise has too high of a DPI for me). I don't know if that is a contributing factor, but i've looked at my changed parameters in about:config for a good while, and i can't figure out what could cause this.

Saturday i'm on another PC, i'll try to get to the bottom of this somehow...

**Comment by bvjazz** [comment]
Ok I give up 
If Firefox doesn't care what then! We fix it, Yikes don't think so maybe youbut I just want to use Mt Gates shortcoming software and live the good lifeNot so though the switch needs to be one that works and hope someone at FF gets it together?Bob V

**Comment by phil15world988** [comment]
the best

**Comment by ParticleCore** [comment]
If you still have this problem please follow the instructions in the previous reply.
