### ISSUE TITLE
Please, the current YouTube version, YT+, still not working with or on my new Firefox browser, version 57, 64-Bit

### ISSUE THREAD

**Issue by charlie6756** [ParticleCore/Particle#620]
Please, the current YouTube version, YT+, still not working with or on my new Firefox browser, version 57, 64-Bit. Please kindly advice me on the right steps to take or show me where to download at least a classic, workable version of the YT for this particular firefox browser. or should I abort Firefox completely and adopt Chrome as my standard browser

**Comment by ParticleCore** [comment]
YT+ does not support the new YouTube update, please read the announcement for the alternative: https://github.com/ParticleCore/Particle/issues/609
