### ISSUE TITLE
Bill Murphy

### ISSUE THREAD

**Issue by goatrock** [ParticleCore/Particle#624]
Now I have a blue box telling me how to restore Youtube and that doesn't work. So, what now?

**Comment by ParticleCore** [comment]
If you no longer can restore the classic YouTube then that is it for you, that is a YouTube decision. You can find the replacement extension version announced here: https://github.com/ParticleCore/Particle/issues/609

**Comment by garoto** [comment]
Who the heck is Bill Murphy?

**Comment by ParticleCore** [comment]
@garoto please do not use the issue tracker for this kind of discussion, keep the discussions related to the issues only.
