### ISSUE TITLE
Default video quality not working anymore

### ISSUE THREAD

**Issue by Mongogamer** [ParticleCore/Particle#629]
Browser Name: Waterfox

  Browser Version: 56.0

  Operating System: Win 7 Ultimate 64 bit

  Software Type: The xpi in the dist folder (So I guess add-on?)

  Software Version: 1.9.5

  Problem Description: Videos don't automatically switch to the default video quality selected in the settings (in my case 720p). Instead they use the automatic youtube resolution.

  Steps to reproduce: Watch basically any video.

  Additional details: Started happening just today.

**Comment by ParticleCore** [comment]
Do keep in mind that this extension does not provide support for any browser that is not Firefox, Chrome or Opera, period. That excludes all forks.

**Comment by Mongogamer** [comment]
I can confirm that the issue also exists in Firefox 57. Video resolution went straight to 480p ignoring the settings.
