### ISSUE TITLE
Can't comment when player shortcuts are on.

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#63]
At first it looks like normal: http://prntscr.com/8a89v2
Then when I click on it, it just turns into a white box and I can't type in it: http://prntscr.com/8a8a12

If I disable shortcuts, there's a sort of an animation when clicking on the comment box, Youtube might've changed something about it.
I'm using the latest ver. of YT+ on latest Chrome w/ Tamper.

**Comment by ParticleCore** [comment]
Thank you for letting me know, they have in fact changed the class name just for that box which is causing this problem, I've already fixed the issue and will be posted with the next updated.
