### ISSUE TITLE
u tube

### ISSUE THREAD

**Issue by justmesuds** [ParticleCore/Particle#632]
its a mess with this update i am moving past it if it does not  work   why use it    just saying if its not  broke dont   fix  it or mess with  it

**Comment by justmesuds** [comment]
if it s not  broke  why  mess with it

**Comment by ParticleCore** [comment]
@justmesuds There was no update done other than the YouTube website itself changing into a completely different and incompatible version, which is completely out of the control of this extension.
In the future send your feedback to the YouTube team instead of spamming this repository.
