### ISSUE TITLE
footer-container unresponsive

### ISSUE THREAD

**Issue by mikhaelkh** [ParticleCore/Particle#638]
Browser Name: Google Chrome

  Browser Version: 63.0.3239.108 (Official Build) (64-bit)

  Operating System: Windows 10 v1607 (14393.1944)

  Software Type: Userscript

  Software Version: 1.9.6

  Userscript Manager: Tampermonkey

  Userscript Manager Version: 4.5.5660

  Problem Description: https://www.youtube.com/html5 - footer-container (Language, Location, Restricted Mode, etc.) is unresponsive to mouse clicks.

**Comment by ParticleCore** [comment]
I will push a fix for this once another iteration occurs since this is not that important and it is simply cosmetic (the fix, not the issue).

**Comment by thienha1** [comment]
Can you make scripts that set a timer to automatically pause/stop on all Youtube embed videos? Like pause a video after X seconds!!?

**Comment by ParticleCore** [comment]
@thienha1 This repository is not for script requests, use appropriate places like greasyfork forum.

**Comment by ParticleCore** [comment]
Closed due to #680
