### ISSUE TITLE
Search bar under video for theater mode full screen.

### ISSUE THREAD

**Issue by D-elias** [ParticleCore/Particle#650]
I have "fit to page in theater mode" selected with 100% "fit to page max width". It does fill the screen but the Youtube search bar is still showing. Can you please add an option to place the Youtube search bar under the video player like Youtube Center for full screen playback?

**Comment by ParticleCore** [comment]
The search bar remains behind the video player on my end, please follow the instructions for posting a new issue as requested: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

Also make sure that you don't have another extension that is causing this conflict, such as TubeBuddy: https://github.com/ParticleCore/Particle/issues/650

**Comment by ParticleCore** [comment]
Closing this for now, if you still have problems follow the instructions in my previous reply.

**Comment by D-elias** [comment]
I just tried it on Google Chrome and the search bar is still on top of the full screen video.
No other extensions are used and YT+ is the only script installed.

![window 2018-01-21 at 14 42 08](https://user-images.githubusercontent.com/3038757/35198461-3eb1d440-febd-11e7-9e77-76252276fb6b.png)
![window 2018-01-21 at 14 55 42](https://user-images.githubusercontent.com/3038757/35198462-3ef28026-febd-11e7-9664-034b6bd551f6.png)

  Browser Name:  Google Chrome

  Browser Version: Version 63.0.3239.132 (Official Build) (64-bit)

  Operating System: MacOS High Sierra 10.13.2

  Software Type: Extension

  Software Version: 4.5

  Userscript Manager: Tampermonkey

  Userscript Version: 1.9.6

  Problem Description: Full screen has search bar visible.

  Steps to reproduce: Import settings below.

  Additional details: 



YT+ settings:
````json
{
  "GEN_BTTR_NTF": true,
  "GEN_SUB_LIST": true,
  "GEN_INF_SCRL": true,
  "GEN_BLUE_GLOW": true,
  "GEN_PPOT_ON": true,
  "VID_END_SHRE": true,
  "VID_DFLT_QLTY": "hd2160",
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": true,
  "VID_PLR_ATPL": true,
  "VID_PLR_ALVIS": true,
  "VID_PLR_SIZE_MEM": true,
  "VID_PLR_VOL_LDN": true,
  "VID_POST_TIME": true,
  "VID_VID_CNT": true,
  "VID_DESC_SHRT": true,
  "VID_PPOT_SZ": "100%",
  "VID_PLR_HTML5": true,
  "BLK_ON": true,
  "floaterX": 1054,
  "floaterY": 686,
  "firstTime": false,
  "volLev": 80,
  "advOpts": true,
  "blacklist": [],
  "extLang": {},
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": true,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "videos",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": false,
  "GEN_YT_LOGO_LINK": true,
  "GEN_DSBL_ADS": true,
  "GEN_LOCL_LANG": false,
  "VID_LAYT_AUTO_PNL": true,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": true,
  "VID_HIDE_COMS": "0",
  "VID_PLR_FIT_WDTH": "100%",
  "VID_PLR_FIT": true,
  "VID_PLR_DYN_SIZE": true,
  "VID_PLR_INFO": false,
  "VID_PLR_HFR": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": true,
  "VID_PLR_ANTS": true,
  "VID_PLR_CC": true,
  "VID_PLR_ALVIS_WDTH": "700",
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": true,
  "theaterMode": true,
  "floaterSnapX": false,
  "floaterSnapY": 1,
  "fullBrs": false,
  "lightsOut": false
}
````

**Comment by ParticleCore** [comment]
I just tested it with the same configuration and YT+ settings as yours, the search bar stays behind the video

![ss](https://user-images.githubusercontent.com/9222661/35198713-8dde4dee-fee2-11e7-8444-6dd770df853e.gif)

The same test was also conducted while logged out with the same result.

I cannot replicate the problem and if I can't replicate it then I can't fix it.

Please follow all the troubleshooting steps as requested, not just the ones you feel like trying: https://github.com/ParticleCore/Particle/wiki/Report-a-problem#troubleshooting

Especially the step where a new Chrome profile is used to rule out browser settings interfering.

**Comment by D-elias** [comment]
Thanks for the gif. When I click on "Full browser mode" it has the same behavior as yours. I was trying to make a new video fill the screen with out the need to click on anything to do so. Youtube Center had this ability by moving the search bar under the video player so every new video filled up the screen according to the size chosen in settings. I tried to replicate this in YT+ by selecting "Fit to page in Theater mode" with "100%" and choosing "Theater mode" in Youtube so every video opens with the video filling up the screen but the search bar is still visible at the top.

**Comment by ParticleCore** [comment]
That has nothing to do with an extension feature, this is normal YouTube behavior and it was not designed to work that way.
If you want the search bar to go behind the video in 100% width theater mode you will have to do it on your own.
This extension is only receiving bug fixes and no more feature/improvements, which I now understand that what you were asking for was the later.

**Comment by D-elias** [comment]
Thanks for explaining this in regard to the YT+ settings. Double clicking on every video to make it go to full screen is default for Youtube with out scripts. I was not aware that feature requests were no longer considered. Perhaps a Paypal donation would be accepted for this? 
I have Youtube loading every video in full screen automatically by adding this line to Stylish. It does remove the search bar completely though.

#yt-masthead-container {
display: none; 
}

**Comment by ParticleCore** [comment]
I appreciate the PayPal donation, but new features are not included because of that, on top of the current state of this extension which is EOL (end of life support, means only bug fixes) due to the new YouTube layout. This is because to make it compatible with the new layout it would require a full rewrite of the extension, which I am currently on the verge of finishing: https://github.com/ParticleCore/Iridium

Either way, I thank you for the interest, but I cannot accept donations in exchange of new features, otherwise it would drive the extension into becoming a bloatware impossible to maintain with all the frequent changes YouTube does.

If all it takes for what you want is that CSS rule then you can just add it in a userstyle and run it with an extension like Stylish or similar.
