### ISSUE TITLE
[question] Blacklist channel from currently played video

### ISSUE THREAD

**Issue by stonecrusher** [ParticleCore/Particle#653]
I know about the blacklist feature not working fully anymore because of youtube changes.

But what am I missing, how can I blacklist the channel from the video I'm watching right now? That's my most needed - I see a video, recognize it's crap and want to block the channel.

Only way at the moment is to search for that channel again in a new window and then blacklist it from the search results.

**Comment by ParticleCore** [comment]
There's currently no way to block the channel from within the video you are watching.
