### ISSUE TITLE
Feature request: Block only ads set in the middle of videos

### ISSUE THREAD

**Issue by mmuh** [ParticleCore/Particle#661]
Thank you for this great script that enhanced my watching experience a lot for so long now! :)

I like to support content creators i'm subscribed to, so the option to show ads on those channels comes really handy. Lately a lot of them unfortunately decided to but lots of ads into the video, not just at the start and/or end, which caused me to block all ads again.

Would it be possible to allow the start/end ads while blocking all others for my subscribed chans?

**Comment by ParticleCore** [comment]
It is technically possible, that was my initial plan, but they change so frequently (the way they are defined in the source code) that it would require me to update the code almost every day. It is still something I keep on the lookout, but last time I checked it keeps changing with the same frequency.

I also wanted to allow users to choose whether they wanted only text ads or video ads as well. Maybe in the future.
