### ISSUE TITLE
Can't close floating player when video has Cards active

### ISSUE THREAD

**Issue by grandta13** [ParticleCore/Particle#663]
Browser Name: Google Chrome

Browser Version: 63.0.3239.132 (Official Build) (64-bit)

Operating System: Windows 8.1 Pro 6.3.9600 Build 9600

Software Type: Userscript

Software Version: 1.9.6

Userscript Manager: Tampermonkey

Userscript Manager Version: 4.5

When the floating player is active after the user has navigated away from the video page, the user will be unable to close the floating player if the video has Cards active, as the Cards icon will completely cover the 'X' button, rendering it un-clickable.

**Comment by ParticleCore** [comment]
Can you provide a screenshot example?

**Comment by grandta13** [comment]
Also, I failed to mention that this bug only presents itself when annotations are enabled in Iridium's settings.
![iridiumcardsbug](https://user-images.githubusercontent.com/19246418/35887410-2b8c5712-0b62-11e8-9399-f64c61326aa0.png)

**Comment by ParticleCore** [comment]
I see, I thought you were referring to the end screen cards that show linking to channels and other videos, will see what I can do to fix this.

**Comment by ParticleCore** [comment]
Closed due to #680
