### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by qsi68824** [ParticleCore/Particle#669]
Hello there,

I would like to ask if you could add two additional Features to your AddOn.

1. Speed: It is possible to set the standard Video-Quality. Could you add a variant to set the standard Play-Speed (0.25 | 0.5 | 0.75 | Standard | 1.25 | 1.5 | 2.0)?
2. Could you add also a "Black Theme" for YouTube and not only the AddOn itself. For example, like this AddOn: https://addons.mozilla.org/en-US/firefox/addon/dark-theme-for-youtube/ it is just about ~22kB big and let the user choose his preferred Background-Colour for YouTube.

PS: I don't know if this is the right way to ask for additional Features, I am still a Noob on gitHub. If not, I am sorry.

**Comment by ParticleCore** [comment]
> Due to time and framework limitations I am unable to accept any more feature requests.

https://github.com/ParticleCore/Particle/blob/master/README.md
