### ISSUE TITLE
Subtitles menu not listing subtitles

### ISSUE THREAD

**Issue by bennyhillthebest** [ParticleCore/Particle#675]
Browser Name: Firefox

  Browser Version: 58.0.2 (64 bit)

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: v1.9.6

  Userscript Manager: ViolentMonkey

  Userscript Version: v2.8.29

  Problem Description: subtitles are not available from the gear button -> subtitles menu, although clicking on subtitles button works. 

  Steps to reproduce: Example video - https://www.youtube.com/watch?v=Ek3aeUhHaFY - 13 subtitles, not available from the subtitles menu, but clicking on the subtitle button activates the browser-localized version of the subtitles.

  Additional details: 

Thanks a lot!

**Comment by ParticleCore** [comment]
> - This extension is only being supported for Firefox 48+, Chrome 42+ and Opera 42+, there are no plans to support any other browser in the future, including any fork of any type. If you are using a different browser then try running the extension in one of the supported versions.

https://github.com/ParticleCore/Particle/wiki/Report-a-problem
