### ISSUE TITLE
Option to add like and dislike button to infobar.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#70]
I mean something similar to option that adds "Watch Later" button to infobar. Unfortunately, the new YouTube HTML5 player don't have like and dislike button in infobar on embed YouTube videos/disabled autoplay on YouTube video page. Can you do something with it, please? :)

**Comment by ParticleCore** [comment]
Sorry but that is not a feature I am interested in adding for now, the "Watch later" option only took one line and it wasn't even directly related to that feature, it was only to show the infobar. To replicate the like/dislike buttons would require a lot more than what the previous feature needed.

I would suggest instead that you'd send Feedback to YouTube asking them to bring back the like/dislike buttons on the infobar, [they were there previously](http://googlesystem.blogspot.com/2013/08/20-things-to-do-using-youtubes-embedded.html), I don't know why they removed them. You can send the feedback via the "Send feedback" link found at the bottom of every YouTube page.

**Comment by Piter432** [comment]
Okay, thank you for information :)
