### ISSUE TITLE
Quality selection is restricted

### ISSUE THREAD

**Issue by Skellingtor** [ParticleCore/Particle#74]
Quality selection on videos is restricted to 720p, 360p and auto no matter the top quality I select. When the script is turned off, all the available qualities show up.

Latest version of Chrome and script, Mac 10.10.5.

Script on.
<img width="84" alt="screen shot 2015-09-09 at 21 07 21" src="https://cloud.githubusercontent.com/assets/14208293/9777265/2442f294-5738-11e5-9a65-0e87f3735ac5.png">

Script off.
<img width="89" alt="screen shot 2015-09-09 at 21 10 36" src="https://cloud.githubusercontent.com/assets/14208293/9777271/319bfe90-5738-11e5-9f83-2f2dd3d9332e.png">

**Comment by Zarggg** [comment]
If you have DASH playback disabled, you will need to toggle that option. Those are the only two qualities available on YouTube in non-DASH format.

**Comment by Skellingtor** [comment]
Really? Well, bummer. At least I know why I had no 60fps. Thanks!

**Comment by ParticleCore** [comment]
It was clearly explained in the wiki:

> (...) but the only available quality options with DASH disabled are 720p and below.

https://github.com/ParticleCore/Particle/wiki/Features#dash_off
