### ISSUE TITLE
[Feature Request] Add rating bars to thumbnails

### ISSUE THREAD

**Issue by FatOrangutan** [ParticleCore/Particle#75]
Would it be possible for you to add rating bars below every thumbnail, on say search results pages, video suggestions etc.?
Thanks.

**Comment by ParticleCore** [comment]
Sorry but this is not a feature I am interested in adding for now.

**Comment by foss-** [comment]
I would highly like to see this feature. I understand you closed this due to prioritization but yet wanted to add my +1 since I thinks this imrpoves using YouTube a lot.

**Comment by FatOrangutan** [comment]
@foss- , not too sure if you aware of the alternatives, but I settled with a modified version of [this script](https://greasyfork.org/en/scripts/2302-youtube-video-ratings-bar-with-power-meter). I basically just deleted all the power meter stuff in it.

**Comment by foss-** [comment]
Ended up using https://addons.mozilla.org/de/firefox/addon/youtube-bogus-remover/ in Firefox. It just would be great to have this together in one solution. But as mentioned, prioritizing is totally legit (:
