### ISSUE TITLE
Remember repeat option

### ISSUE THREAD

**Issue by otsug** [ParticleCore/Particle#8]
I loved the extension is very light but at the moment I need to remember to click repeat each time I open a new video, also when I refresh the page the repeat is off, so I would like the option for the repeat to be on in all the videos by default.

**Comment by Yonezpt** [comment]
I've never considered a user would want this option to be always on, always thought it would be a per video case scenario. Will add it to the options list.

**Comment by ParticleCore** [comment]
I've never considered a user would want this option to be always on, always thought it would be a per video case scenario. Will add it to the options list.

**Comment by otsug** [comment]
I think something happened after version 0.4.4 or so ( I could be wrong on this exactly, but on 0.3.x was working ), now to remember the repeat I need to disable the enabled repeat button and click on enable again to work, and if I refresh the page I have to do it again. I am using the firefox extension on firefox 40 64 bits with the new HTML5 youtube on windows 10, I thought was the windows or firefox update but I just discovered that clicking the repeat button as described above made work again. Thank you.

**Comment by ParticleCore** [comment]
@otsug Seems like the recent YouTube player update adds a delay which causes the feature to fail since it runs before the player exists, will try to fix it as soon as possible. Also please open a new issue in the future, otherwise I will have difficulty knowing which issues are active or not.

**Comment by ParticleCore** [comment]
@otsug I have pushed the fix with the version 0.4.9, let me know if it is working correctly again.

**Comment by otsug** [comment]
Thank you, 0.4.9 seems to be working fine now, I was not sure if I should have created a new issue or not, so next time I will create another instead of commenting in case the issue is already closed.

**Comment by ParticleCore** [comment]
The change has been made to memorize the option because if you want to turn off repeat you can can turn off even if it is memorized, but you cannot have it to stay on when changing videos if it doesn't memorize.

**Comment by q1k** [comment]
What I was trying to say is, to only enable the repeat on that particular video, so when I open a new video or reload the page, the repeat is disabled.

**Comment by ParticleCore** [comment]
I understood, and I explained that if I were to do that (which is how it behaved initially) then users that want the repeat to stay on would not have that ability anymore.

**Comment by q1k** [comment]
so make additional checkbox?

**Comment by ParticleCore** [comment]
Not an option, or else I would also have to create the same for every other similar toggle function. It will stay as it is for now.

**Comment by q1k** [comment]
and which other are togglable? except for the cinema mode

**Comment by q1k** [comment]
The most annoying thing is -I have to constantly disable the repeat. :@

So just add another checkbox, whether repeat will remember the state forever; or just for that page until reloaded.
