### ISSUE TITLE
Feature request: Video quality (resolution, frame rate) as thumbnail overlay

### ISSUE THREAD

**Issue by zmwangx** [ParticleCore/Particle#80]
Coming from YouTubeCenter, this is one thing that I miss (screenshot at the bottom to show what I have in mind). Basically, I would love to see the video quality overlaid on thumbnails, preferably lazily loaded upon mouse over.

Justification: For some of us, the quality of a video is one of the deciding factors of whether we'll even open a video or not. This is especially useful for, e.g., searching for older music videos, when I might already have access and just looking for a high quality version.

I see that a related feature requests — #75 (YouTubeCenter-style rating overlay) — is either turned down or deferred, but I would like to stress that resolution and frame rate, being hard stats of a video, are much more essential than ratings (which I don't really care).

![screen shot 2015-09-20 at 8 15 43 pm](https://cloud.githubusercontent.com/assets/4149852/9984832/7d025a24-5fd4-11e5-84a1-2257ce163243.png)

**Comment by ParticleCore** [comment]
I understand that for each request the user finds the feature useful, but I cannot add features on that criteria so I must consider wether I find it to be worth adding or not. You might find the file details more relevant, others might find the ratings more relevant and others might even prefer to have none of the previously mentioned and instead have the video play in the thumbnail when hovering with the mouse.

There's plenty of features that could be added, however with a website that is changing so frequently causing many features to stop working, the maintenance and overhead would be tremendous so adding features must be controlled especially when I am trying to keep the software as light and small as possible.

With that said I still don't intend to add this feature for now. This doesn't mean that I will never add this feature, I always keep every request in consideration, there have been quite a few "rejected" features that I have implemented.

**Comment by zmwangx** [comment]
> I understand that for each request the user finds the feature useful, but I cannot add features on that criteria so I must consider wether I find it to be worth adding or not.

I fully understand. I just added my own justifications. I did not speak for anyone else.

**Comment by Yoiink** [comment]
I'd also like to add that I liked this feature of YoutubeCenter.

The ratings & thumbnail hover was also very useful. When searching for something quite vague or a tutorial on something, the preview of like:dislike & video quality is useful for finding the video you actually want to watch without having to trawl through a load of garbage first.

**Comment by q1k** [comment]
This is one of the features I miss from YTC

**Comment by s0j0urn** [comment]
@ParticleCore 
I do understand that you have already said that this feature is not in consideration and due to time limitations you are not accepting any new feature requests. However, I'd also like to add my vote to feature requests for showing like/dislike ratio on video thumbnails and may be showing video quality as well on  mouse hover.
In case, you get some time and decide to add more features to already awesome YouTube Plus it will be great if this request can be considered on priority.

Thank you for the YouTube Plus.

**Comment by thegrandpow** [comment]
Need the quality indicator and the animations so bad.
