### ISSUE TITLE
Feature request: hide trending hashtags and recommended channels from YouTube homepage

### ISSUE THREAD

**Issue by zmwangx** [ParticleCore/Particle#81]
My home page (i.e., https://www.youtube.com/) is always flooded with trending hashtags (say #Sports) or recommended channels ("Recommended channel for you", say TaylorSwiftVEVO), which are beyond annoying. (You probably know what I'm talking about; if not, there's a screenshot at the bottom.)

I would love to see an option to hide those cards (i.e., `item-section`s).

![screen shot 2015-09-20 at 8 29 02 pm](https://cloud.githubusercontent.com/assets/4149852/9984928/8d42da56-5fd6-11e5-8eaf-90a2854ae3d2.png)

**Comment by ParticleCore** [comment]
YT+ contains a blacklist feature which you can use to add any channel you want and it will remove it from any suggestions: https://github.com/ParticleCore/Particle/wiki/Features#blacklist_on

You should see the following buttons whenever your mouse is over the thumbnails

![thumb_mod](https://cloud.githubusercontent.com/assets/9222661/9985078/33039524-6014-11e5-8c69-c2d020d2ac79.png)

Is it not working?

**Comment by zmwangx** [comment]
They do work, but

1. I don't really want to block all the recommended channels (I would happily accept their videos in relevant search results). I just don't want to see them on the home page.

2. If you block some, YouTube will just throw other channels at you the next time you load the home page.

**Comment by zmwangx** [comment]
And a little bit about a possible implementation: recommended channels all have `Recommended channel for you` in `span.shelf-annotation shelf-title-annotation`, and hashtags will have a `by <a href="...">#blah</a>` in that same span, so they shouldn't be too hard to detect.

**Comment by ParticleCore** [comment]
I see, but I don't find this enhancement to be worth adding. Also targeting elements by their text content would be a bad method of achieving this, it would stop working for anyone using YouTube with a non-English language.

**Comment by zmwangx** [comment]
Okay.
