### ISSUE TITLE
Comments won't load version 0.6.6

### ISSUE THREAD

**Issue by turmoggy** [ParticleCore/Particle#83]
![2015-09-21_09-37-56](https://cloud.githubusercontent.com/assets/6471906/9993210/89f70ce6-6044-11e5-933b-3429f76d877a.png)

**Comment by ParticleCore** [comment]
Please provide more details: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by turmoggy** [comment]
Chrome 45.0.2454.93 m (64-bit)
Tampermonkey
Windows 10 64 Bit 
Disabled other scripts. 

I have enable comments in the settings and it just shows a loading screen. Previous version of youtube+ worked fine.

**Comment by ParticleCore** [comment]
The latest update contained a new method for the comments section when it was set to hide, by an oversight this issue you mentioned remained unfixed, will address it at once.

**Comment by ParticleCore** [comment]
I have fixed this with the new version 0.6.7, let me know if it is fixed for you as well.

**Comment by MrSmite** [comment]
Comments still don't load when set to "show".

* Win 7 SP-1 x64 (Also tried on Win XP SP-3 x86)
* Firefox 40.0.3
* Using the Firefox Add-on, not a Greasemonkey script

**Comment by ParticleCore** [comment]
@MrSmite Thank you for bringing this to my attention. The problem is fixed, but for some reason during the recent add-on transition that version did not ship with the update, will address this immediately.

**Comment by ParticleCore** [comment]
@MrSmite I have updated the add-on version to 0.6.8 which has the fix working correctly, let me know if it is working for you as well.

**Comment by MrSmite** [comment]
@ParticleCore Thanks, that fixed the comment issue.
