### ISSUE TITLE
Player doesn't remember mode

### ISSUE THREAD

**Issue by MrSmite** [ParticleCore/Particle#84]
__Version:__ 0.6.7
__OS:__ Win 7 SP-1 x64, Win XP SP-3 x86
__Browser:__ Firefox 40.0.3
__Add-on or Script:__ Add-on

__Bug:__

When you switch the player to "theater mode" and close a tab, the video reverts to the smaller 'default view' the next time you open a video.

**Comment by ParticleCore** [comment]
Related to incompatibility with the Flash Player:

>At the moment no support will be provided outside these platforms. YT+ supports only YouTube's HTML5 player, some features will not work when using YouTube's flash player.

https://github.com/ParticleCore/Particle/wiki
