### ISSUE TITLE
'Player Always Visible' Causes Floating Player Off Screen

### ISSUE THREAD

**Issue by MrSmite** [ParticleCore/Particle#85]
__Version:__ 0.6.7
__OS:__ Win 7 SP-1 x64, Win XP SP-3 x86
__Browser:__ Firefox 40.0.3
__Add-on or Script:__ Add-on

__Bug:__

When you enable the "Player always visible when reading comments" otpion, scrolling the page to where the video would be out of view causes it to detach and float over the "up next" sidebar on the right with half the video off screen.

Also, when the video ends, the "suggested videos" at the end of the video exhibit the same pop / float behavior.

**Comment by Eisys** [comment]
You should add pictures of what exactly is happening!

**Comment by ParticleCore** [comment]
Are you using the Flash player? Right click on the YouTube player and see if the menu shows

**Comment by MrSmite** [comment]
> Are you using the Flash player

Yes, I am.

**Comment by ParticleCore** [comment]
Then that is the problem. The guide to report problems informed very clearly about YT+ and Flash player:

>Make sure you are not using the Flash player. Right click on your player and see if it lists "About Adobe Flash Player ..."

> - The software works with the Flash player, but many features do not simply because they are not compatible or possible to work with the limitations imposed by this player type. The only solutions are to use the HTML5 player by visiting this link and activating it: https://www.youtube.com/html5 or to use the Flash player without using the incompatible features

https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by MrSmite** [comment]
Thanks, I must admit I hadn't read the reporting guide.
