### ISSUE TITLE
Disabling autoplay for embed YouTube videos.

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Particle#87]
As title says. This should be helpful especially for sites where embed YouTube videos are set by admin of that website to play automatically. I can add a link to example site to precise my request, but be careful – that site has a lot (I think) ads (stupid polish websites -_-).

**Comment by ParticleCore** [comment]
Sorry, but due to the vast amount of different ways pages can embed YouTube videos and manipulate them, I decided to not extend support for those.
