### ISSUE TITLE
Bit of lag with player size changing.

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Particle#88]
When I scroll down the small player comes up but there is just a little bit of lag when the video itself changes size. For a splitsecond I can only see the top left corner of the video in the small player.
Same with when scrolling back up. I can see the tiny video in the top left of the big player for a splitsecond before it resizes to the player.
This is a pretty small thing but didn't happen before with 0.6.8.

Chrome 45.0.2454.101 m (64-bit) with YT+ 0.6.9 running on Tamper.

**Comment by ParticleCore** [comment]
It was an enhancement I made, the lag is already part of the native YouTube player code, but my enhancement was causing positioning problems on certain video elements, it was pushing them outside the player so I had to remove it for now until I can find a better way of doing this without affecting the player elements.

**Comment by ParticleCore** [comment]
The lag should be gone with the latest update, let me know if it works well for you too.

**Comment by Eisys** [comment]
Yep, its gone in 0.7.0.
Thank you.
