### ISSUE TITLE
Can't play some videos when "Autoplay videos" is disabled

### ISSUE THREAD

**Issue by jsayol** [ParticleCore/Particle#90]
As of today I cannot play ~~any video~~ *some videos* when the "Autoplay videos" option is disabled ~~(probably due to some changes on the YouTube side)~~. 

I tried clicking on the video and pressing the space bar but nothing happens. No errors appear on the console.

Browser: Chrome 45.0.2454.93 (64 bit)
OS: Xubuntu 15.04 amd64

**Comment by Piter432** [comment]
The problem is somewhere in the YouTube+ code. I've reverted back to version 0.6.8 and now I can watch videos with disabled autoplay.

**Comment by jsayol** [comment]
Then it must be related to the fix for issue #82.

**Comment by jsayol** [comment]
I tried enabling "Disable advertisements outside the video page" as per #issuecomment-142061533 and now i can play videos properly with "Autoplay videos" disabled.

I don't have Noscript installed, though I use uBlock Origin and Ghostery (not sure if any of those might be related.)

**Comment by Eisys** [comment]
I can confirm this happening as well.

**Comment by jsayol** [comment]
For reference, here are a couple of videos. One of them plays and the other doesn't.

Plays OK: https://www.youtube.com/watch?v=ZREp1mAPKTM
Doesn't play: https://www.youtube.com/watch?v=qHO9gARac-w

**Comment by phineasthecat** [comment]
Can also confirm this happening. Disabling "Disable advertisements outside the video page" doesn't change anything for me; videos still won't work until I enable autoplay.

Using the userscript version of 0.6.9 with Greasemonkey 3.4.1 and Firefox 38.3.0 on Win7.

**Comment by ParticleCore** [comment]
This is a problem with the recent autoplay testing I included to prevent the issues with a recent change to the YouTube player as a result of a certain script being blocked, either by NoScript or an adblocker . I am currently trying to find a better solution, otherwise I might revert to the previous method.

**Comment by ParticleCore** [comment]
From what I could see so far YouTube has changed the way it packages video ads. This change is probably what caused the [general ad block failure reported recently](https://www.reddit.com/r/youtube/comments/3jv00z), fortunately the ad blockers' issue has been patched unfortunately it changed the way the YouTube player works.

If the video has ads but it fails to load the ads then it tries to play an empty pre-roll ad, completely ignoring the autoplay state. This behavior has been persistent across multiple tests with videos containing ads of different types, no matter what ad type it had it will always play the video normally and the progress bar will show a yellow dot at the start. It is for this reason that the autoplay disabled works correctly if YT+ is set to disable video ads, but not when it allows them.

I have found a way to patch this for the time being and will update it soon after doing further tests.

**Comment by ParticleCore** [comment]
Version 0.7.0 should fix this problem, let me know if it works for you too.

**Comment by phineasthecat** [comment]
0.7.0 fixed it! Thanks.

**Comment by jsayol** [comment]
Yep, it works now. Thanks! :)
