### ISSUE TITLE
When Playing, Sometimes Video Position is Wrong

### ISSUE THREAD

**Issue by hamkah2c** [ParticleCore/Particle#92]
Browser Name: Chrome

Browser Version: 45.0.2454.101 m (64-bit)

Operating System: Win7 64 bit

Software Type: Extension

Software Version: 0.7.0

As example, the normal video is like this:
![image](https://cloud.githubusercontent.com/assets/8862875/10155737/0de2769e-66a3-11e5-99a3-944dacc0b418.png)

But, if I active the extension, is look like this:
![image](https://cloud.githubusercontent.com/assets/8862875/10155757/398cbac0-66a3-11e5-89db-8572f0dfe876.png)
Example video: 
https://www.youtube.com/watch?v=Gd9OhYroLN0
https://www.youtube.com/watch?v=Pgum6OT_VH8
https://www.youtube.com/watch?v=kbbA9BhCTko

and many-many more.

**Comment by ParticleCore** [comment]
Press `Ctrl + F5`, see if the problem still persists.

**Comment by hamkah2c** [comment]
yup, it's normal again now :+1:
