### ISSUE TITLE
Video not centered when Watching from 1200p monitor on fullscreen

### ISSUE THREAD

**Issue by meve90** [ParticleCore/Particle#93]
When you watch a 1080p video from a 1200p monitor on fullscreen it should center the video and apply a black box on top and botton of my screen.
From yesterday it now put the video all on the top leaving a big black box on the botton.
![1200pnotcentered](https://cloud.githubusercontent.com/assets/14894316/10173429/713b6ee4-66e4-11e5-98c8-57fc4c993f52.png)

**Comment by meve90** [comment]
forgot to say that when I disable the addon it become centered again

**Comment by ParticleCore** [comment]
Thanks for bringing this to my attention, press `Ctrl + F5` and see if the problem is now fixed.

**Comment by meve90** [comment]
it's fixed now, thx
