### ISSUE TITLE
Default video quality doesn't work anymore

### ISSUE THREAD

**Issue by meve90** [ParticleCore/Particle#96]
I have default 720p but It switch to 480 auto when (I think) my connection can't handle 720p.
It's a recent thing, before it would just stay at default quality and just buffer.

**Comment by ParticleCore** [comment]
An oversight on my part when trying to improve the autoplay control issue https://github.com/ParticleCore/Particle/issues/90, a fix is already created but since I am also improving the settings system it might take a bit longer to upload this version this time.

**Comment by ParticleCore** [comment]
I've uploaded a fix for this issue in version 0.7.3, let me know if it works for you as well.

**Comment by meve90** [comment]
It work now thx.

**Comment by Eisys** [comment]
Hey @ParticleCore , totally unrelated question but I didn't want to make a new issue. Is it better to use the script version with Tamper or the Chrome addon? I found myself not really needing Tamper anymore and since YT+ is in the chrome store, I wonder which version works better.

**Comment by ParticleCore** [comment]
@Eisys I've created the add-on and extension versions for the users that didn't want the userscript managers' overhead (which has decreaed significantly) or that just didn't want them at all, the different types of YT+ have no differences, the only significant one is that with the userscript there is more flexibility and the user is capable of tinkering with it as he sees fit. If you don't want to use Tampermonkey anymore then the YT+ extension type was made right for this purpose.
