### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by eggw** [ParticleCore/Particle#98]
I recently updated from the old AMO version (I was careful to delete the prefs for a clean reinstall, I'm assuming they're the ones with "particle" in about:config) and now, my settings get reset to the default every time I refresh the page or restart the browser. I am not forgetting to click "save".

EDIT: Tested with a brand new profile with only YT+ installed and the issue persists. Using Firefox 41.0.1 and the latest 0.7.3 YT+ release.

**Comment by ParticleCore** [comment]
Thank you for letting me know, I've uploaded a fix for this problem, let me know if it works correctly now.

**Comment by eggw** [comment]
I can confirm the fix works. Also, thanks for letting me know.
